import test from 'node:test';
import assert from 'node:assert/strict';
import { parseCamaraBudgetHtml, parseCamaraStaff, staffHeaders } from '../../apps/collector/src/camara-cabinet.ts';
import { parseSenateActiveStaff, parseSenateStaffPage } from '../../apps/collector/src/senate-staff.ts';
const quote=(value:string)=>`"${value.replaceAll('"','""')}"`;
test('snapshot da Camara usa URI oficial e rejeita unidade generica',()=>{const rows=[{ponto:'P_1',codGrupo:'2',grupo:'Secretario Parlamentar',nome:'Pessoa A',cargo:'SP01',lotacao:'GAB. 1/1 - DEPUTADA',atoNomeacao:'',dataNomeacao:'2026-01-02',dataInicioHistorico:'2026-01-03',dataPubNomeacao:'',funcao:'',uriLotacao:'https://dadosabertos.camara.leg.br/api/v2/deputados/10'},{ponto:'P_2',codGrupo:'1',grupo:'Efetivo',nome:'Pessoa B',cargo:'Analista',lotacao:'COMISSAO',atoNomeacao:'',dataNomeacao:'',dataInicioHistorico:'2020-01-01',dataPubNomeacao:'',funcao:'',uriLotacao:'https://dadosabertos.camara.leg.br/api/v2/orgaos/20'}];const csv=[staffHeaders.map(quote).join(';'),...rows.map(row=>staffHeaders.map(h=>quote(row[h])).join(';'))].join('\r\n');const parsed=parseCamaraStaff(Buffer.from('\uFEFF'+csv),'raw','2026-09-09T12:00:00.000Z',new Set(['10']));assert.equal(parsed.report.confirmed,1);assert.equal(parsed.report.ignoredUnits,1);assert.equal(parsed.rows[0]!.externalId,'10');assert.equal(parsed.rows[1]!.externalId,null);assert.equal(parsed.rows[1]!.matchStatus,'rejected')});
test('verba preserva limite proporcional, gasto e meses',()=>{const html='<h2>Verba de gabinete em 2026</h2><table><thead><tr><th>Mes</th><th>Valor disponivel (R$)</th><th>Valor gasto (R$)</th></tr></thead><tbody><tr><td>01</td><td>133.170,54</td><td>116.095,44</td></tr><tr><td>02</td><td>165.806,07</td><td>0,00</td></tr></tbody></table>';const rows=parseCamaraBudgetHtml(html,'10',2026,'raw');assert.equal(rows[0]!.availableCents,13317054);assert.equal(rows[0]!.spentCents,11609544);assert.equal(rows[1]!.spentCents,0);assert.throws(()=>parseCamaraBudgetHtml('<html>captcha</html>','10',2026,'raw'),/HTML de verba/)});
test('pagina individual do Senado preserva categorias, fcodigo e remove tabela responsiva duplicada',()=>{const table='<table><caption>Funcionários Comissionados</caption><thead><tr><th>Funcionário</th><th>Função</th><th>Nome da Função</th></tr></thead><tbody><tr><td><a href="detalhe.asp?fcodigo=123"><span>PESSOA A</span></a></td><td>AP-01</td><td>AJUDANTE PARLAMENTAR</td></tr></tbody></table>',third='<table><caption>Terceirizados</caption><thead><tr><th>Nome</th><th>Função</th><th>Empresa</th></tr></thead><tbody><tr><td>Pessoa B</td><td>Copeiro</td><td><a href="/contratos/99">Empresa</a></td></tr></tbody></table>';const rows=parseSenateStaffPage(`<h1>Pessoal de Gabinete em 2026</h1>${table}${third}${table}`,'4560',2026,'raw','2026-09-09T12:00:00Z');assert.equal(rows.length,2);assert.equal(rows[0]!.functionalId,'123');assert.equal(rows[0]!.relationship,'Comissionado');assert.equal(rows[1]!.relationship,'Terceirizado');assert.equal(rows[1]!.externalId,'4560')});
test('Senado preserva estagiário e classifica lotações da base ativa',()=>{const intern='<table><caption>Estagiários</caption><thead><tr><th>Estagiário</th><th>Área</th><th>Curso</th><th>Universidade</th><th>Início</th><th>Término</th></tr></thead><tbody><tr><td>Pessoa C</td><td>Direito</td><td>Direito</td><td>UnB</td><td>02/02/2026</td><td>01/02/2028</td></tr></tbody></table>',parsed=parseSenateStaffPage(`<h1>Pessoal de Gabinete em 2026</h1>${intern}`,'4560',2026,'raw','2026-09-09T12:00:00Z');assert.equal(parsed[0]!.relationship,'Estagiário');assert.equal(parsed[0]!.appointedAt,'2026-02-02');const csv='Nome;Tipo de Vínculo;Data de Admissão;Cargo;Categoria;Função;Afastamento;Isenção do Ponto;Jornada Semanal;Hierarquia Completa\nPessoa A;COMISSIONADO;01/01/2026;;;ASSESSOR;;;40 Horas;[SetorHierarquia[nome=SF - Senado Federal, prefixo=1., nivel=1], SetorHierarquia[nome=GSX - GABINETE DO SENADOR TESTE, prefixo=1.2., nivel=2]]';const active=parseSenateActiveStaff(Buffer.from('\uFEFF'+csv));assert.equal(active[0]!.unitKind,'cabinet');assert.equal(active[0]!.senatorName,'TESTE');assert.equal(active[0]!.relationship,'COMISSIONADO')});
