import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openDatabase, publishElection, publishedElections, publishedPersonElectoralProfile, startRun } from '@senadotracker/db';
import { saveRaw } from '../../apps/collector/src/raw.ts';
import { linkCandidacies, parseTseAssets, parseTseSimplified, parseTseTransactions } from '../../apps/collector/src/elections.ts';
import type { Profile } from '@senadotracker/domain';

const official={cand:[{sqcand:'10000000001',nm:'ALAN RICK MIRANDA',nmu:'ALAN RICK',n:'1111',cc:'UNIÃO',vap:'120000',st:'ELEITO POR QP'}]};
test('resultado simplificado preserva chave, voto e situação literal',()=>{const parsed=parseTseSimplified(official,{year:2022,round:1,uf:'AC',office:'Deputado Federal',rawId:'raw',officialUrl:'https://resultados.tse.jus.br/'});assert.equal(parsed[0]!.sequenceId,'10000000001');assert.equal(parsed[0]!.votes,120000);assert.equal(parsed[0]!.result,'ELEITO POR QP');assert.equal(parsed[0]!.elected,true)});
test('bens e contas preservam centavos, contraparte e versão',()=>{const assets=parseTseAssets([{SQ_CANDIDATO:'1',SQ_BEM_CANDIDATO:'b1',DS_BEM_CANDIDATO:'Casa',DS_TIPO_BEM_CANDIDATO:'Imóvel',VR_BEM_CANDIDATO:'1.234,56',NR_CONTROLE_CANDIDATO:'ret-2'}],'raw');const revenue=parseTseTransactions([{SQ_CANDIDATO:'1',SQ_RECEITA:'r1',NM_DOADOR:'Pessoa',VR_RECEITA:'10,50',NR_CONTROLE_CANDIDATO:'ret-2'}],'revenue','raw');assert.equal(assets[0]!.valueCents,123456);assert.equal(assets[0]!.version,'ret-2');assert.equal(revenue[0]!.valueCents,1050);assert.equal(revenue[0]!.counterparty,'Pessoa')});

test('nome sozinho não confirma e duplicidade fica ambígua',()=>{const candidacy=parseTseSimplified(official,{year:2022,round:1,uf:'AC',office:'Deputado Federal',rawId:'raw',officialUrl:'https://resultados.tse.jus.br/'});const profile={source:'camara',externalId:'1',name:'Alan Rick',fullName:'ALAN RICK MIRANDA',uf:'AC',party:'REPUBLICANOS',photoUrl:null,officialUrl:'https://camara.leg.br',observedAt:'2026-01-01',historyAvailability:'available',mandates:[],exercises:[],parties:[{key:'u',start:'2022-01-01',end:'2022-12-31',endReason:'reported',precision:'date',basis:'official',rawId:'r',partyId:null,party:'UNIÃO',mandateKey:null}],events:[],rawId:'r',personId:'p'} satisfies Profile&{personId:string};assert.equal(linkCandidacies(candidacy,[profile])[0]!.matchStatus,'confirmed');assert.equal(linkCandidacies(candidacy,[profile,{...profile,personId:'p2'}])[0]!.matchStatus,'ambiguous');assert.equal(linkCandidacies(candidacy,[{...profile,uf:'SP'}])[0]!.matchStatus,'pending')});

test('lote eleitoral mantém versões e só consulta vínculo confirmado',async()=>{const dir=await mkdtemp(join(tmpdir(),'election-'));const db=openDatabase(join(dir,'db.sqlite'));try{db.prepare('INSERT INTO people VALUES (?,?)').run('p','now');const run=startRun(db,'tse');const rawId=await saveRaw(db,run,dir,{url:'https://resultados.tse.jus.br/',fetchedAt:'2026-09-08T12:00:00.000Z',status:200,contentType:'application/json',bytes:Buffer.from(JSON.stringify(official))});const candidacy={...parseTseSimplified(official,{year:2022,round:1,uf:'AC',office:'Deputado Federal',rawId,officialUrl:'https://resultados.tse.jus.br/'})[0]!,personId:'p',matchStatus:'confirmed' as const,matchEvidence:['nome+UF','partido']};publishElection(db,run,{id:candidacy.electionId,year:2022,round:1,scope:'AC',officialUrl:candidacy.officialUrl},'partial','contas parciais',[candidacy],[{sequenceId:candidacy.sequenceId,assetId:'1',description:'Imóvel',kind:'Bem imóvel',valueCents:10000,version:'original',rawId}],[{sequenceId:candidacy.sequenceId,transactionId:'d1',kind:'revenue',counterparty:'Doador',counterpartyDocument:null,category:'Doação',description:null,valueCents:5000,date:'2022-08-01',version:'retificadora-1',rawId},{sequenceId:candidacy.sequenceId,transactionId:'x1',kind:'expense',counterparty:'Fornecedor',counterpartyDocument:null,category:'Publicidade',description:null,valueCents:3000,date:'2022-08-02',version:'original',rawId}]);const result=publishedElections(db,'p');assert.equal(result.length,1);assert.equal(result[0]!.assets[0]!.valueCents,10000);assert.equal(result[0]!.revenues[0]!.version,'retificadora-1');const profile=publishedPersonElectoralProfile(db,'p');assert.equal(profile.elections[0]!.assetTotalCents,10000);assert.equal(profile.elections[0]!.expenseTotalCents,3000);assert.equal(profile.patrimony[0]!.valueCents,10000);assert.match(profile.coverage.note,/vínculo confirmado/);assert.equal(db.prepare('SELECT max(version) version FROM schema_migrations').get()!.version, 36)}finally{db.close()}});

