import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openDatabase } from '@senadotracker/db';
import { assetHeaders, candidateHeaders, complementHeaders, importTseLocal, linkCandidacies, parseComplement, streamTseCsv } from '../../apps/collector/src/elections.ts';

const csv=(headers:readonly string[],values:Record<string,string>)=>`${headers.map(x=>`"${x}"`).join(';')}\r\n${headers.map(x=>`"${(values[x]??'#NULO#').replaceAll('"','""')}"`).join(';')}\r\n`;
test('leitor TSE trata Windows-1252, aspas e cabecalho divergente',async()=>{const dir=await mkdtemp(join(tmpdir(),'tse-csv-')),file=join(dir,'ok.csv');await writeFile(file,Buffer.from('"A";"B"\r\n"Jo\u00e3o";"texto; com separador"\r\n','latin1'));const rows=[];for await(const row of streamTseCsv(file,['A','B']))rows.push(row);assert.equal(rows[0]!.A,'Jo\u00e3o');assert.equal(rows[0]!.B,'texto; com separador');await assert.rejects(async()=>{for await(const row of streamTseCsv(file,['X']))void row},/TSE divergente/)});
test('complemento preserva estados e valores documentados',()=>{const details=parseComplement({ST_REELEICAO:'S',ST_DECLARAR_BENS:'N',ST_PREST_CONTAS:'#NULO#',VR_DESPESA_MAX_CAMPANHA:'1.234,56',SQ_ORDEM_SUPLENCIA:'2',DS_SITUACAO_JULGAMENTO:'DEFERIDO'});assert.equal(details.reelection,true);assert.equal(details.declaredAssets,false);assert.equal(details.accountsSubmitted,null);assert.equal(details.campaignLimitCents,123456);assert.equal(details.legalStatus,'DEFERIDO')});
test('vínculo eleitoral usa nome, UF e cargo mesmo sem histórico partidário do pleito',()=>{const candidacy={electionId:'e',sequenceId:'1',year:2022,round:1,office:'SENADOR',uf:'AL',name:'MARIA SILVA',ballotName:'MARIA',ballotNumber:null,party:'ABC',votes:null,result:null,elected:null,matchStatus:'pending' as const,personId:null,matchEvidence:[],officialUrl:'https://tse.test',rawId:'r'};const profile={source:'senado' as const,externalId:'10',personId:'p1',name:'Maria Silva',fullName:'Maria Silva',party:'XYZ',uf:'AL',photoUrl:null,email:null,officialUrl:'https://senado.test',observedAt:'2026-01-01',historyAvailability:'available' as const,mandates:[],exercises:[],parties:[],events:[],rawId:'profile-raw'};const linked=linkCandidacies([candidacy],[profile]);assert.equal(linked[0]!.matchStatus,'confirmed');assert.equal(linked[0]!.personId,'p1');assert.deepEqual(linked[0]!.matchEvidence,['nome oficial/urna','UF','cargo/senado'])});
test('dry-run reconcilia os tres layouts sem publicar',async()=>{const dir=await mkdtemp(join(tmpdir(),'tse-import-')),db=openDatabase(join(dir,'db.sqlite'));try{const cand=join(dir,'cand.csv'),asset=join(dir,'asset.csv'),comp=join(dir,'comp.csv');await writeFile(cand,Buffer.from(csv(candidateHeaders,{ANO_ELEICAO:'2022',NR_TURNO:'1',CD_ELEICAO:'546',DT_ELEICAO:'02/10/2022',DS_CARGO:'DEPUTADO FEDERAL',SQ_CANDIDATO:'1',NR_CANDIDATO:'1234',NM_CANDIDATO:'JOAO DA SILVA',NM_URNA_CANDIDATO:'JOAO',SG_UF:'SP',SG_PARTIDO:'ABC',DS_SIT_TOT_TURNO:'NAO ELEITO',DS_SITUACAO_CANDIDATURA:'APTO'}),'latin1'));await writeFile(asset,Buffer.from(csv(assetHeaders,{ANO_ELEICAO:'2022',SQ_CANDIDATO:'1',NR_ORDEM_BEM_CANDIDATO:'1',DS_TIPO_BEM_CANDIDATO:'VEICULO',DS_BEM_CANDIDATO:'CARRO',VR_BEM_CANDIDATO:'10.000,00'}),'latin1'));await writeFile(comp,Buffer.from(csv(complementHeaders,{ANO_ELEICAO:'2022',SQ_CANDIDATO:'1',ST_REELEICAO:'N',ST_DECLARAR_BENS:'S',ST_PREST_CONTAS:'S'}),'latin1'));const report=await importTseLocal(db,{year:2022,candidatesFile:cand,assetsFile:asset,complementFile:comp,rawDirectory:join(dir,'raw'),dryRun:true});assert.deepEqual(report.selected,{candidacies:1,assets:1,complements:1,excludedAssets:0,orphanAssets:0});assert.equal(report.links.pending,1);assert.equal(report.links.notFound,1);assert.equal(report.published,false);assert.equal(db.prepare('SELECT count(*) n FROM electoral_batches').get()!.n,0)}finally{db.close()}});
