import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowLeft,Building2,ExternalLink,MapPin,ReceiptText,Store,Users} from 'lucide-react';
import {validCnpj} from '@senadotracker/db';
import type {DataCoverage,Source} from '@senadotracker/domain';
import {supplierDetail} from '@/lib/data';
import {LegislativeSubnav} from '@/components/legislative-subnav';
import {InstitutionHero} from '@/components/heroes';
import {KpiCard,KpiGrid,CoverageBadge} from '@/components/metrics';
import {BarChart,LineChart} from '@/components/charts';
import {BrazilValueMap} from '@/components/brazil-state-map';
import {DataTable,type DataColumn} from '@/components/data-table';
import {PartyLogo} from '@/components/party-logo';
import {EmptyState} from '@/components/empty-state';
import {FilterBar} from '@/components/data-controls';
import {Card,CardContent,CardHeader} from '@/components/ui/card';

export const dynamic='force-dynamic';
type Params=Record<string,string|string[]|undefined>;
const scalar=(value:string|string[]|undefined)=>typeof value==='string'?value:undefined;
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),percent=new Intl.NumberFormat('pt-BR',{style:'percent',maximumFractionDigits:1}),months=['jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez'];
const formatCnpj=(value:string)=>value.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,'$1.$2.$3/$4-$5');
function href(document:string,values:Record<string,string|number|undefined>){const query=new URLSearchParams();for(const [key,value] of Object.entries(values))if(value!==undefined&&value!=='')query.set(key,String(value));return `/legislativo/fornecedores/${document}?${query}`}

export default async function SupplierDetailPage({params,searchParams}:{params:Promise<{documento:string}>;searchParams:Promise<Params>}){
  const route=await params,query=await searchParams,document=route.documento.replace(/\D/g,'');if(!validCnpj(document))notFound();
  const sourceValue=scalar(query.casa),source:Source|undefined=sourceValue==='senado'||sourceValue==='camara'?sourceValue:undefined,requestedYear=Number(scalar(query.ano)),year=Number.isInteger(requestedYear)?requestedYear:undefined,rawPage=Number(scalar(query.pagina)??1),page=Number.isSafeInteger(rawPage)&&rawPage>0?rawPage:1,result=supplierDetail({document,page,pageSize:25,...(source?{source}:{}),...(year?{year}:{})});
  if(result.status==='unavailable')return <><LegislativeSubnav/><main className="page-shell py-12"><EmptyState title="Fornecedor indisponível" description={result.message}/></main></>;if(!result.data)notFound();const data=result.data;
  type Person=(typeof data.people)[number];const columns:DataColumn<Person>[]=[{key:'rank',header:'Posição',align:'right',render:item=><strong>{item.rank}º</strong>},{key:'person',header:'Parlamentar',render:item=><div><Link className="font-bold text-primary underline" href={`/parlamentares/${item.source}/${item.externalId}`}>{item.profile.name}</Link><small className="mt-1 flex items-center gap-1.5 text-muted-foreground"><PartyLogo party={item.profile.party} size={20}/>{item.profile.party}/{item.profile.uf} · {item.source==='senado'?'Senado':'Câmara'}</small></div>},{key:'value',header:'Valor líquido',align:'right',render:item=><strong>{money.format(item.valueCents/100)}</strong>},{key:'share',header:'Participação',align:'right',render:item=>item.share===null?'—':percent.format(item.share)},{key:'records',header:'Lançamentos',align:'right',render:item=>item.records}];
  const aliases=data.aliases.filter(name=>name!==data.name),base={casa:source,ano:data.year};
  return <><LegislativeSubnav/><main id="conteudo" tabIndex={-1}><div className="page-shell py-8"><Link href={href(document,{...base,pagina:undefined}).replace(`/${document}`, '')} className="mb-4 inline-flex items-center gap-2 text-sm font-bold text-primary"><ArrowLeft size={16}/>Voltar ao radar</Link><InstitutionHero context="Fornecedor identificado nas cotas parlamentares" title={data.name} description={`CNPJ ${formatCnpj(document)} · pagamentos agregados a partir dos lançamentos oficiais de CEAPS e CEAP.`} imageUrl="/congresso.svg" location={source?source==='senado'?'Senado Federal':'Câmara dos Deputados':'Senado Federal e Câmara dos Deputados'} actions={<a className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2 text-sm font-bold text-foreground" href="https://www.gov.br/receitafederal/pt-br/assuntos/cadastros/cnpj">Consultar CNPJ na Receita <ExternalLink size={14}/></a>}/></div>
  <section className="page-shell py-8"><FilterBar action={`/legislativo/fornecedores/${document}`} fields={[{name:'casa',label:'Casa',value:source??'',options:[{value:'',label:'Congresso'},{value:'senado',label:'Senado'},{value:'camara',label:'Câmara'}]},{name:'ano',label:'Ano',value:String(data.year),options:data.years.map(value=>({value:String(value),label:String(value)}))}]}/></section>
  <section className="border-y bg-card"><div className="page-shell py-10"><KpiGrid className="xl:grid-cols-3"><KpiCard label="Total líquido recebido" value={money.format(data.totalCents/100)} coverage={data.coverage} comparison={`${data.records.toLocaleString('pt-BR')} lançamentos`} icon={ReceiptText}/><KpiCard label="Parlamentares pagadores" value={data.parliamentarians} coverage={data.coverage} comparison={`${data.ufs} UFs · ${data.parties} partidos`} icon={Users}/><KpiCard label="Ticket médio por lançamento" value={data.ticketAverageCents===null?'—':money.format(data.ticketAverageCents/100)} coverage={data.coverage} comparison={`em ${data.year}`} icon={Store}/><KpiCard label="Concentração no maior pagador" value={data.top1Share===null?'—':percent.format(data.top1Share)} coverage={data.coverage} comparison="participação no total" icon={Users}/><KpiCard label="Concentração nos 5 maiores" value={data.top5Share===null?'—':percent.format(data.top5Share)} coverage={data.coverage} comparison="participação no total" icon={Users}/><KpiCard label="Casas com pagamentos" value={data.houses.length} coverage={data.coverage} comparison={data.houses.map(item=>item.label==='senado'?'Senado':'Câmara').join(' e ')} icon={Building2}/></KpiGrid></div></section>
  <section className="page-shell space-y-14 py-14"><section><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-3xl font-bold">Identificação publicada</h2><p className="mt-2 text-sm text-muted-foreground">O nome abaixo foi informado nos lançamentos de cota e não equivale a validação cadastral pela Receita Federal.</p></div><CoverageBadge coverage={data.coverage as DataCoverage}/></div><Card className="mt-5"><CardContent className="grid gap-5 p-6 md:grid-cols-2"><div><p className="text-xs font-bold uppercase text-muted-foreground">Nome mais recorrente</p><p className="mt-2 text-xl font-black">{data.name}</p><p className="mt-2 font-mono text-sm">{formatCnpj(document)}</p></div><div><p className="text-xs font-bold uppercase text-muted-foreground">Também aparece como</p>{aliases.length?<ul className="mt-2 space-y-1 text-sm">{aliases.map(name=><li key={name}>{name}</li>)}</ul>:<p className="mt-2 text-sm text-muted-foreground">Nenhuma variação adicional no recorte.</p>}</div></CardContent></Card></section>
  <section className="grid gap-6 xl:grid-cols-2"><BarChart title="Pagamentos por categoria (R$)" data={data.categories.map(item=>({label:item.label,value:item.valueCents/100}))} coverage={data.coverage}/><div><h2 className="mb-4 text-2xl font-bold">Onde recebe mais?</h2><BrazilValueMap values={data.states}/></div></section>
  <section className="grid gap-6 xl:grid-cols-2"><div><BarChart title="Pagamentos por partido (R$)" data={data.partyGroups.map(item=>({label:item.label,value:item.valueCents/100}))} coverage={data.coverage}/><div className="mt-4 flex flex-wrap gap-2">{data.partyGroups.map(item=><div key={item.label} className="flex items-center gap-2 rounded-full border bg-card px-3 py-2 text-sm"><PartyLogo party={item.label} size={22}/><strong>{item.label}</strong><span className="text-muted-foreground">{money.format(item.valueCents/100)}</span></div>)}</div></div><BarChart title="Pagamentos por Casa (R$)" data={data.houses.map(item=>({label:item.label==='senado'?'Senado':'Câmara',value:item.valueCents/100}))} coverage={data.coverage}/></section>
  <LineChart title={`Evolução mensal dos pagamentos em ${data.year} (R$)`} data={data.months.map(item=>({label:months[item.month-1]!,value:item.valueCents===null?null:item.valueCents/100}))} coverage={data.coverage}/>
  <section id="parlamentares"><h2 className="text-3xl font-bold">Quem pagou este fornecedor?</h2><p className="mt-2 text-sm text-muted-foreground">Ranking pelo valor líquido identificado no mesmo recorte. Cada linha abre o perfil parlamentar.</p><div className="mt-5"><DataTable caption="Parlamentares pagadores" rows={data.people} columns={columns} rowKey={item=>`${item.source}:${item.externalId}`} coverage={{...data.coverage,sampleSize:data.peopleTotal}} page={page} pageCount={Math.max(1,Math.ceil(data.peopleTotal/data.pageSize))} pageHref={next=>href(document,{...base,pagina:next>1?next:undefined})}/></div></section>
  <Card><CardHeader><h2 className="flex items-center gap-2 text-xl font-bold"><MapPin size={19}/>Como ler esta página</h2></CardHeader><CardContent className="space-y-2 text-sm leading-6 text-muted-foreground"><p>Valores representam pagamentos líquidos registrados nas cotas parlamentares, preservando estornos publicados.</p><p>Categorias funcionam como contexto do gasto; não afirmam CNAE, ramo empresarial, endereço, sócios ou situação cadastral.</p><p>Páginas são criadas somente para CNPJ com dígitos verificadores válidos. CPF e fornecedor sem documento ficam fora deste detalhamento público.</p><p>Concentração é uma pista para consulta dos documentos oficiais e não indica, isoladamente, irregularidade.</p></CardContent></Card></section></main></>;
}
