import type { DatabaseSync } from 'node:sqlite';
import { distribution, searchText, type DataCoverage, type Expense, type Profile, type Source } from '@senadotracker/domain';
import { partyAtDate } from './parties.ts';

const mean=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null;
const net=(row:Expense)=>row.netCents-row.refundCents;
const normalizeSupplier=(row:Expense)=>searchText([row.supplierDocument,row.supplier].filter(Boolean).join(':'))||'nao-informado';

export function publishedExpenseDetail(db:DatabaseSync,source:Source,externalId:string,year:number){
  if(!Number.isInteger(year)||year<2008||year>2100)throw new Error('Ano inválido');
  const profileRow=db.prepare(`SELECT p.payload FROM profiles p JOIN active_publications a ON a.batch_id=p.batch_id WHERE a.source=? AND p.external_id=?`).get(source,externalId);if(!profileRow)return null;const profile=JSON.parse(String(profileRow.payload)) as Profile;
  const batch=db.prepare(`SELECT b.id,b.published_at,b.record_count FROM expense_batches b JOIN active_expense_publications a ON a.batch_id=b.id WHERE a.source=? AND a.year=?`).get(source,year);if(!batch){const coverage:DataCoverage={availability:'unavailable',source,period:{from:`${year}-01-01`,to:`${year}-12-31`,grain:'year'},batchId:null,note:'Não há lote anual de cota publicado para esta Casa.',sampleSize:0};return{source,year,profile,coverage,totalCents:null,categories:[],months:[],suppliers:[],topSupplier:null,benchmarks:null,highlights:[]}}
  const rows=db.prepare('SELECT * FROM expenses WHERE batch_id=? AND external_id=? ORDER BY month,record_key').all(String(batch.id),externalId).map(row=>({source:String(row.source) as Source,externalId:String(row.external_id),year:Number(row.year),month:Number(row.month),recordKey:String(row.record_key),categoryCode:String(row.category_code),category:String(row.category),supplier:row.supplier?String(row.supplier):null,supplierDocument:row.supplier_document?String(row.supplier_document):null,documentNumber:row.document_number?String(row.document_number):null,documentId:row.document_id?String(row.document_id):null,documentUrl:row.document_url?String(row.document_url):null,issuedAt:row.issued_at?String(row.issued_at):null,grossCents:row.gross_cents===null?null:Number(row.gross_cents),deductionCents:Number(row.deduction_cents),netCents:Number(row.net_cents),refundCents:Number(row.refund_cents),installment:row.installment===null?null:Number(row.installment),detail:row.detail?String(row.detail):null,rawId:String(row.raw_id)} satisfies Expense));
  const observedMonths=new Set(db.prepare('SELECT DISTINCT month FROM expenses WHERE batch_id=? ORDER BY month').all(String(batch.id)).map(row=>Number(row.month))),lastMonth=Math.max(...observedMonths,0),totalCents=rows.reduce((sum,row)=>sum+net(row),0);
  const group=<T>(key:(row:Expense)=>string,display:(row:Expense)=>T)=>{const map=new Map<string,{label:T;valueCents:number;records:number}>();for(const row of rows){const id=key(row),current=map.get(id)??{label:display(row),valueCents:0,records:0};current.valueCents+=net(row);current.records++;map.set(id,current)}return[...map.values()].sort((a,b)=>b.valueCents-a.valueCents||String(a.label).localeCompare(String(b.label),'pt-BR'))};
  const categories=group(row=>row.categoryCode||searchText(row.category),row=>row.category).map(item=>({...item,share:totalCents>0?item.valueCents/totalCents:null}));
  const suppliers=group(normalizeSupplier,row=>row.supplier??'Fornecedor não informado').map(item=>({...item,share:totalCents>0?item.valueCents/totalCents:null})),topSupplier=suppliers[0]??null;
  const personalByMonth=new Map<number,number>();for(const row of rows)personalByMonth.set(row.month,(personalByMonth.get(row.month)??0)+net(row));
  const allRows=db.prepare(`SELECT e.external_id,e.month,sum(e.net_cents-e.refund_cents) value FROM expenses e WHERE e.batch_id=? GROUP BY e.external_id,e.month`).all(String(batch.id));const profiles=new Map(db.prepare(`SELECT p.external_id,p.payload FROM profiles p JOIN active_publications a ON a.batch_id=p.batch_id WHERE a.source=?`).all(source).map(row=>[String(row.external_id),JSON.parse(String(row.payload)) as Profile]));const cutoff=`${year}-${String(lastMonth).padStart(2,'0')}-28`,party=partyAtDate(profile,cutoff)??profile.party;
  const monthlyGroups=new Map<number,{party:number[];state:number[]}>();for(const row of allRows){const person=profiles.get(String(row.external_id));if(!person)continue;const item=monthlyGroups.get(Number(row.month))??{party:[],state:[]},value=Number(row.value);if((partyAtDate(person,cutoff)??person.party)===party)item.party.push(value);if(person.uf===profile.uf)item.state.push(value);monthlyGroups.set(Number(row.month),item)}
  const months=Array.from({length:12},(_,index)=>{const month=index+1,covered=observedMonths.has(month),groups=monthlyGroups.get(month);return{month,valueCents:covered?(personalByMonth.get(month)??0):null,partyMeanCents:covered&&groups?mean(groups.party):null,stateMeanCents:covered&&groups?mean(groups.state):null}});
  const totals=new Map<string,number>();for(const row of allRows)totals.set(String(row.external_id),(totals.get(String(row.external_id))??0)+Number(row.value));const universe=[...totals].map(([id,valueCents])=>({id,valueCents,profile:profiles.get(id)})).filter(item=>item.profile).sort((a,b)=>b.valueCents-a.valueCents||a.id.localeCompare(b.id));const own=universe.find(item=>item.id===externalId),rank=own?universe.indexOf(own)+1:null,houseValues=universe.map(item=>item.valueCents),partyValues=universe.filter(item=>(partyAtDate(item.profile!,cutoff)??item.profile!.party)===party).map(item=>item.valueCents),stateValues=universe.filter(item=>item.profile!.uf===profile.uf).map(item=>item.valueCents),stats=(values:number[])=>({meanCents:mean(values),distribution:distribution(values),sampleSize:values.length});const house=stats(houseValues),benchmarks={party:{label:party,...stats(partyValues)},state:{label:profile.uf,...stats(stateValues)},house:{label:source==='senado'?'Senado':'Câmara',...house},rank,universe:universe.length,percentile:rank!==null&&universe.length>1?100*(universe.length-rank)/(universe.length-1):rank===1?100:null,medianDifference:house.distribution.median&&own?(own.valueCents-house.distribution.median)/house.distribution.median:null};
  const coveredValues=months.flatMap(month=>month.valueCents===null?[]:[month.valueCents]),average=mean(coveredValues),peak=months.filter(month=>month.valueCents!==null).sort((a,b)=>b.valueCents!-a.valueCents!)[0]??null,highlights:string[]=[];if(categories[0]?.share!==null&&categories[0]!.share>=.25)highlights.push(`${(categories[0]!.share!*100).toLocaleString('pt-BR',{maximumFractionDigits:1})}% dos gastos identificados estão em ${categories[0]!.label}.`);if(topSupplier&&topSupplier.share!==null&&topSupplier.share>=.15)highlights.push(`${topSupplier.label} representa ${(topSupplier.share!*100).toLocaleString('pt-BR',{maximumFractionDigits:1})}% do total identificado.`);if(peak&&average&&peak.valueCents!>=average*1.5)highlights.push(`O mês ${peak.month} teve gasto ${(peak.valueCents!/average).toLocaleString('pt-BR',{maximumFractionDigits:1})}× acima da média mensal do parlamentar.`);if(rank!==null)highlights.push(`Posição ${rank} de ${universe.length} na Casa, no mesmo período observado.`);
  const coverage:DataCoverage={availability:rows.length?'available':'partial',source,period:{from:lastMonth?`${year}-01-01`:null,to:lastMonth?`${year}-${String(lastMonth).padStart(2,'0')}-28`:null,grain:'month'},batchId:String(batch.id),note:'Cota líquida identificada no lote ativo; estornos são preservados e não representa o custo total do mandato.',sampleSize:rows.length};return{source,year,profile,party,totalCents,categories,months,suppliers,topSupplier,benchmarks,highlights,coverage,origin:{batchId:String(batch.id),publishedAt:String(batch.published_at)}};
}
