import type {DatabaseSync,SQLInputValue} from 'node:sqlite';

export type FinancialPhase='commitment'|'liquidation'|'payment';
export interface FinancialFact{sourceSystem:string;phase:FinancialPhase;amountSignedScaled:number;movementKind:string;movementYear:number;restosAPagar:boolean}
export interface FinancialReconciliation{sourceByPhase:Partial<Record<FinancialPhase,string>>;totals:Record<FinancialPhase,number|null>;issues:{kind:string;expected:number|null;observed:number|null}[];publishablePaid:number|null}
const priorities:Record<'CAMARA'|'SENADO',string[]>={CAMARA:['camara_financeiro'],SENADO:['senado_siafi']};

/** Não soma fontes paralelas. Estornos e anulações entram com o sinal persistido. */
export function reconcileFinancialSeries(institution:'CAMARA'|'SENADO',facts:FinancialFact[],committedFallback:number|null=null):FinancialReconciliation{const sourceByPhase:Partial<Record<FinancialPhase,string>>={},totals:Record<FinancialPhase,number|null>={commitment:committedFallback,liquidation:null,payment:null};for(const phase of ['commitment','liquidation','payment'] as const){const candidates=[...new Set(facts.filter(fact=>fact.phase===phase).map(fact=>fact.sourceSystem))],source=priorities[institution].find(item=>candidates.includes(item))??null;if(!source)continue;sourceByPhase[phase]=source;totals[phase]=facts.filter(fact=>fact.phase===phase&&fact.sourceSystem===source).reduce((sum,fact)=>sum+fact.amountSignedScaled,0)}const issues:FinancialReconciliation['issues']=[];if(totals.commitment!==null&&totals.liquidation!==null&&totals.liquidation>totals.commitment)issues.push({kind:'liquidated_above_committed',expected:totals.commitment,observed:totals.liquidation});if(totals.liquidation!==null&&totals.payment!==null&&totals.payment>totals.liquidation)issues.push({kind:'paid_above_liquidated',expected:totals.liquidation,observed:totals.payment});return{sourceByPhase,totals,issues,publishablePaid:issues.some(issue=>issue.kind==='paid_above_liquidated')?null:totals.payment}}

export function institutionalFinancialReconciliation(db:DatabaseSync,contractId?:string){const commitments=db.prepare(`SELECT c.id,c.institution,c.committed_value_scaled FROM commitments c ${contractId?'WHERE c.contract_id=?':''} ORDER BY c.id`).all(...(contractId?[contractId]:[]));return commitments.map(commitment=>{const facts=db.prepare('SELECT source_system,phase,amount_signed_scaled,movement_kind,movement_year,restos_a_pagar FROM financial_movements WHERE commitment_id=?').all(String(commitment.id)).map(row=>({sourceSystem:String(row.source_system),phase:String(row.phase) as FinancialPhase,amountSignedScaled:Number(row.amount_signed_scaled),movementKind:String(row.movement_kind),movementYear:Number(row.movement_year),restosAPagar:Boolean(row.restos_a_pagar)})),result=reconcileFinancialSeries(String(commitment.institution) as 'CAMARA'|'SENADO',facts,commitment.committed_value_scaled==null?null:Number(commitment.committed_value_scaled));return{commitmentId:String(commitment.id),institution:String(commitment.institution),...result}})}

/** Escada semântica: cada grandeza permanece independente e nunca compõe um “total gasto”. */
export function institutionalContractFinancialSummary(db:DatabaseSync,contractId:string){const contract=db.prepare('SELECT * FROM institutional_contracts WHERE id=?').get(contractId);if(!contract)return null;const one=(sql:string,...params:SQLInputValue[])=>{const value=db.prepare(sql).get(...params)?.value;return value==null?null:Number(value)},execution=institutionalFinancialReconciliation(db,contractId),sum=(phase:FinancialPhase)=>{const values=execution.map(item=>item.totals[phase]).filter((value):value is number=>value!==null);return values.length?values.reduce((a,b)=>a+b,0):null},paid=execution.every(item=>item.publishablePaid!==null)?execution.reduce((total,item)=>total+item.publishablePaid!,0):null;return{contractId,institution:String(contract.institution),currency:String(contract.currency),scale:Number(contract.value_scale),estimated:contract.tender_id?one('SELECT sum(estimated_total_value_scaled) value FROM tender_items WHERE tender_id=?',contract.tender_id):null,proposed:null,awarded:contract.tender_id?one('SELECT sum(a.awarded_value_scaled) value FROM item_awards a JOIN tender_items i ON i.id=a.tender_item_id WHERE i.tender_id=?',contract.tender_id):null,contractOriginal:contract.original_value_scaled==null?null:Number(contract.original_value_scaled),contractCurrent:contract.current_published_value_scaled==null?null:Number(contract.current_published_value_scaled),currentValueSemantics:contract.current_value_semantics==null?null:String(contract.current_value_semantics),billed:one('SELECT sum(billed_value_scaled) value FROM contract_billings WHERE contract_id=?',contractId),committed:sum('commitment'),liquidated:sum('liquidation'),paid,issues:execution.flatMap(item=>item.issues.map(issue=>({...issue,commitmentId:item.commitmentId}))),commitments:execution.length}}
