import type {DatabaseSync} from 'node:sqlite';
import {type Profile,type Source} from '@senadotracker/domain';
import {publishedParliamentarySubsidy} from './public-info.ts';
import {reportingCutoff} from './reporting-period.ts';

export type DashboardSort='name'|'name_desc'|'participation_desc'|'participation_asc'|'proposals_desc'|'proposals_asc'|'cost_desc'|'cost_asc'|'staff_desc'|'staff_asc';
export interface DashboardQuery{source?:Source|undefined;role?:string|undefined;uf?:string|undefined;party?:string|undefined;search?:string|undefined;year?:number|undefined;sort?:DashboardSort|undefined;page?:number|undefined;pageSize?:number|undefined}
export interface DashboardRow{source:Source;externalId:string;name:string;photoUrl:string|null;role:string;uf:string;party:string;situation:string;presence:number|null;participation:number|null;proposals:number|null;rapporteurships:number|null;totalCostCents:number|null;monthlyCostCents:number|null;costMonths:number|null;costPeriod:string|null;staff:number|null;assetsCents:number|null;assetYear:number|null;mandates:number|null}
const key=(source:Source,id:string)=>`${source}:${id}`;
const normal=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR');
type VoteMetric={presence:number|null;nominal:number|null};
const metricCache=new WeakMap<DatabaseSync,Map<string,{expires:number;value:Map<string,VoteMetric>}>>();
function participationForHouse(db:DatabaseSync,source:Source,year:number,people:Array<{id:string;profile:Profile}>){
  const batch=db.prepare('SELECT batch_id FROM active_legislative_publications WHERE source=? AND year=?').get(source,year),roster=db.prepare('SELECT batch_id FROM active_publications WHERE source=?').get(source),cacheKey=`${source}:${year}:${batch?.batch_id??''}:${roster?.batch_id??''}`,cache=metricCache.get(db)??new Map(),hit=cache.get(cacheKey);if(hit&&hit.expires>Date.now())return hit.value;
  const result=new Map<string,VoteMetric>(),cutoff=reportingCutoff(year),presence=new Map(source==='camara'?db.prepare('SELECT external_id,days_present,days_total FROM chamber_official_presence WHERE year=?').all(year).map(row=>[String(row.external_id),{present:Number(row.days_present),total:Number(row.days_total)}]):[]);
  const deliberations=batch?db.prepare(`SELECT d.external_id,d.date FROM nominal_deliberations n JOIN deliberations d ON d.batch_id=n.batch_id AND d.external_id=n.deliberation_id WHERE n.batch_id=? AND json_extract(d.payload,'$.chamberBody')='PLEN' AND substr(d.date,1,10)<=?`).all(String(batch.batch_id),cutoff):[];
  const accepted=source==='camara'?"'sim','nao','abstencao','votou','secreto','obstrucao'":"'sim','nao','abstencao','votou','secreto'";
  const votes=new Map<string,Set<string>>();if(batch)for(const row of db.prepare(`SELECT v.external_id,v.deliberation_id FROM legislative_votes v JOIN nominal_deliberations n ON n.batch_id=v.batch_id AND n.deliberation_id=v.deliberation_id JOIN deliberations d ON d.batch_id=v.batch_id AND d.external_id=v.deliberation_id WHERE v.batch_id=? AND json_extract(d.payload,'$.chamberBody')='PLEN' AND substr(d.date,1,10)<=? AND search_text(json_extract(v.payload,'$.vote')) IN (${accepted})`).all(String(batch.batch_id),cutoff)){const id=String(row.external_id),set=votes.get(id)??new Set<string>();set.add(String(row.deliberation_id));votes.set(id,set)}
  for(const {id,profile} of people){const official=presence.get(id),voted=votes.get(id),eligible=deliberations.filter(row=>(profile.exercises??[]).some(exercise=>String(row.date)>=exercise.start.slice(0,10)&&(!exercise.end||String(row.date)<=exercise.end.slice(0,10))));const numerator=eligible.filter(row=>voted?.has(String(row.external_id))).length;result.set(id,{presence:official&&official.total?official.present/official.total:null,nominal:eligible.length&&numerator>0&&(source==='senado'||official)?numerator/eligible.length:null})}
  cache.set(cacheKey,{expires:Date.now()+60_000,value:result});metricCache.set(db,cache);return result;
}

export function publishedRankingsDashboard(db:DatabaseSync,query:DashboardQuery={}){
  const sources:Source[]=query.source?[query.source]:['senado','camara'];
  const latest=Number(db.prepare('SELECT max(year) year FROM active_expense_publications').get()?.year??new Date().getFullYear());
  const year=query.year&&Number.isInteger(query.year)&&query.year>=2000&&query.year<=new Date().getFullYear()?query.year:latest;
  const page=Math.max(1,Math.floor(query.page??1)),pageSize=Math.min(100,Math.max(1,Math.floor(query.pageSize??10)));
  const profiles=sources.flatMap(source=>db.prepare(`SELECT p.external_id,p.name,p.uf,p.party,p.payload,p.person_id FROM profiles p JOIN active_publications a ON a.batch_id=p.batch_id WHERE a.source=?`).all(source).map(row=>({source,id:String(row.external_id),personId:String(row.person_id),profile:JSON.parse(String(row.payload)) as Profile})));
  const facets={ufs:[...new Set(profiles.map(item=>item.profile.uf))].sort(),parties:[...new Set(profiles.map(item=>item.profile.party))].sort()};
  const candidate=profiles.filter(({source,profile})=>(!query.uf||profile.uf===query.uf)&&(!query.party||profile.party===query.party)&&(!query.role||query.role===source)&&(!query.search||normal(`${profile.name} ${profile.party} ${profile.uf}`).includes(normal(query.search))));
  const dates:string[]=[];
  const electoralFreshness=db.prepare(`SELECT min(b.published_at) published_at FROM active_electoral_publications a JOIN electoral_batches b ON b.id=a.batch_id`).get();if(electoralFreshness?.published_at)dates.push(String(electoralFreshness.published_at));
  const expense=new Map<string,Map<number,number>>(),cabinet=new Map<string,Map<number,number>>(),staff=new Map<string,number>(),proposals=new Map<string,number>(),rapporteurs=new Map<string,number>(),assets=new Map<string,{year:number;value:number}>();
  const participation=new Map<string,{presence:number|null;nominal:number|null}>();
  const salaryByMonth=new Map<number,number>();for(let month=1;month<=12;month++){const at=`${year}-${String(month).padStart(2,'0')}-01`,salary=publishedParliamentarySubsidy(db,at);if(salary)salaryByMonth.set(month,salary.valueCents)}
  for(const source of sources){
    const roster=db.prepare(`SELECT b.published_at FROM active_publications a JOIN publication_batches b ON b.id=a.batch_id WHERE a.source=?`).get(source);if(roster)dates.push(String(roster.published_at));
    const housePeople=profiles.filter(item=>item.source===source),ids=housePeople.map(item=>item.id);
    for(const [id,metric] of participationForHouse(db,source,year,housePeople))participation.set(key(source,id),metric);
    const expenseBatch=db.prepare(`SELECT a.batch_id,b.published_at FROM active_expense_publications a JOIN expense_batches b ON b.id=a.batch_id WHERE a.source=? AND a.year=?`).get(source,year);
    if(expenseBatch){dates.push(String(expenseBatch.published_at));for(const row of db.prepare(`SELECT external_id,month,sum(net_cents-refund_cents) value FROM expenses WHERE batch_id=? GROUP BY external_id,month`).all(String(expenseBatch.batch_id))){const k=key(source,String(row.external_id)),months=expense.get(k)??new Map<number,number>();months.set(Number(row.month),Number(row.value));expense.set(k,months)}}
    const staffBatch=db.prepare(`SELECT a.batch_id,b.observed_at FROM active_staff_snapshot_publications a JOIN staff_snapshot_batches b ON b.id=a.batch_id WHERE a.source=? AND b.availability<>'unavailable'`).get(source);
    if(staffBatch){dates.push(String(staffBatch.observed_at));for(const row of db.prepare(`SELECT external_id,count(*) value FROM functional_staff_assignments WHERE batch_id=? AND source=? AND match_status='confirmed' GROUP BY external_id`).all(String(staffBatch.batch_id),source))staff.set(key(source,String(row.external_id)),Number(row.value));for(const id of ids)if(!staff.has(key(source,id)))staff.set(key(source,id),0)}
    if(source==='senado'){
      const batch=db.prepare(`SELECT a.batch_id,b.published_at FROM active_expanded_cost_publications a JOIN expanded_cost_batches b ON b.id=a.batch_id WHERE a.source=? AND a.year=?`).get(source,year);
      if(batch){dates.push(String(batch.published_at));for(const row of db.prepare(`SELECT external_id,competence,sum(value_cents) value FROM expanded_costs WHERE batch_id=? AND rubric='cabinet_payroll_gross' AND value_cents IS NOT NULL GROUP BY external_id,competence`).all(String(batch.batch_id))){const month=Number(String(row.competence).slice(5,7));if(month>=1&&month<=12){const k=key(source,String(row.external_id)),months=cabinet.get(k)??new Map<number,number>();months.set(month,Number(row.value));cabinet.set(k,months)}}}
    }else{
      const batch=db.prepare(`SELECT a.batch_id,b.published_at FROM active_cabinet_budget_publications a JOIN cabinet_budget_batches b ON b.id=a.batch_id WHERE a.source=? AND a.year=?`).get(source,year);
      if(batch){dates.push(String(batch.published_at));for(const row of db.prepare(`SELECT external_id,month,sum(spent_cents) value FROM cabinet_monthly_budgets WHERE batch_id=? AND spent_cents IS NOT NULL GROUP BY external_id,month`).all(String(batch.batch_id))){const k=key(source,String(row.external_id)),months=cabinet.get(k)??new Map<number,number>();months.set(Number(row.month),Number(row.value));cabinet.set(k,months)}}
    }
    const batches=db.prepare(`SELECT a.batch_id,a.scope,b.published_at FROM active_activity_publications a JOIN activity_batches b ON b.id=a.batch_id WHERE a.source=?`).all(source),batchIds=batches.map(row=>String(row.batch_id)),partial=batches.some(row=>String(row.scope).startsWith('amostra-'));for(const row of batches)dates.push(String(row.published_at));
    if(batchIds.length){const marks=batchIds.map(()=>'?').join(',');for(const row of db.prepare(`SELECT person_external_id id,count(DISTINCT proposal_id) value FROM proposal_authors WHERE batch_id IN (${marks}) AND person_external_id IS NOT NULL GROUP BY person_external_id`).all(...batchIds))proposals.set(key(source,String(row.id)),Number(row.value));for(const row of db.prepare(`SELECT person_external_id id,count(*) value FROM legislative_appointments WHERE batch_id IN (${marks}) AND kind='rapporteurship' GROUP BY person_external_id`).all(...batchIds))rapporteurs.set(key(source,String(row.id)),Number(row.value));if(!partial)for(const id of ids){proposals.set(key(source,id),proposals.get(key(source,id))??0);rapporteurs.set(key(source,id),rapporteurs.get(key(source,id))??0)}}
  }
  // Aggregate once; conflicting asset versions are excluded rather than summed.
  const candidateIds=new Set(candidate.map(item=>item.personId));
  for(const row of db.prepare(`SELECT c.person_id,c.year,sum(a.value_cents) value,count(*) entries,count(DISTINCT a.asset_id) assets FROM candidacies c JOIN active_electoral_publications p ON p.batch_id=c.batch_id JOIN electoral_batches b ON b.id=c.batch_id JOIN electoral_assets a ON a.batch_id=c.batch_id AND a.sequence_id=c.sequence_id WHERE c.match_status='confirmed' AND b.availability<>'unavailable' GROUP BY c.person_id,c.year,c.sequence_id,c.batch_id ORDER BY c.year DESC`).all()){
    const personId=String(row.person_id);if(candidateIds.has(personId)&&!assets.has(personId)&&Number(row.entries)===Number(row.assets))assets.set(personId,{year:Number(row.year),value:Number(row.value)});
  }
  const rows:DashboardRow[]=candidate.map(({source,id,personId,profile})=>{const itemKey=key(source,id),e=expense.get(itemKey),c=cabinet.get(itemKey),months=e&&c?[...e.keys()].filter(month=>{const start=`${year}-${String(month).padStart(2,'0')}-01`,end=`${year}-${String(month).padStart(2,'0')}-31`;return c.has(month)&&salaryByMonth.has(month)&&start<=new Date().toISOString().slice(0,10)&&profile.exercises.some(exercise=>exercise.start.slice(0,10)<=end&&(!exercise.end||exercise.end.slice(0,10)>=start))}).sort((a,b)=>a-b):[],total=months.length?months.reduce((sum,month)=>sum+e!.get(month)!+c!.get(month)!+salaryByMonth.get(month)!,0):null,asset=assets.get(personId);return{source,externalId:id,name:profile.name,photoUrl:profile.photoUrl,role:source==='senado'?'Senador(a)':'Deputado(a) federal',uf:profile.uf,party:profile.party,situation:profile.exercises.some(item=>!item.end||item.end>=new Date().toISOString().slice(0,10))?'Em exercício':'Cadastro atual',presence:participation.get(itemKey)?.presence??null,participation:participation.get(itemKey)?.nominal??null,proposals:proposals.get(itemKey)??null,rapporteurships:rapporteurs.get(itemKey)??null,totalCostCents:total,monthlyCostCents:total!==null?total/months.length:null,costMonths:months.length||null,costPeriod:months.length?`${year}-${String(months[0]).padStart(2,'0')} a ${year}-${String(months.at(-1)).padStart(2,'0')}`:null,staff:staff.get(itemKey)??null,assetsCents:asset?.value??null,assetYear:asset?.year??null,mandates:profile.historyAvailability==='available'?profile.mandates.length:null}});
  const sort=query.sort??'name',descending=sort.endsWith('_desc'),field=sort.replace(/_(asc|desc)$/,'');
  rows.sort((a,b)=>{const av=field==='participation'?a.participation:field==='proposals'?a.proposals:field==='cost'?a.totalCostCents:field==='staff'?a.staff:a.name,bv=field==='participation'?b.participation:field==='proposals'?b.proposals:field==='cost'?b.totalCostCents:field==='staff'?b.staff:b.name;if(av===null&&bv!==null)return 1;if(bv===null&&av!==null)return -1;const compared=typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv),'pt-BR');return (descending?-compared:compared)||a.name.localeCompare(b.name,'pt-BR')||a.externalId.localeCompare(b.externalId)});
  const take=(field:keyof DashboardRow,direction:'asc'|'desc')=>[...rows].filter(row=>typeof row[field]==='number').sort((a,b)=>((Number(a[field])-Number(b[field]))*(direction==='asc'?1:-1))||a.name.localeCompare(b.name,'pt-BR'))[0]??null;
  const assetYear=Math.max(0,...rows.map(row=>row.assetYear??0)),assetComparable=rows.filter(row=>row.assetYear===assetYear);
  const highlights={presence:take('presence','asc'),activity:[...rows].filter(row=>row.proposals!==null&&row.rapporteurships!==null).sort((a,b)=>(b.proposals!+b.rapporteurships!)-(a.proposals!+a.rapporteurships!)||a.name.localeCompare(b.name,'pt-BR'))[0]??null,cost:take('monthlyCostCents','desc'),staff:take('staff','desc'),assets:[...assetComparable].sort((a,b)=>(b.assetsCents??0)-(a.assetsCents??0)||a.name.localeCompare(b.name,'pt-BR'))[0]??null};
  return{year,updatedAt:dates.length?dates.sort()[0]:null,facets,total:rows.length,page,pageSize,items:rows.slice((page-1)*pageSize,page*pageSize),highlights,allItems:rows,coverage:{presence:rows.filter(row=>row.presence!==null).length,participation:rows.filter(row=>row.participation!==null).length,activity:rows.filter(row=>row.proposals!==null&&row.rapporteurships!==null).length,cost:rows.filter(row=>row.totalCostCents!==null).length,staff:rows.filter(row=>row.staff!==null).length,assets:assetComparable.length}};
}
