import {createHash} from 'node:crypto';
import type {DatabaseSync} from 'node:sqlite';
import {canStrongMatchSupplierIdentifier,normalizeSupplierIdentifier,searchText,type Source} from '@senadotracker/domain';
import {transaction} from './index.ts';

const stableId=(prefix:string,...parts:string[])=>`${prefix}_${createHash('sha256').update(parts.join('\u001f')).digest('hex').slice(0,32)}`;
const iso=(value:unknown,year:number,month:number)=>{const text=String(value??'').slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(text)?text:`${year}-${String(month).padStart(2,'0')}-01`};
export interface SupplierIdentityBackfillOptions {source?:Source;year?:number;dryRun?:boolean;now?:string}
export interface SupplierIdentityBackfillResult {rows:number;strongRows:number;unresolvedRows:number;suppliers:number;identifiers:number;names:number;roles:number;links:number;invalid:number;masked:number;sentinel:number;cpf:number;cnpj:number;conflicts:number;published:boolean}
type ExpenseSupplierRow={batch_id:string;record_key:string;source:string;year:number;month:number;issued_at:string|null;supplier:string|null;supplier_document:string|null};
export interface ResolveSupplierInput{document:string|null|undefined;name:string|null|undefined;source:string;sourceRecordId:string;institution:'CAMARA'|'SENADO';role:'INSTITUTIONAL_TENDER'|'INSTITUTIONAL_CONTRACT'|'INSTITUTIONAL_PAYMENT';observedAt:string}
export function queueSupplierIdentityReview(db:DatabaseSync,input:{source:string;sourceRecordId:string;document:string|null|undefined;name?:string|null;reason?:string;observedAt:string}){const identity=normalizeSupplierIdentifier(input.document??''),status=identity.validationStatus==='valid'?'conflict':identity.validationStatus,id=stableId('supplier_review',input.source,input.sourceRecordId,status);db.prepare(`INSERT INTO supplier_identity_review_queue(id,source,source_record_id,raw_identifier,normalized_identifier,validation_status,reason,status,evidence_json,created_at,resolved_at) VALUES (?,?,?,?,?,?,?,'pending',?,?,NULL) ON CONFLICT(source,source_record_id,validation_status) DO UPDATE SET raw_identifier=excluded.raw_identifier,normalized_identifier=excluded.normalized_identifier,reason=excluded.reason,evidence_json=excluded.evidence_json`).run(id,input.source,input.sourceRecordId,input.document??null,identity.normalizedValue||null,status,input.reason??`Identificador ${status}; revisão manual necessária`,JSON.stringify({name:input.name??null,normalizationVersion:identity.normalizationVersion,type:identity.type}),input.observedAt);return id}
export function resolveStrongSupplier(db:DatabaseSync,input:ResolveSupplierInput):{supplierId:string;created:boolean}|null{if(!input.document)return null;const identity=normalizeSupplierIdentifier(input.document);if(!canStrongMatchSupplierIdentifier(identity)){queueSupplierIdentityReview(db,{source:input.source,sourceRecordId:input.sourceRecordId,document:input.document,name:input.name??null,observedAt:input.observedAt});return null}const key=`${identity.type}:${identity.countryCode??''}:${identity.normalizedValue}`,id=stableId('sup',key),identifierId=stableId('sid',key),existing=db.prepare(`SELECT supplier_id FROM supplier_identifiers WHERE identifier_type=? AND normalized_value=? AND country_code=? AND validation_status='valid'`).get(identity.type,identity.normalizedValue,identity.countryCode);if(existing&&String(existing.supplier_id)!==id){queueSupplierIdentityReview(db,{source:input.source,sourceRecordId:input.sourceRecordId,document:input.document,name:input.name??null,reason:'Identificador forte já associado a outra entidade',observedAt:input.observedAt});return null}const created=!db.prepare('SELECT 1 FROM suppliers WHERE id=?').get(id),name=String(input.name??'').trim()||null;db.prepare(`INSERT INTO suppliers VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET canonical_name=coalesce(suppliers.canonical_name,excluded.canonical_name),updated_at=excluded.updated_at`).run(id,name,identity.type==='cpf'?'individual':'company','confirmed',input.observedAt,input.observedAt);db.prepare(`INSERT INTO supplier_identifiers VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING`).run(identifierId,id,identity.type,identity.rawValue,identity.normalizedValue,identity.countryCode,0,'valid',identity.normalizationVersion,null,null,input.source,input.sourceRecordId,input.observedAt);db.prepare(`INSERT INTO supplier_identifier_observations VALUES (?,?,?,?,?,?) ON CONFLICT(supplier_identifier_id,source,source_record_id) DO UPDATE SET last_seen_at=excluded.last_seen_at`).run(identifierId,identity.rawValue,input.source,input.sourceRecordId,input.observedAt,input.observedAt);if(name){const search=searchText(name),nameId=stableId('sname',id,search);db.prepare(`INSERT INTO supplier_names VALUES (?,?,?,?,?,NULL,NULL,?,?,?,?) ON CONFLICT(id) DO UPDATE SET last_seen_at=excluded.last_seen_at`).run(nameId,id,name,search,created?1:0,input.source,input.sourceRecordId,input.observedAt,input.observedAt)}db.prepare(`INSERT INTO supplier_roles VALUES (?,?,?,?,?,?,?) ON CONFLICT(supplier_id,role,institution,source,source_record_id) DO UPDATE SET last_seen_at=excluded.last_seen_at`).run(id,input.role,input.institution,input.observedAt,input.observedAt,input.source,input.sourceRecordId);return{supplierId:id,created}}

/** Liga somente identificadores fortes; texto/nome nunca confirma identidade. */
export function backfillExpenseSupplierIdentities(db:DatabaseSync,runId:string|null,options:SupplierIdentityBackfillOptions={}):SupplierIdentityBackfillResult {
  const where:string[]=[];const values:(string|number)[]=[];if(options.source){where.push('e.source=?');values.push(options.source)}if(options.year){where.push('e.year=?');values.push(options.year)}
  const rows=db.prepare(`SELECT e.batch_id,e.record_key,e.source,e.year,e.month,e.issued_at,e.supplier,e.supplier_document FROM expenses e JOIN active_expense_publications a ON a.batch_id=e.batch_id${where.length?` WHERE ${where.join(' AND ')}`:''} ORDER BY e.batch_id,e.record_key`).all(...values) as unknown as ExpenseSupplierRow[];
  const groups=new Map<string,{identity:ReturnType<typeof normalizeSupplierIdentifier>;rows:typeof rows;names:Map<string,{name:string;count:number;first:string;last:string;sources:Set<string>}>}>();let invalid=0,masked=0,sentinel=0,cpf=0,cnpj=0,unresolvedRows=0;
  for(const row of rows){const raw=String(row.supplier_document??'');if(!raw.trim()){unresolvedRows++;continue}const identity=normalizeSupplierIdentifier(raw);if(identity.type==='cpf')cpf++;if(identity.type==='cnpj')cnpj++;if(identity.validationStatus==='invalid')invalid++;if(identity.validationStatus==='masked')masked++;if(identity.validationStatus==='sentinel')sentinel++;if(!canStrongMatchSupplierIdentifier(identity)){unresolvedRows++;continue}const key=`${identity.type}:${identity.countryCode??''}:${identity.normalizedValue}`,group=groups.get(key)??{identity,rows:[] as ExpenseSupplierRow[],names:new Map<string,{name:string;count:number;first:string;last:string;sources:Set<string>}>()};group.rows.push(row);const name=String(row.supplier??'').trim();if(name){const nameKey=searchText(name),date=iso(row.issued_at,Number(row.year),Number(row.month)),entry=group.names.get(nameKey)??{name,count:0,first:date,last:date,sources:new Set<string>()};entry.count++;if(date<entry.first)entry.first=date;if(date>entry.last)entry.last=date;entry.sources.add(String(row.source));group.names.set(nameKey,entry)}groups.set(key,group)}
  const result:SupplierIdentityBackfillResult={rows:rows.length,strongRows:rows.length-unresolvedRows,unresolvedRows,suppliers:groups.size,identifiers:groups.size,names:[...groups.values()].reduce((n,g)=>n+g.names.size,0),roles:0,links:rows.length-unresolvedRows,invalid,masked,sentinel,cpf,cnpj,conflicts:0,published:false};if(options.dryRun)return result;if(!runId)throw new Error('Backfill persistente exige runId');const run=db.prepare('SELECT source,status FROM ingestion_runs WHERE id=?').get(runId);if(!run||run.source!=='civica'||run.status!=='running')throw new Error('Backfill de fornecedor exige execução Cívica ativa');
  transaction(db,()=>{const now=options.now??new Date().toISOString();for(const row of rows){if(!String(row.supplier_document??'').trim())continue;const identity=normalizeSupplierIdentifier(String(row.supplier_document));if(!canStrongMatchSupplierIdentifier(identity))queueSupplierIdentityReview(db,{source:`expense:${row.source}`,sourceRecordId:`${row.batch_id}:${row.record_key}`,document:row.supplier_document,name:row.supplier,observedAt:now})}for(const [identityKey,group] of groups){const supplierId=stableId('sup',identityKey),identifierId=stableId('sid',identityKey),canonical=[...group.names.values()].sort((a,b)=>b.count-a.count||b.last.localeCompare(a.last)||a.name.localeCompare(b.name,'pt-BR'))[0]?.name??null;const existing=db.prepare(`SELECT supplier_id FROM supplier_identifiers WHERE identifier_type=? AND normalized_value=? AND country_code=? AND validation_status='valid'`).get(group.identity.type,group.identity.normalizedValue,group.identity.countryCode);if(existing&&String(existing.supplier_id)!==supplierId){result.conflicts++;queueSupplierIdentityReview(db,{source:String(group.rows[0]!.source),sourceRecordId:`${group.rows[0]!.batch_id}:${group.rows[0]!.record_key}`,document:group.identity.rawValue,name:canonical,reason:'Identificador forte associado a outra entidade',observedAt:now});continue}db.prepare(`INSERT INTO suppliers(id,canonical_name,entity_kind,identity_status,created_at,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET canonical_name=excluded.canonical_name,updated_at=excluded.updated_at`).run(supplierId,canonical,group.identity.type==='cpf'?'individual':'company','confirmed',now,now);const firstRow=group.rows[0]!,firstRecord=`${firstRow.batch_id}:${firstRow.record_key}`;db.prepare(`INSERT INTO supplier_identifiers(id,supplier_id,identifier_type,raw_value,normalized_value,country_code,is_masked,validation_status,normalization_version,valid_from,valid_to,source,source_record_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING`).run(identifierId,supplierId,group.identity.type,group.identity.rawValue,group.identity.normalizedValue,group.identity.countryCode,0,'valid',group.identity.normalizationVersion,null,null,String(firstRow.source),firstRecord,now);
      const rawForms=new Map<string,{source:string;raw:string;first:string;last:string}>();for(const row of group.rows){const raw=String(row.supplier_document),source=String(row.source),key=`${source}\u001f${raw}`,date=iso(row.issued_at,Number(row.year),Number(row.month)),seen=rawForms.get(key)??{source,raw,first:date,last:date};if(date<seen.first)seen.first=date;if(date>seen.last)seen.last=date;rawForms.set(key,seen)}for(const seen of rawForms.values())db.prepare(`INSERT INTO supplier_identifier_observations VALUES (?,?,?,?,?,?) ON CONFLICT(supplier_identifier_id,source,source_record_id) DO UPDATE SET last_seen_at=excluded.last_seen_at`).run(identifierId,seen.raw,seen.source,`expense-document:${seen.source}:${seen.raw}`,seen.first,seen.last);
      db.prepare('UPDATE supplier_names SET is_canonical=0 WHERE supplier_id=?').run(supplierId);for(const [nameKey,name] of group.names){const nameId=stableId('sname',supplierId,nameKey),source=[...name.sources].sort().join('+'),record=`expense-name:${source}:${nameKey}`;db.prepare(`INSERT INTO supplier_names(id,supplier_id,name,search_name,is_canonical,valid_from,valid_to,source,source_record_id,first_seen_at,last_seen_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET last_seen_at=excluded.last_seen_at,is_canonical=excluded.is_canonical,source=excluded.source,source_record_id=excluded.source_record_id`).run(nameId,supplierId,name.name,nameKey,name.name===canonical?1:0,null,null,source,record,name.first,name.last)}
      const byInstitution=new Map<string,{first:string;last:string}>();for(const row of group.rows){const institution=String(row.source)==='camara'?'CAMARA':'SENADO',date=iso(row.issued_at,Number(row.year),Number(row.month)),entry=byInstitution.get(institution)??{first:date,last:date};if(date<entry.first)entry.first=date;if(date>entry.last)entry.last=date;byInstitution.set(institution,entry)}for(const [institution,period] of byInstitution){db.prepare(`INSERT INTO supplier_roles VALUES (?,?,?,?,?,?,?) ON CONFLICT(supplier_id,role,institution,source,source_record_id) DO UPDATE SET last_seen_at=excluded.last_seen_at`).run(supplierId,'PARLIAMENTARY_EXPENSE',institution,period.first,period.last,'expenses',`active-expenses:${institution}`);result.roles++}
      for(const row of group.rows)db.prepare(`INSERT INTO expense_supplier_links VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(batch_id,record_key) DO UPDATE SET supplier_id=excluded.supplier_id,supplier_identifier_id=excluded.supplier_identifier_id,matched_at=excluded.matched_at,resolver_version=excluded.resolver_version,evidence_json=excluded.evidence_json`).run(String(row.batch_id),String(row.record_key),supplierId,identifierId,'strong_identifier','confirmed',now,group.identity.normalizationVersion,JSON.stringify({type:group.identity.type,normalizedValue:group.identity.normalizedValue,sourceField:'supplier_document'}));}
    result.published=true;const reconciliation={...result,conflicts:result.conflicts};db.prepare(`INSERT INTO supplier_identity_batches VALUES (?,?,'published',?,?,?)`).run(runId,now,'supplier-id-v1',result.strongRows,JSON.stringify(reconciliation));db.prepare(`INSERT INTO active_supplier_identity_publication VALUES (1,?) ON CONFLICT(singleton) DO UPDATE SET batch_id=excluded.batch_id`).run(runId);db.prepare("UPDATE ingestion_runs SET status='published',finished_at=?,expected_count=?,roster_complete=1,reconciliation_json=? WHERE id=?").run(now,result.strongRows,JSON.stringify(reconciliation),runId);db.prepare('DELETE FROM job_locks WHERE run_id=?').run(runId)});return result;
}

export function supplierIdentitySummary(db:DatabaseSync){const batch=db.prepare(`SELECT b.* FROM supplier_identity_batches b JOIN active_supplier_identity_publication a ON a.batch_id=b.id WHERE a.singleton=1`).get();return{batch:batch?{id:String(batch.id),publishedAt:String(batch.published_at),normalizationVersion:String(batch.normalization_version),recordCount:Number(batch.record_count),reconciliation:JSON.parse(String(batch.reconciliation_json))}:null,suppliers:Number(db.prepare('SELECT count(*) n FROM suppliers').get()?.n??0),links:Number(db.prepare('SELECT count(*) n FROM expense_supplier_links').get()?.n??0)}}
