import type { DatabaseSync } from 'node:sqlite';
import { transaction } from './index.ts';

/** Materializes and atomically publishes the category distribution for a financial revision. */
export function rebuildSupplierCategorySnapshot(db: DatabaseSync, financialRevisionId: string, options: { cutoffStart?: string|null; cutoffEnd?: string|null; enrichmentAttemptComplete?: boolean; allowPartial?: boolean; enrichmentState?: Record<string,unknown> } = {}) {
  const now=new Date().toISOString();
  const sourceBatches=db.prepare("SELECT source,batch_id FROM active_expense_publications WHERE year=2026").all() as Array<Record<string,unknown>>;
  const chamberBatch=String(sourceBatches.find(row=>row.source==='camara')?.batch_id??'');
  const senateBatch=String(sourceBatches.find(row=>row.source==='senado')?.batch_id??'');
  const rows=db.prepare(`SELECT cm.institution,coalesce(fm.expense_nature_key,fm.expense_nature_raw,fm.expense_nature,fm.expense_element,fm.expense_group) category_key,coalesce(fm.expense_nature_raw,fm.expense_nature,fm.expense_element,fm.expense_group,fm.expense_nature_key) category_label,fm.amount_signed_scaled value,fm.id movement_id,cm.supplier_id FROM financial_movements fm JOIN commitments cm ON cm.id=fm.commitment_id WHERE fm.phase='payment' AND EXISTS (SELECT 1 FROM institutional_publication_membership pm WHERE pm.revision_scope=cm.institution||':2026' AND pm.source_system=fm.source_system AND pm.source_movement_id=fm.source_movement_id AND pm.included=1)`).all() as Array<Record<string,unknown>>;
  const canonical=rows.length, total=rows.reduce((sum,row)=>sum+Number(row.value??0),0);
  const grouped=new Map<string,{institution:string;key:string;label:string;value:number;count:number;suppliers:Set<string>}>();
  for(const row of rows){const institution=String(row.institution),key=row.category_key?String(row.category_key):'__unclassified__',label=row.category_label?String(row.category_label):'Sem classificação disponível',g=grouped.get(`${institution}:${key}`)??{institution,key,label,value:0,count:0,suppliers:new Set<string>()};g.value+=Number(row.value??0);g.count++;if(row.supplier_id)g.suppliers.add(String(row.supplier_id));grouped.set(`${institution}:${key}`,g)}
  const classified=rows.filter(row=>row.category_key!==null&&row.category_key!==undefined&&String(row.category_key)!=='').reduce((sum,row)=>sum+Number(row.value??0),0), classifiedRecords=rows.filter(row=>row.category_key!==null&&row.category_key!==undefined&&String(row.category_key)!=='').length;
  const revision=db.prepare('SELECT revision_id FROM active_supplier_category_revision WHERE singleton=1').get() as {revision_id?:string}|undefined;
  transaction(db,()=>{
    if(revision?.revision_id) db.prepare("UPDATE supplier_category_revisions SET status='superseded' WHERE revision_id=? AND status='published'").run(revision.revision_id);
    db.prepare("INSERT INTO supplier_category_revisions (revision_id,status,cutoff_start,cutoff_end,chamber_institutional_revision,senate_institutional_revision,chamber_expense_publication_id,senate_expense_publication_id,created_at,enrichment_attempt_complete,canonical_records,classified_records,unclassified_records,canonical_value_scaled,classified_value_scaled,unclassified_value_scaled,category_coverage_records,category_coverage_value,enrichment_state_json) VALUES (?, 'building',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, ?,?) ON CONFLICT(revision_id) DO UPDATE SET status='building',cutoff_start=excluded.cutoff_start,cutoff_end=excluded.cutoff_end,chamber_institutional_revision=excluded.chamber_institutional_revision,senate_institutional_revision=excluded.senate_institutional_revision,chamber_expense_publication_id=excluded.chamber_expense_publication_id,senate_expense_publication_id=excluded.senate_expense_publication_id,created_at=excluded.created_at,enrichment_attempt_complete=excluded.enrichment_attempt_complete,canonical_records=excluded.canonical_records,classified_records=excluded.classified_records,unclassified_records=excluded.unclassified_records,canonical_value_scaled=excluded.canonical_value_scaled,classified_value_scaled=excluded.classified_value_scaled,unclassified_value_scaled=excluded.unclassified_value_scaled,category_coverage_records=excluded.category_coverage_records,category_coverage_value=excluded.category_coverage_value,enrichment_state_json=excluded.enrichment_state_json").run(financialRevisionId,options.cutoffStart??null,options.cutoffEnd??null,'CAMARA:2026','SENADO:2026',chamberBatch,senateBatch,now,options.enrichmentAttemptComplete?1:0,canonical,classifiedRecords,canonical-classifiedRecords,total,classified,total-classified,canonical?classifiedRecords/canonical:0,total?classified/total:0,JSON.stringify(options.enrichmentState??{}));
    db.prepare('DELETE FROM supplier_category_snapshot WHERE revision_id=?').run(financialRevisionId);
    const insert=db.prepare('INSERT INTO supplier_category_snapshot VALUES (?,?,?,?,?,?,?,?,?,?,?)');
    for(const g of grouped.values()) insert.run(financialRevisionId,'institucional',g.institution,g.key,g.label,'official','expense_nature',g.value,g.count,g.suppliers.size,total?g.value/total:0);
    db.prepare("UPDATE supplier_category_revisions SET status='reconciled' WHERE revision_id=? AND (enrichment_attempt_complete=1 OR ?=1) AND canonical_value_scaled=classified_value_scaled+unclassified_value_scaled AND canonical_records=classified_records+unclassified_records").run(financialRevisionId,options.allowPartial?1:0);
    const state=db.prepare('SELECT status FROM supplier_category_revisions WHERE revision_id=?').get(financialRevisionId) as {status:string};
    if(state.status!=='reconciled') throw new Error('Category snapshot failed reconciliation');
    db.prepare("UPDATE supplier_category_revisions SET status='published',published_at=? WHERE revision_id=?").run(now,financialRevisionId);
    db.prepare('INSERT INTO active_supplier_category_revision VALUES (1,?) ON CONFLICT(singleton) DO UPDATE SET revision_id=excluded.revision_id').run(financialRevisionId);
  });
  return {revisionId:financialRevisionId,canonicalRecords:canonical,classifiedRecords,unclassifiedRecords:canonical-classifiedRecords,canonicalValueScaled:total,classifiedValueScaled:classified,unclassifiedValueScaled:total-classified,categoryCoverageRecords:canonical?classifiedRecords/canonical:0,categoryCoverageValue:total?classified/total:0};
}
