import type { DatabaseSync } from 'node:sqlite';
import { searchText } from '@senadotracker/domain';

export interface SupplierMarketQuery { year?: number; house?: 'all'|'CAMARA'|'SENADO'; limit?: number; search?: string; category?: string; }

export function publishedInstitutionalSupplierOverview(db: DatabaseSync, query: Pick<SupplierMarketQuery,'year'|'house'> = {}) {
  const year=query.year??new Date().getUTCFullYear(), house=query.house??'all', global=house==='all', table=global?'supplier_global_yearly':'supplier_global_house_yearly', houseWhere=global?'':' AND g.institution=?', params:Array<string|number>=global?[year]:[year,house];
  const totals=db.prepare(`SELECT count(*) suppliers,sum(coalesce(g.institutional_paid_scaled,0)) paid FROM ${table} g JOIN active_supplier_aggregate_revision ar ON ar.revision_id=g.revision_id AND ar.singleton=1 WHERE g.year=?${houseWhere} AND g.institutional_paid_scaled IS NOT NULL`).get(...params) as Record<string,unknown>;
  const suppliers=db.prepare(`SELECT g.supplier_id,s.canonical_name name,g.institutional_paid_scaled paid,g.institutional_contracts contracts FROM ${table} g JOIN active_supplier_aggregate_revision ar ON ar.revision_id=g.revision_id AND ar.singleton=1 JOIN suppliers s ON s.id=g.supplier_id WHERE g.year=?${houseWhere} AND g.institutional_paid_scaled IS NOT NULL ORDER BY paid DESC,g.supplier_id LIMIT 20`).all(...params) as Record<string,unknown>[];
  const total=Number(totals.paid??0),topFive=suppliers.slice(0,5).reduce((sum,row)=>sum+Number(row.paid??0),0);
  const houseBreakdown=db.prepare(`SELECT g.institution,sum(coalesce(g.institutional_paid_scaled,0)) paid,count(*) suppliers FROM supplier_global_house_yearly g JOIN active_supplier_aggregate_revision ar ON ar.revision_id=g.revision_id AND ar.singleton=1 WHERE g.year=? AND g.institutional_paid_scaled IS NOT NULL GROUP BY g.institution ORDER BY g.institution`).all(year) as Record<string,unknown>[];
  const observedHouses=houseBreakdown.map(row=>String(row.institution));
  const monthly=db.prepare(`SELECT c.institution, fm.movement_year year, CAST(substr(fm.occurred_at,6,2) AS INTEGER) month, sum(fm.amount_signed_scaled) paid, count(*) movements FROM financial_movements fm JOIN commitments c ON c.id=fm.commitment_id WHERE fm.phase='payment' AND fm.movement_year=?${house==='all'?'':' AND c.institution=?'} GROUP BY c.institution,fm.movement_year,month ORDER BY c.institution,month`).all(...(house==='all'?[year]:[year,house])) as Record<string,unknown>[];
  return {year,house,totalPaidCents:total,suppliers:Number(totals.suppliers??0),topSupplier:suppliers[0]??null,topFiveCents:topFive,topFiveShare:total?topFive/total:null,items:suppliers,houseBreakdown,observedHouses,monthly,topCategory:null as null,categoryAvailability:'unavailable' as const,monthlyAvailability:monthly.length?'available' as const:'unavailable' as const};
}

export function publishedCongressSupplierOverview(db: DatabaseSync, query: Pick<SupplierMarketQuery,'year'|'house'> = {}) {
  const year=query.year??new Date().getUTCFullYear(), house=query.house??'all', global=house==='all', table=global?'supplier_global_yearly':'supplier_global_house_yearly', houseWhere=global?'':' AND g.institution=?', params:Array<string|number>=global?[year]:[year,house];
  const totals=db.prepare(`SELECT sum(CASE WHEN coalesce(g.parliamentary_net_scaled,0)>0 OR coalesce(g.institutional_paid_scaled,0)>0 THEN 1 ELSE 0 END) suppliers_any,sum(CASE WHEN coalesce(g.parliamentary_net_scaled,0)>0 THEN 1 ELSE 0 END) suppliers_parliamentary,sum(CASE WHEN coalesce(g.institutional_paid_scaled,0)>0 THEN 1 ELSE 0 END) suppliers_institutional,sum(coalesce(g.parliamentary_net_scaled,0)) parliamentary,sum(coalesce(g.institutional_paid_scaled,0)) institutional FROM ${table} g JOIN active_supplier_aggregate_revision ar ON ar.revision_id=g.revision_id AND ar.singleton=1 WHERE g.year=?${houseWhere}`).get(...params) as Record<string,unknown>;
  const parliamentaryCents=Number(totals.parliamentary??0), institutionalCents=Number(totals.institutional??0), totalObservedCents=parliamentaryCents+institutionalCents;
  const top=(orderBy:string,limit:number)=>(db.prepare(`SELECT g.supplier_id,s.canonical_name name,coalesce(g.parliamentary_net_scaled,0) parliamentary,coalesce(g.institutional_paid_scaled,0) institutional FROM ${table} g JOIN active_supplier_aggregate_revision ar ON ar.revision_id=g.revision_id AND ar.singleton=1 JOIN suppliers s ON s.id=g.supplier_id WHERE g.year=?${houseWhere} ORDER BY ${orderBy} DESC,g.supplier_id LIMIT ?`).all(...params,limit) as Record<string,unknown>[]).map(row=>({supplierId:String(row.supplier_id),name:String(row.name??'Fornecedor sem nome'),parliamentary:Number(row.parliamentary),institutional:Number(row.institutional),total:Number(row.parliamentary)+Number(row.institutional)}));
  const unifiedTop=top('coalesce(g.parliamentary_net_scaled,0)+coalesce(g.institutional_paid_scaled,0)',5), parliamentaryTop=top('coalesce(g.parliamentary_net_scaled,0)',5), institutionalTop=top('coalesce(g.institutional_paid_scaled,0)',5);
  const topFiveCents=unifiedTop.reduce((sum,row)=>sum+row.total,0), topFiveParliamentaryCents=parliamentaryTop.reduce((sum,row)=>sum+row.parliamentary,0), topFiveInstitutionalCents=institutionalTop.reduce((sum,row)=>sum+row.institutional,0);
  const categories=(db.prepare(`SELECT category,sum(net_value_scaled) value FROM supplier_parliamentary_categories c JOIN active_supplier_aggregate_revision ar ON ar.revision_id=c.revision_id AND ar.singleton=1 WHERE c.year=?${global?'':' AND c.institution=?'} GROUP BY category ORDER BY value DESC LIMIT 10`).all(...params) as Record<string,unknown>[]).map(row=>({category:String(row.category),value:Number(row.value)}));
  const houseBreakdown=(db.prepare(`SELECT g.institution,sum(coalesce(g.parliamentary_net_scaled,0)) parliamentary,sum(coalesce(g.institutional_paid_scaled,0)) institutional FROM supplier_global_house_yearly g JOIN active_supplier_aggregate_revision ar ON ar.revision_id=g.revision_id AND ar.singleton=1 WHERE g.year=? GROUP BY g.institution ORDER BY g.institution`).all(year) as Record<string,unknown>[]).map(row=>{const parliamentary=Number(row.parliamentary),institutional=Number(row.institutional),total=parliamentary+institutional;return{institution:row.institution as 'CAMARA'|'SENADO',parliamentary,institutional,total,share:totalObservedCents?total/totalObservedCents:null}});
  const parliamentaryMonthly=db.prepare(`SELECT institution,month,sum(net_value_scaled) value FROM supplier_parliamentary_monthly m JOIN active_supplier_aggregate_revision ar ON ar.revision_id=m.revision_id AND ar.singleton=1 WHERE m.year=?${global?'':' AND m.institution=?'} GROUP BY institution,month`).all(...params) as Record<string,unknown>[];
  const institutionalMonthly=db.prepare(`SELECT c.institution,CAST(substr(fm.occurred_at,6,2) AS INTEGER) month,sum(fm.amount_signed_scaled) value FROM financial_movements fm JOIN commitments c ON c.id=fm.commitment_id WHERE fm.phase='payment' AND fm.movement_year=?${global?'':' AND c.institution=?'} GROUP BY c.institution,month`).all(...params) as Record<string,unknown>[];
  const monthlyMap=new Map<string,{institution:string;month:number;parliamentary:number;institutional:number}>();
  for(const row of parliamentaryMonthly){const institution=String(row.institution),month=Number(row.month);monthlyMap.set(`${institution}-${month}`,{institution,month,parliamentary:Number(row.value),institutional:0})}
  for(const row of institutionalMonthly){const institution=String(row.institution),month=Number(row.month),key=`${institution}-${month}`,current=monthlyMap.get(key)??{institution,month,parliamentary:0,institutional:0};current.institutional=Number(row.value);monthlyMap.set(key,current)}
  const monthly=[...monthlyMap.values()].map(row=>({...row,year,total:row.parliamentary+row.institutional})).sort((a,b)=>a.institution===b.institution?a.month-b.month:a.institution.localeCompare(b.institution));
  const years=db.prepare('SELECT DISTINCT year FROM active_expense_publications ORDER BY year DESC').all().map(row=>Number((row as Record<string,unknown>).year));
  // institutionalCategoryAvailability fica 'unavailable' até financial_movements ganhar expense_nature/elemento_despesa; quando existir, replicar o GROUP BY de categories acima sobre a nova coluna e trocar a flag.
  return {year,house,totalObservedCents,parliamentaryCents,institutionalCents,suppliersLinked:Number(totals.suppliers_any??0),suppliersParliamentary:Number(totals.suppliers_parliamentary??0),suppliersInstitutional:Number(totals.suppliers_institutional??0),topSupplier:unifiedTop[0]??null,topFiveCents,topFiveShare:totalObservedCents?topFiveCents/totalObservedCents:null,topSupplierParliamentary:parliamentaryTop[0]??null,topFiveParliamentaryCents,topFiveParliamentaryShare:parliamentaryCents?topFiveParliamentaryCents/parliamentaryCents:null,topSupplierInstitutional:institutionalTop[0]??null,topFiveInstitutionalCents,topFiveInstitutionalShare:institutionalCents?topFiveInstitutionalCents/institutionalCents:null,categories,houseBreakdown,monthly,years,parliamentaryCategoryAvailability:'available' as const,institutionalCategoryAvailability:'unavailable' as const};
}

export function publishedSupplierMarket(db: DatabaseSync, query: SupplierMarketQuery = {}) {
  const year=query.year??new Date().getUTCFullYear(), house=query.house??'all', limit=Math.min(5000,Math.max(100,query.limit??2000)), search=query.search?.trim()??'', category=query.category?.trim()??'';
  if(!Number.isSafeInteger(year)||year<2001||year>2100)throw new Error('Ano inválido');
  const global=house==='all', table=global?'supplier_global_yearly':'supplier_global_house_yearly', houseWhere=global?'':' AND g.institution=?', filterParts:string[]=[];const filterParams:Array<string|number>=[];
  if(search){filterParts.push(" AND EXISTS (SELECT 1 FROM supplier_names sn WHERE sn.supplier_id=g.supplier_id AND search_name GLOB ?||'*')");filterParams.push(searchText(search))}
  if(category){filterParts.push(" AND EXISTS (SELECT 1 FROM supplier_parliamentary_categories sc WHERE sc.revision_id=g.revision_id AND sc.supplier_id=g.supplier_id AND sc.year=g.year AND sc.category=?)");filterParams.push(category)}
  const filterWhere=filterParts.join('');
  const scopeParams:Array<string|number>=global?[year]:[year,house], filteredParams=[...scopeParams,...filterParams];
  const totals=db.prepare(`SELECT count(*) suppliers,sum(coalesce(g.parliamentary_net_scaled,0)) net,sum(coalesce(g.parliamentary_records,0)) records,sum(coalesce(g.parliamentarians,0)) parliamentarians FROM ${table} g JOIN active_supplier_aggregate_revision ar ON ar.revision_id=g.revision_id AND ar.singleton=1 WHERE g.year=?${houseWhere}${filterWhere}`).get(...filteredParams) as Record<string,unknown>;
  const top=db.prepare(`SELECT g.supplier_id,s.canonical_name name,coalesce(g.parliamentary_net_scaled,0) net,coalesce(g.parliamentary_records,0) records,coalesce(g.parliamentarians,0) parliamentarians,coalesce(g.ufs,0) ufs,coalesce(g.parties,0) parties FROM ${table} g JOIN active_supplier_aggregate_revision ar ON ar.revision_id=g.revision_id AND ar.singleton=1 JOIN suppliers s ON s.id=g.supplier_id WHERE g.year=?${houseWhere}${filterWhere} ORDER BY net DESC,g.supplier_id LIMIT ?`).all(...filteredParams,limit) as Record<string,unknown>[];
  const totalNet=Number(totals.net??0),topFive=top.slice(0,5).reduce((sum,row)=>sum+Number(row.net),0),topOne=Number(top[0]?.net??0),topTwenty=top.slice(0,20).reduce((sum,row)=>sum+Number(row.net),0),concentration={topOneCents:topOne,topFiveCents:topFive,topTwentyCents:topTwenty,remainingCents:Math.max(0,totalNet-topTwenty),topOneShare:totalNet?topOne/totalNet:null,topFiveShare:totalNet?topFive/totalNet:null,topTwentyShare:totalNet?topTwenty/totalNet:null};
  const dependency=new Map<string,{total:number;max:number}>();
  const ids=top.slice(0,Math.min(100,top.length)).map(row=>String(row.supplier_id));
  if(ids.length){const placeholders=ids.map(()=>'?').join(','),houseSql=global?'':' AND institution=?',rows=db.prepare(`SELECT supplier_id,client_source,client_external_id,net_value_scaled value FROM supplier_parliamentary_clients c JOIN active_supplier_aggregate_revision ar ON ar.revision_id=c.revision_id AND ar.singleton=1 WHERE c.year=?${houseSql} AND c.supplier_id IN (${placeholders})`).all(...(global?[year,...ids]:[year,house,...ids])) as Record<string,unknown>[];for(const row of rows){const id=String(row.supplier_id),value=Number(row.value),current=dependency.get(id)??{total:0,max:0};current.total+=value;current.max=Math.max(current.max,value);dependency.set(id,current)}}
  for(const row of top){const value=dependency.get(String(row.supplier_id));if(value)(row as Record<string,unknown>).dependency_share=value.total?value.max/value.total:null;}
  const sharedFive=Number(db.prepare(`SELECT count(*) n FROM ${table} g JOIN active_supplier_aggregate_revision ar ON ar.revision_id=g.revision_id AND ar.singleton=1 WHERE g.year=?${houseWhere} AND coalesce(g.parliamentarians,0)>=5`).get(...scopeParams)?.n??0);
  const newObserved=Number(db.prepare(`SELECT count(*) n FROM ${table} g JOIN active_supplier_aggregate_revision ar ON ar.revision_id=g.revision_id AND ar.singleton=1 WHERE g.year=?${houseWhere} AND NOT EXISTS (SELECT 1 FROM supplier_global_yearly old WHERE old.revision_id=g.revision_id AND old.supplier_id=g.supplier_id AND old.year<?)`).get(...scopeParams,year)?.n??0);
  const recurrence=db.prepare(`SELECT count(*) suppliers,sum(CASE WHEN years=1 THEN 1 ELSE 0 END) one_year,sum(CASE WHEN years>=3 THEN 1 ELSE 0 END) three_plus,sum(CASE WHEN years=(SELECT count(DISTINCT year) FROM supplier_global_yearly WHERE revision_id=(SELECT revision_id FROM active_supplier_aggregate_revision WHERE singleton=1)) THEN 1 ELSE 0 END) all_years FROM (SELECT supplier_id,count(DISTINCT year) years FROM supplier_global_yearly WHERE revision_id=(SELECT revision_id FROM active_supplier_aggregate_revision WHERE singleton=1) GROUP BY supplier_id)`).get() as Record<string,unknown>;
  const categories=db.prepare(`SELECT category,sum(net_value_scaled) value,count(DISTINCT supplier_id) suppliers FROM supplier_parliamentary_categories c JOIN active_supplier_aggregate_revision ar ON ar.revision_id=c.revision_id AND ar.singleton=1 WHERE c.year=?${global?'':' AND c.institution=?'}${category?' AND c.category=?':''} GROUP BY category ORDER BY value DESC LIMIT 10`).all(...scopeParams,...(category?[category]:[])).map(row=>row as Record<string,unknown>);
  const reachSummary=db.prepare(`SELECT ufs,parties,count(*) suppliers FROM ${table} g JOIN active_supplier_aggregate_revision ar ON ar.revision_id=g.revision_id AND ar.singleton=1 WHERE g.year=?${houseWhere} GROUP BY ufs,parties ORDER BY suppliers DESC LIMIT 12`).all(...scopeParams).map(row=>row as Record<string,unknown>);
  const monthly=db.prepare(`SELECT year,month,sum(net_value_scaled) value,count(DISTINCT supplier_id) suppliers FROM supplier_parliamentary_monthly m JOIN active_supplier_aggregate_revision ar ON ar.revision_id=m.revision_id AND ar.singleton=1 WHERE m.year<=?${global?'':' AND m.institution=?'} GROUP BY year,month ORDER BY year DESC,month DESC LIMIT 36`).all(...scopeParams).map(row=>row as Record<string,unknown>).reverse();
  const comparable=monthly.filter(row=>Number(row.year)===year||Number(row.year)===year-1), currentMonths=new Set(comparable.filter(row=>Number(row.year)===year).map(row=>Number(row.month))), previousMonths=new Set(comparable.filter(row=>Number(row.year)===year-1).map(row=>Number(row.month))), commonMonths=[...currentMonths].filter(month=>previousMonths.has(month));
  const currentComparable=commonMonths.reduce((sum,month)=>sum+Number(comparable.find(row=>Number(row.year)===year&&Number(row.month)===month)?.value??0),0), previousComparable=commonMonths.reduce((sum,month)=>sum+Number(comparable.find(row=>Number(row.year)===year-1&&Number(row.month)===month)?.value??0),0);
  const growth=commonMonths.length?{months:commonMonths.length,currentCents:currentComparable,previousCents:previousComparable,deltaCents:currentComparable-previousComparable,rate:previousComparable?currentComparable/previousComparable-1:null}:null;
  const dependencyRows=top.filter(row=>typeof row.dependency_share==='number').sort((a,b)=>Number(b.dependency_share)-Number(a.dependency_share)).slice(0,10);
  const highlights=dependencyRows.slice(0,5).map(row=>({kind:'dependency_share' as const,supplierId:String(row.supplier_id),name:String(row.name??'Fornecedor sem nome'),value:Number(row.dependency_share)}));
  const velocityIds=top.slice(0,100).map(row=>String(row.supplier_id)),velocity=new Map<string,{first:string|null;hundredThousand:string|null;fiveHundredThousand:string|null}>();
  if(velocityIds.length){const placeholders=velocityIds.map(()=>'?').join(','),rows=db.prepare(`SELECT supplier_id,year,month,sum(net_value_scaled) value FROM supplier_parliamentary_monthly m JOIN active_supplier_aggregate_revision ar ON ar.revision_id=m.revision_id AND ar.singleton=1 WHERE supplier_id IN (${placeholders})${global?'':' AND institution=?'} GROUP BY supplier_id,year,month ORDER BY supplier_id,year,month`).all(...(global?velocityIds:[...velocityIds,house])) as Record<string,unknown>[];let current='';let cumulative=0;for(const row of rows){const id=String(row.supplier_id);if(id!==current){current=id;cumulative=0;velocity.set(id,{first:`${row.year}-${String(row.month).padStart(2,'0')}`,hundredThousand:null,fiveHundredThousand:null})}cumulative+=Number(row.value??0);const item=velocity.get(id)!;const stamp=`${row.year}-${String(row.month).padStart(2,'0')}`;if(item.hundredThousand===null&&cumulative>=10000000)item.hundredThousand=stamp;if(item.fiveHundredThousand===null&&cumulative>=50000000)item.fiveHundredThousand=stamp;}}
  const clientChange=new Map<string,{current:number|null;previous:number|null;delta:number|null}>();
  if(velocityIds.length){const placeholders=velocityIds.map(()=>'?').join(','),houseSql=global?'':' AND c.institution=?',rows=db.prepare(`SELECT c.supplier_id,c.year,count(DISTINCT c.client_source||':'||c.client_external_id) clients FROM supplier_parliamentary_clients c JOIN active_supplier_aggregate_revision ar ON ar.revision_id=c.revision_id AND ar.singleton=1 WHERE c.supplier_id IN (${placeholders}) AND c.year IN (?,?)${houseSql} GROUP BY c.supplier_id,c.year`).all(...velocityIds,year,year-1,...(global?[]:[house])) as Record<string,unknown>[];for(const row of rows){const id=String(row.supplier_id),item=clientChange.get(id)??{current:null,previous:null,delta:null};if(Number(row.year)===year)item.current=Number(row.clients);if(Number(row.year)===year-1)item.previous=Number(row.clients);item.delta=item.current!==null&&item.previous!==null?item.current-item.previous:null;clientChange.set(id,item)}}
  const velocityItems=top.slice(0,20).map(row=>({supplierId:String(row.supplier_id),name:String(row.name??'Fornecedor sem nome'),...velocity.get(String(row.supplier_id))??{first:null,hundredThousand:null,fiveHundredThousand:null},clients:clientChange.get(String(row.supplier_id))??{current:null,previous:null,delta:null}}));
  const feed=[...(highlights[0]?[{kind:'concentration' as const,title:'Concentração observada',supplierId:highlights[0].supplierId,name:highlights[0].name,value:highlights[0].value}]:[]),...(sharedFive?[{kind:'shared' as const,title:'Fornecedores compartilhados',supplierId:null,name:`${sharedFive.toLocaleString('pt-BR')} fornecedores aparecem para 5 ou mais parlamentares`,value:null}]:[]),...(newObserved?[{kind:'new' as const,title:'Primeiro ano observado',supplierId:null,name:`${newObserved.toLocaleString('pt-BR')} fornecedores aparecem pela primeira vez na série coberta`,value:null}]:[])];
  return {year,house,coverage:{suppliers:Number(totals.suppliers??0),records:Number(totals.records??0),parliamentarians:Number(totals.parliamentarians??0)},totalNetCents:totalNet,topFiveCents:topFive,topFiveShare:totalNet?topFive/totalNet:null,concentration,sharedFive,newObserved,points:top,recurrence, highlights, feed, categories, monthly, growth, velocity:velocityItems, reachSummary};
}
