import type { DatabaseSync } from 'node:sqlite';
import { startRun, transaction } from './index.ts';

export function publishSupplierAggregates(db: DatabaseSync, now = new Date().toISOString()) {
  const runId = startRun(db, 'civica');
  transaction(db, () => {
    db.prepare("INSERT INTO supplier_aggregate_revisions VALUES (?,?,'validated','{}')").run(runId, now);
    db.prepare(`INSERT INTO supplier_parliamentary_yearly SELECT ?,l.supplier_id,e.year,CASE e.source WHEN 'camara' THEN 'CAMARA' ELSE 'SENADO' END,sum(e.net_cents-e.refund_cents),2,count(*),count(DISTINCT e.source||':'||e.external_id),count(DISTINCT p.uf),count(DISTINCT p.party),min(coalesce(e.issued_at,printf('%04d-%02d-01',e.year,e.month))),max(coalesce(e.issued_at,printf('%04d-%02d-01',e.year,e.month))) FROM expenses e JOIN active_expense_publications a ON a.batch_id=e.batch_id JOIN expense_supplier_links l ON l.batch_id=e.batch_id AND l.record_key=e.record_key AND l.match_status='confirmed' JOIN active_publications ap ON ap.source=e.source JOIN profiles p ON p.batch_id=ap.batch_id AND p.external_id=e.external_id GROUP BY l.supplier_id,e.year,e.source`).run(runId);
    db.prepare(`INSERT INTO supplier_parliamentary_clients SELECT ?,l.supplier_id,e.year,CASE e.source WHEN 'camara' THEN 'CAMARA' ELSE 'SENADO' END,e.source,e.external_id,sum(e.net_cents-e.refund_cents),2,count(*) FROM expenses e JOIN active_expense_publications a ON a.batch_id=e.batch_id JOIN expense_supplier_links l ON l.batch_id=e.batch_id AND l.record_key=e.record_key AND l.match_status='confirmed' GROUP BY l.supplier_id,e.year,e.source,e.external_id`).run(runId);
    db.prepare(`INSERT INTO supplier_parliamentary_congress_yearly SELECT ?,l.supplier_id,e.year,sum(e.net_cents-e.refund_cents),2,count(*),count(DISTINCT e.source||':'||e.external_id),count(DISTINCT p.uf),count(DISTINCT p.party),count(DISTINCT e.source),min(coalesce(e.issued_at,printf('%04d-%02d-01',e.year,e.month))),max(coalesce(e.issued_at,printf('%04d-%02d-01',e.year,e.month))) FROM expenses e JOIN active_expense_publications a ON a.batch_id=e.batch_id JOIN expense_supplier_links l ON l.batch_id=e.batch_id AND l.record_key=e.record_key AND l.match_status='confirmed' JOIN active_publications ap ON ap.source=e.source JOIN profiles p ON p.batch_id=ap.batch_id AND p.external_id=e.external_id GROUP BY l.supplier_id,e.year`).run(runId);
    db.prepare(`INSERT INTO supplier_parliamentary_monthly SELECT ?,l.supplier_id,e.year,e.month,CASE e.source WHEN 'camara' THEN 'CAMARA' ELSE 'SENADO' END,sum(e.net_cents-e.refund_cents),2,count(*) FROM expenses e JOIN active_expense_publications a ON a.batch_id=e.batch_id JOIN expense_supplier_links l ON l.batch_id=e.batch_id AND l.record_key=e.record_key AND l.match_status='confirmed' GROUP BY l.supplier_id,e.year,e.month,e.source`).run(runId);
    db.prepare(`INSERT INTO supplier_parliamentary_categories SELECT ?,l.supplier_id,e.year,CASE e.source WHEN 'camara' THEN 'CAMARA' ELSE 'SENADO' END,e.category,sum(e.net_cents-e.refund_cents),2,count(*) FROM expenses e JOIN active_expense_publications a ON a.batch_id=e.batch_id JOIN expense_supplier_links l ON l.batch_id=e.batch_id AND l.record_key=e.record_key AND l.match_status='confirmed' GROUP BY l.supplier_id,e.year,e.source,e.category`).run(runId);
    db.prepare(`INSERT INTO supplier_institutional_yearly SELECT ?,cm.supplier_id,m.movement_year,cm.institution,sum(CASE WHEN m.phase='commitment' THEN m.amount_signed_scaled END),sum(CASE WHEN m.phase='liquidation' THEN m.amount_signed_scaled END),sum(CASE WHEN m.phase='payment' THEN m.amount_signed_scaled END),2,count(DISTINCT cm.contract_id),count(DISTINCT cm.id),CASE cm.institution WHEN 'SENADO' THEN 'Ano da NE; execução e restos posteriores podem estar agregados' ELSE 'Ano do movimento financeiro publicado' END FROM commitments cm JOIN financial_movements m ON m.commitment_id=cm.id WHERE cm.supplier_id IS NOT NULL AND ((cm.institution='CAMARA' AND m.source_system='camara_financeiro') OR (cm.institution='SENADO' AND m.source_system='senado_siafi')) GROUP BY cm.supplier_id,m.movement_year,cm.institution`).run(runId);
    db.prepare(`INSERT INTO supplier_global_yearly WITH institutional AS (SELECT supplier_id,year,sum(paid_scaled) paid,sum(contracts) contracts,sum(commitments) commitments,count(*) houses FROM supplier_institutional_yearly WHERE revision_id=? GROUP BY supplier_id,year),keys AS (SELECT supplier_id,year FROM supplier_parliamentary_congress_yearly WHERE revision_id=? UNION SELECT supplier_id,year FROM institutional) SELECT ?,k.supplier_id,k.year,p.net_value_scaled,p.records,p.parliamentarians,p.ufs,p.parties,p.houses,i.paid,i.contracts,i.commitments,i.houses,p.first_observed_at,p.last_observed_at FROM keys k LEFT JOIN supplier_parliamentary_congress_yearly p ON p.revision_id=? AND p.supplier_id=k.supplier_id AND p.year=k.year LEFT JOIN institutional i ON i.supplier_id=k.supplier_id AND i.year=k.year`).run(runId,runId,runId,runId);
    db.prepare(`INSERT INTO supplier_global_house_yearly WITH keys AS (SELECT supplier_id,year,institution FROM supplier_parliamentary_yearly WHERE revision_id=? UNION SELECT supplier_id,year,institution FROM supplier_institutional_yearly WHERE revision_id=?) SELECT ?,k.supplier_id,k.year,k.institution,p.net_value_scaled,p.records,p.parliamentarians,p.ufs,p.parties,i.paid_scaled,i.contracts,i.commitments,p.first_observed_at,p.last_observed_at FROM keys k LEFT JOIN supplier_parliamentary_yearly p ON p.revision_id=? AND p.supplier_id=k.supplier_id AND p.year=k.year AND p.institution=k.institution LEFT JOIN supplier_institutional_yearly i ON i.revision_id=? AND i.supplier_id=k.supplier_id AND i.year=k.year AND i.institution=k.institution`).run(runId,runId,runId,runId,runId);
    const counts = {
      parliamentary: Number(db.prepare('SELECT count(*) n FROM supplier_parliamentary_yearly WHERE revision_id=?').get(runId)?.n ?? 0),
      congress: Number(db.prepare('SELECT count(*) n FROM supplier_parliamentary_congress_yearly WHERE revision_id=?').get(runId)?.n ?? 0),
      monthly: Number(db.prepare('SELECT count(*) n FROM supplier_parliamentary_monthly WHERE revision_id=?').get(runId)?.n ?? 0),
      categories: Number(db.prepare('SELECT count(*) n FROM supplier_parliamentary_categories WHERE revision_id=?').get(runId)?.n ?? 0),
      institutional: Number(db.prepare('SELECT count(*) n FROM supplier_institutional_yearly WHERE revision_id=?').get(runId)?.n ?? 0),
      global: Number(db.prepare('SELECT count(*) n FROM supplier_global_yearly WHERE revision_id=?').get(runId)?.n ?? 0),
      globalHouse: Number(db.prepare('SELECT count(*) n FROM supplier_global_house_yearly WHERE revision_id=?').get(runId)?.n ?? 0),
    };
    db.prepare("UPDATE supplier_aggregate_revisions SET status='published',reconciliation_json=? WHERE id=?").run(JSON.stringify(counts), runId);
    db.prepare('INSERT INTO active_supplier_aggregate_revision VALUES (1,?) ON CONFLICT(singleton) DO UPDATE SET revision_id=excluded.revision_id').run(runId);
    db.prepare("UPDATE ingestion_runs SET status='published',finished_at=?,expected_count=?,roster_complete=1,reconciliation_json=? WHERE id=?").run(now, counts.parliamentary + counts.institutional, JSON.stringify(counts), runId);
    db.prepare('DELETE FROM job_locks WHERE run_id=?').run(runId);
  });
  return { runId, ...JSON.parse(String(db.prepare('SELECT reconciliation_json FROM supplier_aggregate_revisions WHERE id=?').get(runId)?.reconciliation_json)) };
}
