import type { DataCoverage } from '@senadotracker/domain';
import { ReceiptText,Users } from 'lucide-react';
import { InstitutionHero,ProfileHero } from '@/components/heroes';
import { SearchBar,FilterBar } from '@/components/data-controls';
import { KpiCard,KpiGrid } from '@/components/metrics';
import { NavigationCard,ExplainerCard } from '@/components/content-cards';
import { DataTable,type DataColumn } from '@/components/data-table';
import { BarChart,HistogramChart,LineChart,StackedBarChart,type ChartTone } from '@/components/charts';
import { BenchmarkRuler,type KpiBenchmark } from '@/components/benchmark-ruler';
import { DumbbellCell,DumbbellLegend } from '@/components/dumbbell';
import { TogglePills } from '@/components/toggle-pills';
import { bandOf,sequentialRamp } from '@/lib/scale';
import { percent as pct } from '@/lib/format';
import { StateChoroplethMap } from '@/components/state-choropleth-map';
import { evalLabel,evalTone,evalVar,toneLegend } from '@/lib/eval-color';
import { OfficialSourcesCard,OfficialSourcesStrip,type OfficialSource } from '@/components/official-sources';
import { ComparisonBar } from '@/components/comparison-bar';
import { SectionHeader,SectionTabs } from '@/components/section-navigation';
import { Button } from '@/components/ui/button';
import { Card,CardContent,CardHeader } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

export const metadata={title:'Sistema visual'};
const coverage=(availability:DataCoverage['availability'],note:string):DataCoverage=>({availability,source:'senado',period:{from:'2026-01-01',to:'2026-08-31',grain:'month'},batchId:availability==='unavailable'?null:'catalogo-visual',note,sampleSize:availability==='unavailable'?0:79});
const available=coverage('available','Lote validado e publicado.');const partial=coverage('partial','Cobertura disponível para parte do universo.');const unavailable=coverage('unavailable','Nenhum lote compatível foi publicado.');const stale=coverage('stale','O lote publicado excedeu a janela de atualização.');const notApplicable=coverage('not_applicable','Esta métrica não se aplica ao recorte.');
const sources:OfficialSource[]=[{name:'Senado Federal',url:'https://www12.senado.leg.br/dados-abertos/',updatedAt:'31/08/2026',batchId:'catalogo-visual'},{name:'Câmara dos Deputados',url:'https://dadosabertos.camara.leg.br/',updatedAt:null,batchId:null,note:'Exemplo de atualização indisponível.'}];
type Row={id:string;name:string;party:string;value:number};const rows:Row[]=[{id:'1',name:'Parlamentar de exemplo A',party:'AAA/SP',value:120000},{id:'2',name:'Parlamentar de exemplo B',party:'BBB/RJ',value:98000}];const columns:DataColumn<Row>[]=[{key:'name',header:'Nome',render:r=><strong>{r.name}</strong>},{key:'party',header:'Partido/UF',render:r=>r.party},{key:'value',header:'Valor',align:'right',render:r=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(r.value/100)}];
const chart=[{label:'A',value:12},{label:'B',value:28},{label:'C',value:19},{label:'D',value:35}];
// Escala de avaliação exercitada com valores fixos: evalTone, a régua e o painter são funções puras,
// então este catálogo é a prova visual sem tocar o banco.
const costScale={median:22,p10:10,p90:32,direction:'higher-is-worse' as const,availability:'available' as const,sampleSize:81};
const costTone:ChartTone={of:datum=>evalVar(evalTone(datum.value,costScale)),legend:toneLegend('higher-is-worse')};
const ruler=(value:number|null,percentile:number|null,extra:Partial<KpiBenchmark>={}):KpiBenchmark=>({value,unit:'cents',direction:'higher-is-worse',median:2_500_00,p10:1_200_00,p90:4_100_00,percentile,sampleSize:81,availability:'available',universeLabel:'senadores',note:'cota de 2026 no mesmo lote',...extra});
const mapUfs=['SP','RJ','MG','BA','PR','RS','PE','CE','PA','SC','GO','MA','AM','ES','PB','RN','MT','AL','PI','DF','MS','SE','RO','TO','AC'];
const choropleth={meta:{key:'expenseCents' as const,label:'Cota parlamentar',unit:'cents' as const,direction:'higher-is-worse' as const,houseMinSample:10,stateMinSample:3,partyMinSample:3,note:'Exemplo do catálogo.'},
  buckets:[0,1,2,3,4].map(index=>({index,from:(15+index*4)*100_00,to:(19+index*4)*100_00,count:index===4?5:index===0?4:4})),
  items:[...mapUfs.map((uf,index)=>({uf,value:(15+(index%5)*4)*100_00+index*100,sampleSize:3+index,bucket:index%5})),
    // Três UFs sem universo suficiente: precisam sair em cinza, não no tom mais claro da rampa.
    ...['RR','AP'].map(uf=>({uf,value:null,sampleSize:2,bucket:null})),{uf:'PB',value:null,sampleSize:0,bucket:null}]
    .filter((item,index,all)=>all.findIndex(other=>other.uf===item.uf)===index)
    .map(item=>({...item,coverage:coverage(item.bucket===null?'unavailable':'available','Exemplo do catálogo.')})),
  coverage:coverage('partial','Exemplo do catálogo: três UFs sem universo suficiente.')};
const stateNames:Record<string,string>={AC:'Acre',AL:'Alagoas',AP:'Amapá',AM:'Amazonas',BA:'Bahia',CE:'Ceará',DF:'Distrito Federal',ES:'Espírito Santo',GO:'Goiás',MA:'Maranhão',MT:'Mato Grosso',MS:'Mato Grosso do Sul',MG:'Minas Gerais',PA:'Pará',PB:'Paraíba',PR:'Paraná',PE:'Pernambuco',PI:'Piauí',RJ:'Rio de Janeiro',RN:'Rio Grande do Norte',RS:'Rio Grande do Sul',RO:'Rondônia',RR:'Roraima',SC:'Santa Catarina',SP:'São Paulo',SE:'Sergipe',TO:'Tocantins'};const tabs=[{id:'fundacoes',label:'Fundações'},{id:'componentes',label:'Componentes'},{id:'dados',label:'Dados'},{id:'navegacao',label:'Navegação'}];
export default function DesignSystemPage(){return <main id="conteudo" tabIndex={-1}><div className="page-shell py-10"><InstitutionHero context="Catálogo interno" title="Sistema visual legislativo" description="Componentes compartilhados com cobertura, período e origem obrigatórios. Os valores abaixo são exemplos rotulados para revisão visual." location="Ambiente de desenvolvimento" actions={<Button variant="outline" className="bg-white text-foreground">Revisar componentes</Button>}/></div><SectionTabs items={tabs}/><div className="page-shell space-y-20 py-14">
<section className="space-y-8"><SectionHeader number={1} id="fundacoes" title="Fundações" description="Tokens preservam o verde institucional e as superfícies de papel da experiência existente."/><div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><h3 className="text-xl font-bold">Cores e superfícies</h3></CardHeader><CardContent className="grid grid-cols-2 gap-3">{[['Primária','bg-primary text-primary-foreground'],['Secundária','bg-secondary text-secondary-foreground'],['Cartão','bg-card'],['Sucesso','bg-success text-white'],['Atenção','bg-warning text-white'],['Erro','bg-danger text-white']].map(([label,style])=><div key={label} className={`rounded-xl border p-5 ${style}`}>{label}</div>)}</CardContent></Card><Card><CardHeader><h3 className="text-xl font-bold">Controles e foco</h3></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Button>Primário</Button><Button variant="outline">Contorno</Button><Button variant="ghost">Discreto</Button></div><label className="block text-sm font-bold">Campo de exemplo<Input className="mt-2" placeholder="Use Tab para conferir o foco"/></label></CardContent></Card></div></section>
<section className="space-y-8"><SectionHeader number={2} id="componentes" title="Heróis, busca e cartões"/><ProfileHero name="Nome parlamentar" subtitle="Partido · Estado" role="Senador da República" mandate="Mandato informado pela fonte oficial" sources={<OfficialSourcesCard sources={sources}/>} actions={<Button variant="outline" className="bg-white text-foreground">Perfil oficial ↗</Button>}/><SearchBar/><FilterBar fields={[{name:'estado',label:'Estado',options:[{value:'',label:'Todos'},{value:'SP',label:'São Paulo'}]},{name:'partido',label:'Partido',options:[{value:'',label:'Todos'},{value:'AAA',label:'AAA'}]}]}/><div className="grid gap-4 md:grid-cols-2"><NavigationCard icon={Users} title="Senadores" description="Explore representantes, atuação e dados publicados." href="/legislativo/senadores" meta="Legislativo"/><ExplainerCard icon={ReceiptText} title="Como ler gastos">Rubricas parciais aparecem separadas e nunca recebem o rótulo de custo total.</ExplainerCard></div></section>
<section className="space-y-8"><SectionHeader number={3} id="dados" title="Estados e visualizações" description="Disponibilidade, universo e período acompanham cada número."/><KpiGrid><KpiCard label="Texto livre fica neutro" value="79" coverage={available} comparison="Acima do período comparável" icon={Users}/><KpiCard label="Parcial" value="R$ 1.234" coverage={partial} comparison={null} icon={ReceiptText}/><KpiCard label="Indisponível" value={null} coverage={unavailable} comparison={null}/><KpiCard label="Desatualizado" value="27" coverage={stale} comparison={null}/><KpiCard label="Não se aplica" value={null} coverage={notApplicable} comparison={null}/></KpiGrid><div className="grid gap-6 lg:grid-cols-2"><HistogramChart title="Histograma" data={chart} coverage={available}/><BarChart title="Barras" data={chart} coverage={partial}/><StackedBarChart title="Barras empilhadas" data={[{label:'AAA',segments:[{label:'Sim',value:18},{label:'Não',value:7},{label:'Abstenção',value:2}]},{label:'BBB',segments:[{label:'Sim',value:9},{label:'Não',value:12},{label:'Abstenção',value:3}]}]} coverage={available}/><LineChart title="Série com lacuna" data={[{label:'2023',value:14},{label:'2024',value:null},{label:'2025',value:22},{label:'2026',value:25}]} coverage={partial}/></div><DataTable caption="Parlamentares de exemplo" columns={columns} rows={rows} rowKey={r=>r.id} coverage={available} page={1} pageCount={2} pageHref={p=>`/design-system?pagina=${p}`}/><DataTable caption="Estado vazio" columns={columns} rows={[]} rowKey={r=>r.id} coverage={unavailable}/>
<div><h3 className="text-xl font-bold">Escala de avaliação</h3><p className="mt-2 max-w-3xl text-sm text-muted-foreground">A cor codifica a relação com um referencial, não a série. Cobertura insuficiente permanece cinza — nunca verde, nunca vermelho — para preservar a ausência de nota geral. A cor nunca viaja sozinha: acompanha sempre seta e rótulo.</p>
<ul className="mt-5 flex flex-wrap gap-4 text-xs">{(['good','watch','alert','typical','unknown'] as const).map(tone=><li className="flex items-center gap-2" key={tone}><i className="size-4 rounded" style={{background:evalVar(tone)}}/><span><strong className="block">{tone}</strong>{evalLabel(tone,'higher-is-worse')}</span></li>)}</ul>
<KpiGrid className="mt-6"><KpiCard label="Régua · percentil alto" value="R$ 4.500" coverage={available} comparison={ruler(4_500_00,.93)} icon={ReceiptText}/><KpiCard label="Régua · percentil baixo" value="R$ 1.100" coverage={available} comparison={ruler(1_100_00,.06)} icon={ReceiptText}/><KpiCard label="Régua · sem percentil" value="R$ 3.000" coverage={available} comparison={ruler(3_000_00,null)} icon={ReceiptText}/><KpiCard label="Régua · universo curto" value="R$ 3.000" coverage={partial} comparison={ruler(3_000_00,.5,{availability:'partial',sampleSize:4})} icon={ReceiptText}/></KpiGrid>
<div className="mt-5 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-card p-5"><p className="text-sm font-semibold text-muted-foreground">Contagem lê melhor como múltiplo</p><strong className="mt-2 block text-2xl">7 vínculos</strong><BenchmarkRuler benchmark={{value:7,unit:'count',direction:'higher-is-worse',median:5,p10:2,p90:9,percentile:null,sampleSize:81,availability:'available',universeLabel:'senadores',note:'snapshot do gabinete'}}/></div><div className="rounded-2xl border bg-card p-5"><p className="text-sm font-semibold text-muted-foreground">Razão com direção invertida</p><strong className="mt-2 block text-2xl">62%</strong><BenchmarkRuler benchmark={{value:.62,unit:'ratio',direction:'higher-is-better',median:.84,p10:.7,p90:.95,percentile:.08,sampleSize:513,availability:'available',universeLabel:'deputados',note:'votações nominais de 2026'}}/></div><div className="rounded-2xl border bg-card p-5"><p className="text-sm font-semibold text-muted-foreground">Sem referencial compatível</p><strong className="mt-2 block text-2xl">—</strong><BenchmarkRuler benchmark={{value:null,unit:'cents',direction:'higher-is-worse',median:null,p10:null,p90:null,percentile:null,sampleSize:0,availability:'unavailable',universeLabel:'senadores',note:'nenhum lote publicado'}}/></div></div>
<div className="mt-6 grid gap-6 lg:grid-cols-2"><BarChart title="Barras com tom semântico" data={chart} coverage={available} tone={costTone}/><HistogramChart title="Histograma com tom semântico" data={chart} coverage={available} tone={costTone}/></div></div>
<div><h3 className="text-xl font-bold">Matriz de concordância</h3><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Faixas fixas, porque um percentual de concordância vale o que diz. O número está em toda célula: a cor acelera a leitura, nunca a carrega sozinha. Par sem votação em comum fica cinza tracejado, nunca 0%.</p>
<div className="mt-5 overflow-x-auto rounded-2xl border bg-card p-4"><table className="w-full min-w-[420px] border-separate border-spacing-1 text-sm"><caption className="sr-only">Exemplo de matriz de concordância</caption>
<thead><tr><td/>{['Ana','Bruno','Célia'].map(name=><th key={name} scope="col" className="p-2 text-left text-xs font-bold">{name}</th>)}</tr></thead>
<tbody>{[[null,.94,.41],[.94,null,.38],[.41,.38,null]].map((row,rowIndex)=><tr key={rowIndex}><th scope="row" className="p-2 text-left text-xs font-bold">{['Ana','Bruno','Célia'][rowIndex]}</th>
{row.map((value,columnIndex)=>{if(value===null)return <td key={columnIndex} className="rounded-lg bg-muted/40 p-3 text-center text-xs text-muted-foreground">—</td>;
if(rowIndex===2&&columnIndex===1)return <td key={columnIndex} className="rounded-lg border border-dashed p-3 text-center text-xs text-muted-foreground">sem votos comuns</td>;
const band=bandOf(value,[.5,.65,.8,.9]);return <td key={columnIndex} className="rounded-lg p-3 text-center" style={{background:sequentialRamp[band],color:band>=3?'#fff':'var(--foreground)'}}><strong className="block tabular-nums">{pct(value)}</strong><small className="tabular-nums opacity-80">n=87</small></td>})}</tr>)}</tbody></table></div></div>
<div><h3 className="text-xl font-bold">Dumbbell e alternância de unidade</h3><p className="mt-2 max-w-3xl text-sm text-muted-foreground">A haste é a história. Sem valência de cor: variar patrimônio não é mérito nem demérito, então o que se codifica é direção — vazado é o ponto de partida, cheio é o mais recente. A escala é compartilhada pelas linhas.</p>
<div className="mt-5 flex flex-wrap items-end gap-6"><TogglePills label="Unidade de comparação" current="nominal" pills={[{value:'nominal',label:'Valores nominais',href:'/design-system#dados'},{value:'ipca',label:'Corrigido pelo IPCA',href:'/design-system#dados',disabled:true,reason:'Exemplo de opção indisponível: o índice do mês de referência não está publicado.'}]}/></div>
<div className="mt-5 rounded-2xl border bg-card p-5"><DumbbellLegend fromLabel="2018" toLabel="2022"/><div className="mt-4 grid gap-4 sm:grid-cols-2">{[{label:'Crescimento',from:120_000_00,to:480_000_00},{label:'Redução',from:400_000_00,to:150_000_00}].map(item=><div key={item.label}><p className="text-xs font-bold text-muted-foreground">{item.label}</p><div className="mt-1"><DumbbellCell fromCents={item.from} toCents={item.to} max={480_000_00} fromLabel="2018" toLabel="2022"/></div></div>)}</div></div></div>
<div><h3 className="text-xl font-bold">Mapa coroplético</h3><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Rampa sequencial de quintis para magnitude. UF sem universo suficiente recebe cinza quente, fora do matiz da rampa, para não ser confundida com valor baixo. Siglas em tom escuro trocam de tinta e ganham halo.</p><div className="mt-5"><StateChoroplethMap data={choropleth} names={stateNames} href={uf=>`/design-system#${uf}`}/></div></div></section>
<section className="space-y-8"><SectionHeader number={4} id="navegacao" title="Fontes e comparação"/><OfficialSourcesCard sources={sources}/><ComparisonBar source="senado" options={[{id:'1',label:'Parlamentar A',source:'senado'},{id:'2',label:'Parlamentar B',source:'senado'},{id:'3',label:'Parlamentar C',source:'senado'}]}/></section></div><OfficialSourcesStrip sources={sources}/></main>}
