import type { DataCoverage } from '@senadotracker/domain';
import { ReceiptText,Users } from 'lucide-react';
import { InstitutionHero,ProfileHero } from '@/components/heroes';
import { SearchBar,FilterBar } from '@/components/data-controls';
import { KpiCard,KpiGrid } from '@/components/metrics';
import { NavigationCard,ExplainerCard } from '@/components/content-cards';
import { DataTable,type DataColumn } from '@/components/data-table';
import { BarChart,HistogramChart,LineChart,StackedBarChart } from '@/components/charts';
import { OfficialSourcesCard,OfficialSourcesStrip,type OfficialSource } from '@/components/official-sources';
import { ComparisonBar } from '@/components/comparison-bar';
import { SectionHeader,SectionTabs } from '@/components/section-navigation';
import { Button } from '@/components/ui/button';
import { Card,CardContent,CardHeader } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

export const metadata={title:'Sistema visual'};
const coverage=(availability:DataCoverage['availability'],note:string):DataCoverage=>({availability,source:'senado',period:{from:'2026-01-01',to:'2026-08-31',grain:'month'},batchId:availability==='unavailable'?null:'catalogo-visual',note,sampleSize:availability==='unavailable'?0:79});
const available=coverage('available','Lote validado e publicado.');const partial=coverage('partial','Cobertura disponível para parte do universo.');const unavailable=coverage('unavailable','Nenhum lote compatível foi publicado.');const stale=coverage('stale','O lote publicado excedeu a janela de atualização.');const notApplicable=coverage('not_applicable','Esta métrica não se aplica ao recorte.');
const sources:OfficialSource[]=[{name:'Senado Federal',url:'https://www12.senado.leg.br/dados-abertos/',updatedAt:'31/08/2026',batchId:'catalogo-visual'},{name:'Câmara dos Deputados',url:'https://dadosabertos.camara.leg.br/',updatedAt:null,batchId:null,note:'Exemplo de atualização indisponível.'}];
type Row={id:string;name:string;party:string;value:number};const rows:Row[]=[{id:'1',name:'Parlamentar de exemplo A',party:'AAA/SP',value:120000},{id:'2',name:'Parlamentar de exemplo B',party:'BBB/RJ',value:98000}];const columns:DataColumn<Row>[]=[{key:'name',header:'Nome',render:r=><strong>{r.name}</strong>},{key:'party',header:'Partido/UF',render:r=>r.party},{key:'value',header:'Valor',align:'right',render:r=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(r.value/100)}];
const chart=[{label:'A',value:12},{label:'B',value:28},{label:'C',value:19},{label:'D',value:35}];const tabs=[{id:'fundacoes',label:'Fundações'},{id:'componentes',label:'Componentes'},{id:'dados',label:'Dados'},{id:'navegacao',label:'Navegação'}];
export default function DesignSystemPage(){return <main id="conteudo" tabIndex={-1}><div className="page-shell py-10"><InstitutionHero context="Catálogo interno" title="Sistema visual legislativo" description="Componentes compartilhados com cobertura, período e origem obrigatórios. Os valores abaixo são exemplos rotulados para revisão visual." location="Ambiente de desenvolvimento" actions={<Button variant="outline" className="bg-white text-foreground">Revisar componentes</Button>}/></div><SectionTabs items={tabs}/><div className="page-shell space-y-20 py-14">
<section className="space-y-8"><SectionHeader number={1} id="fundacoes" title="Fundações" description="Tokens preservam o verde institucional e as superfícies de papel da experiência existente."/><div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><h3 className="text-xl font-bold">Cores e superfícies</h3></CardHeader><CardContent className="grid grid-cols-2 gap-3">{[['Primária','bg-primary text-primary-foreground'],['Secundária','bg-secondary text-secondary-foreground'],['Cartão','bg-card'],['Sucesso','bg-success text-white'],['Atenção','bg-warning text-white'],['Erro','bg-danger text-white']].map(([label,style])=><div key={label} className={`rounded-xl border p-5 ${style}`}>{label}</div>)}</CardContent></Card><Card><CardHeader><h3 className="text-xl font-bold">Controles e foco</h3></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Button>Primário</Button><Button variant="outline">Contorno</Button><Button variant="ghost">Discreto</Button></div><label className="block text-sm font-bold">Campo de exemplo<Input className="mt-2" placeholder="Use Tab para conferir o foco"/></label></CardContent></Card></div></section>
<section className="space-y-8"><SectionHeader number={2} id="componentes" title="Heróis, busca e cartões"/><ProfileHero name="Nome parlamentar" subtitle="Partido · Estado" role="Senador da República" mandate="Mandato informado pela fonte oficial" sources={<OfficialSourcesCard sources={sources}/>} actions={<Button variant="outline" className="bg-white text-foreground">Perfil oficial ↗</Button>}/><SearchBar/><FilterBar fields={[{name:'estado',label:'Estado',options:[{value:'',label:'Todos'},{value:'SP',label:'São Paulo'}]},{name:'partido',label:'Partido',options:[{value:'',label:'Todos'},{value:'AAA',label:'AAA'}]}]}/><div className="grid gap-4 md:grid-cols-2"><NavigationCard icon={Users} title="Senadores" description="Explore representantes, atuação e dados publicados." href="/legislativo/senadores" meta="Legislativo"/><ExplainerCard icon={ReceiptText} title="Como ler gastos">Rubricas parciais aparecem separadas e nunca recebem o rótulo de custo total.</ExplainerCard></div></section>
<section className="space-y-8"><SectionHeader number={3} id="dados" title="Estados e visualizações" description="Disponibilidade, universo e período acompanham cada número."/><KpiGrid><KpiCard label="Disponível" value="79" coverage={available} comparison="Acima do período comparável" icon={Users}/><KpiCard label="Parcial" value="R$ 1.234" coverage={partial} comparison={null} icon={ReceiptText}/><KpiCard label="Indisponível" value={null} coverage={unavailable} comparison={null}/><KpiCard label="Desatualizado" value="27" coverage={stale} comparison={null}/><KpiCard label="Não se aplica" value={null} coverage={notApplicable} comparison={null}/></KpiGrid><div className="grid gap-6 lg:grid-cols-2"><HistogramChart title="Histograma" data={chart} coverage={available}/><BarChart title="Barras" data={chart} coverage={partial}/><StackedBarChart title="Barras empilhadas" data={[{label:'AAA',segments:[{label:'Sim',value:18},{label:'Não',value:7},{label:'Abstenção',value:2}]},{label:'BBB',segments:[{label:'Sim',value:9},{label:'Não',value:12},{label:'Abstenção',value:3}]}]} coverage={available}/><LineChart title="Série com lacuna" data={[{label:'2023',value:14},{label:'2024',value:null},{label:'2025',value:22},{label:'2026',value:25}]} coverage={partial}/></div><DataTable caption="Parlamentares de exemplo" columns={columns} rows={rows} rowKey={r=>r.id} coverage={available} page={1} pageCount={2} pageHref={p=>`/design-system?pagina=${p}`}/><DataTable caption="Estado vazio" columns={columns} rows={[]} rowKey={r=>r.id} coverage={unavailable}/></section>
<section className="space-y-8"><SectionHeader number={4} id="navegacao" title="Fontes e comparação"/><OfficialSourcesCard sources={sources}/><ComparisonBar source="senado" options={[{id:'1',label:'Parlamentar A',source:'senado'},{id:'2',label:'Parlamentar B',source:'senado'},{id:'3',label:'Parlamentar C',source:'senado'}]}/></section></div><OfficialSourcesStrip sources={sources}/></main>}
