import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { DatabaseSync } from 'node:sqlite';
import { startRun, failRun, publishActivity } from '@senadotracker/db';
import type { LegislativeAppointment, Proposal, ProposalAuthor, Source } from '@senadotracker/domain';
import { saveRaw } from './raw.ts';

const idFromUri=(value:unknown)=>typeof value==='string'?value.split('/').filter(Boolean).at(-1)??null:null;
const text=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null;
async function evidence(db:DatabaseSync,run:string,rawDir:string,path:string,url:string){const bytes=await readFile(path);const rawId=await saveRaw(db,run,rawDir,{url,fetchedAt:new Date().toISOString(),status:200,contentType:'application/json',bytes});return{rawId,data:JSON.parse(bytes.toString('utf8').replace(/^\uFEFF/,'')) as any}}

export async function collectActivity(db:DatabaseSync,source:Source,dataDir:string,progress:(s:string)=>void=()=>{}){
 const run=startRun(db,source);try{
  const proposals:Proposal[]=[];const authors:ProposalAuthor[]=[];const appointments:LegislativeAppointment[]=[];
  if(source==='camara'){
   const p=await evidence(db,run,resolve(dataDir,'raw'),resolve(dataDir,'research/camara-proposicoes-2026.json'),'https://dadosabertos.camara.leg.br/arquivos/proposicoes/json/proposicoes-2026.json');
   const a=await evidence(db,run,resolve(dataDir,'raw'),resolve(dataDir,'research/camara-autores-2026.json'),'https://dadosabertos.camara.leg.br/arquivos/proposicoesAutores/json/proposicoesAutores-2026.json');
   const o=await evidence(db,run,resolve(dataDir,'raw'),resolve(dataDir,'research/camara-orgaos-membros-L57.json'),'https://dadosabertos.camara.leg.br/arquivos/orgaosDeputados/json/orgaosDeputados-L57.json');
   for(const x of p.data.dados){const status=x.ultimoStatus??{};proposals.push({source,externalId:String(x.id),type:String(x.siglaTipo??x.descricaoTipo??''),number:x.numero==null?null:String(x.numero),year:Number(x.ano)||null,label:`${x.siglaTipo} ${x.numero}/${x.ano}`,summary:text(x.ementa),presentedAt:text(x.dataApresentacao),status:text(status.descricaoSituacao),officialUrl:`https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=${x.id}`,rawId:p.rawId});const relator=idFromUri(status.uriRelator);if(relator)appointments.push({source,externalId:`relator:${x.id}:${relator}:${status.sequencia??''}`,personExternalId:relator,kind:'rapporteurship',bodyId:status.codOrgao==null?null:String(status.codOrgao),bodyLabel:text(status.siglaOrgao),role:'Relator',start:text(status.data)?.slice(0,10)??null,end:null,status:text(status.descricaoSituacao),proposalId:String(x.id),officialUrl:`https://dadosabertos.camara.leg.br/api/v2/proposicoes/${x.id}`,rawId:p.rawId})}
   for(const x of a.data.dados)authors.push({proposalId:String(x.idProposicao),externalId:idFromUri(x.uriAutor),name:String(x.nomeAutor??'Autor não identificado'),party:text(x.siglaPartidoAutor),uf:text(x.siglaUFAutor),kind:String(x.tipoAutor??'não informado'),primary:x.proponente==null?null:String(x.proponente).toLowerCase()==='sim',order:Number.isFinite(Number(x.ordemAssinatura))?Number(x.ordemAssinatura):null,rawId:a.rawId});
   for(const x of o.data.dados){const person=idFromUri(x.uriDeputado);if(person)appointments.push({source,externalId:`orgao:${idFromUri(x.uriOrgao)}:${person}:${x.dataInicio??''}:${x.cargo??''}`,personExternalId:person,kind:String(x.cargo??'').toLowerCase().includes('presidente')?'office':'commission',bodyId:idFromUri(x.uriOrgao),bodyLabel:text(x.siglaOrgao)??text(x.nomeOrgao),role:String(x.cargo??'Membro'),start:text(x.dataInicio),end:text(x.dataFim),status:x.dataFim?'encerrado':'atual',proposalId:null,officialUrl:String(x.uriOrgao??'https://dadosabertos.camara.leg.br/api/v2/orgaos'),rawId:o.rawId})}
  }else{
   const au=await evidence(db,run,resolve(dataDir,'raw'),resolve(dataDir,'research/e-2.json'),'https://legis.senado.leg.br/dadosabertos/senador/5672/autorias.json');const re=await evidence(db,run,resolve(dataDir,'raw'),resolve(dataDir,'research/e-3.json'),'https://legis.senado.leg.br/dadosabertos/senador/5672/relatorias.json');const co=await evidence(db,run,resolve(dataDir,'raw'),resolve(dataDir,'research/e-4.json'),'https://legis.senado.leg.br/dadosabertos/senador/5672/comissoes.json');const ca=await evidence(db,run,resolve(dataDir,'raw'),resolve(dataDir,'research/e-5.json'),'https://legis.senado.leg.br/dadosabertos/senador/5672/cargos.json');
   const map=new Map<string,Proposal>();const add=(m:any,rawId:string)=>{const x=m.Materia;const id=String(x.Codigo);if(!map.has(id))map.set(id,{source,externalId:id,type:String(x.Sigla??''),number:text(x.Numero),year:Number(x.Ano)||null,label:String(x.DescricaoIdentificacao??`${x.Sigla} ${x.Numero}/${x.Ano}`),summary:text(x.Ementa),presentedAt:text(x.Data),status:null,officialUrl:`https://www25.senado.leg.br/web/atividade/materias/-/materia/${id}`,rawId})};
   for(const x of au.data.MateriasAutoriaParlamentar.Parlamentar.Autorias.Autoria){add(x,au.rawId);authors.push({proposalId:String(x.Materia.Codigo),externalId:'5672',name:'Alan Rick',party:null,uf:null,kind:'Parlamentar',primary:String(x.IndicadorAutorPrincipal).toLowerCase()==='sim',order:null,rawId:au.rawId})}
   for(const x of re.data.MateriasRelatoriaParlamentar.Parlamentar.Relatorias.Relatoria){add(x,re.rawId);appointments.push({source,externalId:`relator:${x.Materia.Codigo}:${x.DataDesignacao}:${x.Comissao?.Codigo??''}`,personExternalId:'5672',kind:'rapporteurship',bodyId:text(x.Comissao?.Codigo),bodyLabel:text(x.Comissao?.Sigla),role:String(x.DescricaoTipoRelator??'Relator'),start:text(x.DataDesignacao),end:text(x.DataDestituicao),status:text(x.DescricaoMotivoDestituicao),proposalId:String(x.Materia.Codigo),officialUrl:`https://www25.senado.leg.br/web/atividade/materias/-/materia/${x.Materia.Codigo}`,rawId:re.rawId})}
   const memberships=[...(co.data.MembroComissaoParlamentar.Parlamentar.MembroComissoes.Comissao??[])];for(const x of memberships){const i=x.IdentificacaoComissao;appointments.push({source,externalId:`comissao:${i.CodigoComissao}:${x.DataInicio}:${x.DescricaoParticipacao}`,personExternalId:'5672',kind:'commission',bodyId:String(i.CodigoComissao),bodyLabel:text(i.SiglaComissao)??text(i.NomeComissao),role:String(x.DescricaoParticipacao??'Membro'),start:text(x.DataInicio),end:text(x.DataFim),status:x.DataFim?'encerrado':'atual',proposalId:null,officialUrl:'https://legis.senado.leg.br/dadosabertos/senador/5672/comissoes',rawId:co.rawId})}
   for(const x of ca.data.CargoParlamentar.Parlamentar.Cargos.Cargo??[]){const i=x.IdentificacaoComissao;appointments.push({source,externalId:`cargo:${i.CodigoComissao}:${x.CodigoCargo}:${x.DataInicio}`,personExternalId:'5672',kind:'office',bodyId:String(i.CodigoComissao),bodyLabel:text(i.SiglaComissao)??text(i.NomeComissao),role:String(x.DescricaoCargo??'Cargo'),start:text(x.DataInicio),end:text(x.DataFim),status:x.DataFim?'encerrado':'atual',proposalId:null,officialUrl:'https://legis.senado.leg.br/dadosabertos/senador/5672/cargos',rawId:ca.rawId})}proposals.push(...map.values());
  }
  const proposalIds=new Set(proposals.map(item=>item.externalId));
  for(let index=authors.length-1;index>=0;index--)if(!proposalIds.has(authors[index]!.proposalId))authors.splice(index,1);
  appointments.forEach((item,index)=>item.externalId=`${item.externalId}:${index}`);
  publishActivity(db,run,source,source==='camara'?'2026-L57':'amostra-5672',proposals,authors,appointments,[]);progress(`${source}: ${proposals.length} proposições, ${authors.length} autorias, ${appointments.length} atuações, 0 vínculos normativos explícitos`);return{runId:run,proposals:proposals.length,authors:authors.length,appointments:appointments.length};
 }catch(e){failRun(db,run,e instanceof Error?e.message:String(e));throw e}
}
