import { readFile, writeFile } from 'node:fs/promises';
import type { DatabaseSync } from 'node:sqlite';
import { decimalCents, searchText, type ExpandedCost } from '@senadotracker/domain';
import { failRun, listPublished, publishExpandedCosts, startRun } from '@senadotracker/db';
import { saveRawFile } from './raw.ts';

function csvRows(input:string){const rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<input.length;i++){const c=input[i]!;if(c==='"'){if(quoted&&input[i+1]==='"'){field+='"';i++}else if(quoted)quoted=false;else if(!field)quoted=true;else field+='"'}else if(c===';'&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&input[i+1]==='\n')i++;row.push(field);field='';if(row.some(Boolean))rows.push(row);row=[]}else field+=c}if(quoted)throw new Error('CSV de remuneração com aspas não terminadas');if(field||row.length){row.push(field);rows.push(row)}return rows}
const headers=['VÍNCULO','CATEGORIA','CARGO','REFERÊNCIA CARGO','SÍMBOLO FUNÇÃO','ANO EXERCÍCIO','LOTAÇÃO EXERCÍCIO','TIPO FOLHA','REMUN_BASICA','VANT_PESSOAIS','FUNC_COMISSIONADA','GRAT_NATALINA','HORAS_EXTRAS','OUTRAS_EVENTUAIS','ABONO_PERMANENCIA','REVERSAO_TETO_CONST','IMPOSTO_RENDA','PREVIDÊNCIA','FALTAS','REM_LIQUIDA','DIÁRIAS','AUXÍLIOS','VANT_INDENIZATORIAS'] as const;
const officeName=(lotacao:string)=>lotacao.match(/^Gabinete d[oa] Senador(?:a)? (.+)$/i)?.[1]?.trim()??null;
const earningColumns=['REMUN_BASICA','VANT_PESSOAIS','FUNC_COMISSIONADA','GRAT_NATALINA','HORAS_EXTRAS','OUTRAS_EVENTUAIS','ABONO_PERMANENCIA','REVERSAO_TETO_CONST','FALTAS'] as const;
const sum=(row:Record<string,string>,columns:readonly string[])=>columns.reduce((n,c)=>n+decimalCents(row[c]||0),0);
export function parseSenateCabinetPayroll(bytes:Uint8Array,rawId:string,competence:string,identityByName:Map<string,string>){
  if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test(competence))throw new Error('Competência obrigatória e inválida');const rows=csvRows(new TextDecoder('windows-1252').decode(bytes));if(rows.length<3||rows[0]?.[0]!=='ÚLTIMA ATUALIZAÇÃO'||rows[1]?.length!==headers.length||!rows[1]!.every((h,i)=>h===headers[i]))throw new Error('Cabeçalho de remuneração do Senado inesperado');
  const resolveOffice=(office:string)=>{const normalized=searchText(office),exact=identityByName.get(normalized);if(exact)return exact;const candidates=[...identityByName].filter(([known])=>normalized.includes(known)||known.includes(normalized)).map(([,id])=>id);return new Set(candidates).size===1?candidates[0]!:null};
  const grouped=new Map<string,{externalId:string;gross:number;allowances:number;daily:number;indemnities:number;normal:number;rows:number;lotacao:string}>(),unmatched=new Set<string>(),types=new Map<string,number>(),duplicates=new Map<string,number>();let cabinetRows=0,otherUnits=0;
  for(let i=2;i<rows.length;i++){const values=rows[i]!;if(values.length!==headers.length)throw new Error(`Linha ${i+1} da remuneração possui ${values.length} colunas`);const signature=values.join('\u001f');duplicates.set(signature,(duplicates.get(signature)??0)+1);const r=Object.fromEntries(headers.map((h,j)=>[h,values[j]??''])),type=r['TIPO FOLHA']||'Não informado';types.set(type,(types.get(type)??0)+1);const office=officeName(r['LOTAÇÃO EXERCÍCIO']??'');if(!office){otherUnits++;continue}cabinetRows++;const externalId=resolveOffice(office);if(!externalId){unmatched.add(r['LOTAÇÃO EXERCÍCIO']!);continue}const current=grouped.get(externalId)??{externalId,gross:0,allowances:0,daily:0,indemnities:0,normal:0,rows:0,lotacao:r['LOTAÇÃO EXERCÍCIO']!};current.gross+=sum(r,earningColumns);current.allowances+=decimalCents(r['AUXÍLIOS']||0);current.daily+=decimalCents(r['DIÁRIAS']||0);current.indemnities+=decimalCents(r['VANT_INDENIZATORIAS']||0);current.rows++;if(type==='Normal')current.normal++;grouped.set(externalId,current)}
  const costs:ExpandedCost[]=[];for(const g of grouped.values()){const base={source:'senado' as const,externalId:g.externalId,competence,overlapGroup:'senado-folha-gabinete',availability:'partial' as const,rawId};costs.push({...base,rubric:'cabinet_payroll_gross',nature:'expense',valueCents:g.gross,label:'Proventos brutos publicados da equipe, sem encargos patronais',count:g.rows},{...base,rubric:'cabinet_allowances',nature:'expense',valueCents:g.allowances,label:'Auxílios publicados da equipe',count:g.rows},{...base,rubric:'cabinet_daily_allowances',nature:'expense',valueCents:g.daily,label:'Diárias publicadas da equipe',count:g.rows},{...base,rubric:'cabinet_indemnities',nature:'expense',valueCents:g.indemnities,label:'Vantagens indenizatórias publicadas da equipe',count:g.rows},{...base,rubric:'cabinet_staff_normal_rows',nature:'headcount',valueCents:null,label:'Linhas de folha normal vinculadas ao gabinete',count:g.normal})}
  return{costs,matchedOffices:grouped.size,unmatched:[...unmatched].sort(),report:{inputRows:rows.length-2,cabinetRows,otherUnits,payrollTypes:Object.fromEntries(types),repeatedSignatures:[...duplicates.values()].filter(n=>n>1).length,personLinkAvailability:'unavailable' as const,personLinkNote:'O CSV não contém nome, matrícula ou fcodigo; remuneração não é atribuída individualmente.'}}
}
export async function importSenateCabinetPayroll(db:DatabaseSync,file:string,competence:string,rawDirectory:string,options:{dryRun?:boolean;reportFile?:string}={}){if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test(competence))throw new Error('Competência inválida');const year=Number(competence.slice(0,4)),profiles=listPublished(db,{source:'senado',pageSize:100}).items,names=new Map<string,string>();for(const p of profiles)for(const name of [p.name,p.fullName].filter(Boolean) as string[]){const key=searchText(name);if(names.has(key)&&names.get(key)!==p.externalId)names.delete(key);else names.set(key,p.externalId)}let runId:string|null=null;try{if(!options.dryRun)runId=startRun(db,'senado');const bytes=await readFile(file),url=`https://www.senado.leg.br/transparencia/LAI/secrh/SF_ConsultaRemuneracaoServidoresParlamentares_${competence.replace('-','')}.csv`,rawId=options.dryRun?'dry:payroll':await saveRawFile(db,runId!,rawDirectory,file,{url,fetchedAt:new Date().toISOString(),status:200,contentType:'text/csv; charset=windows-1252'}),parsed=parseSenateCabinetPayroll(bytes,rawId,competence,names),result={runId,dryRun:Boolean(options.dryRun),competence,matchedOffices:parsed.matchedOffices,unmatched:parsed.unmatched,costRecords:parsed.costs.length,...parsed.report,published:false};if(!options.dryRun){publishExpandedCosts(db,runId!,'senado',year,'partial',`Competência ${competence}; ${parsed.matchedOffices} gabinetes vinculados. O CSV não contém identificador individual; folhas extraordinárias são mantidas nas rubricas e nos diagnósticos.`,parsed.costs);result.published=true}if(options.reportFile)await writeFile(options.reportFile,JSON.stringify(result,null,2)+'\n');return result}catch(error){if(runId)failRun(db,runId,error instanceof Error?error.message:String(error));throw error}}
