import { mkdir,readFile,stat,writeFile } from 'node:fs/promises';
import { dirname,resolve } from 'node:path';
import type { DatabaseSync } from 'node:sqlite';
import type { LegislativeComplement } from '@senadotracker/domain';
import { failRun,publishComplement,startRun } from '@senadotracker/db';
import { saveRaw } from './raw.ts';

type Json=Record<string,unknown>;
const api='https://dadosabertos.camara.leg.br/api/v2';
const text=(value:unknown)=>value===null||value===undefined||String(value).trim()===''?null:String(value).trim();
const idFromUri=(value:unknown)=>/\/(\d+)\/?$/.exec(String(value??''))?.[1]??null;
export function parseCamaraMovements(id:string,data:unknown,rawId:string):LegislativeComplement[]{const items=Array.isArray((data as {dados?:unknown})?.dados)?(data as {dados:Json[]}).dados:[];return items.map(item=>({source:'camara',externalKey:`movement:${id}:${item.sequencia}`,kind:'movement',personExternalId:idFromUri(item.uriUltimoRelator),proposalId:id,deliberationId:null,bodyId:idFromUri(item.uriOrgao),occurredAt:text(item.dataHora),label:text(item.descricaoTramitacao)??'Movimentação',value:JSON.stringify({code:text(item.codTipoTramitacao),situationCode:text(item.codSituacao),situation:text(item.descricaoSituacao),dispatch:text(item.despacho),body:text(item.siglaOrgao),url:text(item.url)}),officialUrl:text(item.url)??`${api}/proposicoes/${id}/tramitacoes`,rawId}))}

async function cachedPage(url:string,file:string){try{const [bytes,info]=await Promise.all([readFile(file),stat(file)]);return{bytes:new Uint8Array(bytes),fetchedAt:info.mtime.toISOString(),cached:true}}catch{}const response=await fetch(url,{signal:AbortSignal.timeout(15_000),headers:{Accept:'application/json','User-Agent':'Civica/0.1 (dados publicos legislativos)'}});if(!response.ok)throw new Error(`HTTP ${response.status}: ${url}`);const bytes=new Uint8Array(await response.arrayBuffer());await mkdir(dirname(file),{recursive:true});await writeFile(file,bytes);return{bytes,fetchedAt:new Date().toISOString(),cached:false}}
function nextUrl(data:Json){const links=Array.isArray(data.links)?data.links as Json[]:[];return text(links.find(link=>link.rel==='next')?.href)}
async function fetchOne(id:string,cacheDirectory:string){let url=`${api}/proposicoes/${id}/tramitacoes`,page=1;const pages:Array<{url:string;bytes:Uint8Array;fetchedAt:string;cached:boolean;data:Json}>=[];while(url){const loaded=await cachedPage(url,resolve(cacheDirectory,id,`${page}.json`)),data=JSON.parse(new TextDecoder().decode(loaded.bytes)) as Json;pages.push({url,bytes:loaded.bytes,fetchedAt:loaded.fetchedAt,cached:loaded.cached,data});url=nextUrl(data)??'';page++}return{id,pages}}
export function camaraMovementCandidates(db:DatabaseSync,year:number,types:string[]){const marks=types.map(()=>'?').join(',');return db.prepare(`SELECT DISTINCT p.external_id id FROM proposals p JOIN active_activity_publications a ON a.batch_id=p.batch_id WHERE a.source='camara' AND CAST(json_extract(p.payload,'$.year') AS INTEGER)=? AND upper(json_extract(p.payload,'$.type')) IN (${marks}) AND (search_text(COALESCE(json_extract(p.payload,'$.status'),'')) LIKE '%finaliz%' OR search_text(COALESCE(json_extract(p.payload,'$.status'),'')) LIKE '%arquiv%' OR search_text(COALESCE(json_extract(p.payload,'$.status'),'')) LIKE '%retirad%' OR search_text(COALESCE(json_extract(p.payload,'$.status'),'')) LIKE '%transform%norma%' OR search_text(COALESCE(json_extract(p.payload,'$.status'),'')) LIKE '%remessa%arquivo%') ORDER BY p.external_id`).all(year,...types).map(row=>String(row.id))}
export async function collectCamaraPropositionMovements(db:DatabaseSync,options:{year:number;types?:string[];ids?:string[];limit?:number;rawDirectory:string;cacheDirectory:string;progress?:(message:string)=>void}){const types=(options.types?.length?options.types:['REQ','RIC','INC','DOC','EMC','PL']).map(value=>value.toUpperCase()),all=options.ids?.length?[...new Set(options.ids)]:camaraMovementCandidates(db,options.year,types),ids=options.limit?all.slice(0,options.limit):all;if(!ids.length)return{requested:0,published:0,failures:[]};const run=startRun(db,'camara',Date.now(),900_000);try{const records:LegislativeComplement[]=[],failures:Array<{id:string;error:string}>=[];let cachedPages=0;for(let offset=0;offset<ids.length;offset+=6){const chunk=ids.slice(offset,offset+6),settled=await Promise.allSettled(chunk.map(id=>fetchOne(id,options.cacheDirectory)));for(let index=0;index<settled.length;index++){const result=settled[index]!,id=chunk[index]!;if(result.status==='rejected'){failures.push({id,error:result.reason instanceof Error?result.reason.message:String(result.reason)});continue}for(const page of result.value.pages){if(page.cached)cachedPages++;const rawId=await saveRaw(db,run,options.rawDirectory,{url:page.url,fetchedAt:page.fetchedAt,status:200,contentType:'application/json',bytes:page.bytes});records.push(...parseCamaraMovements(id,page.data,rawId))}}options.progress?.(`${Math.min(offset+chunk.length,ids.length)}/${ids.length} proposições`)}const unique=[...new Map(records.map(item=>[item.externalKey,item])).values()];if(!unique.length)throw new Error(`Nenhuma tramitação oficial foi coletada${failures.length?`: ${failures.map(item=>`${item.id}: ${item.error}`).join('; ')}`:''}`);if(failures.length)throw new Error(`Coleta incompleta; lote anterior preservado. ${failures.slice(0,10).map(item=>`${item.id}: ${item.error}`).join('; ')}`);const selection=options.ids?.length?'ids':options.limit?`limit-${options.limit}`:types.join('-').toLowerCase();publishComplement(db,run,'camara',`camara-proposition-movements-${options.year}-${selection}`,unique,{year:options.year,types,requested:ids.length,published:new Set(unique.map(item=>item.proposalId)).size,records:unique.length,cachedPages,failures});return{requested:ids.length,published:new Set(unique.map(item=>item.proposalId)).size,records:unique.length,cachedPages,failures}}catch(error){failRun(db,run,error instanceof Error?error.message:String(error));throw error}}
