import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { DatabaseSync } from 'node:sqlite';
import { failRun, publishComplement, startRun } from '@senadotracker/db';
import type { LegislativeComplement } from '@senadotracker/domain';
import { saveRaw } from './raw.ts';

type Json=Record<string,unknown>;
type ResponseData={bytes:Uint8Array;url:string;fetchedAt:string;status:number;contentType:string};
const text=(value:unknown)=>value===null||value===undefined?'':String(value).trim();
const object=(value:unknown):Json=>value&&typeof value==='object'&&!Array.isArray(value)?value as Json:{};
const list=(value:unknown):Json[]=>Array.isArray(value)?value.filter((item):item is Json=>Boolean(item)&&typeof item==='object'):[];
const annualUrl=(year:number)=>`https://dadosabertos.camara.leg.br/arquivos/eventos/json/eventos-${year}.json`;
const agendaUrl=(id:string)=>`https://dadosabertos.camara.leg.br/api/v2/eventos/${id}/pauta`;

async function load(url:string,file:string):Promise<ResponseData>{
  try{return{bytes:new Uint8Array(await readFile(file)),url,fetchedAt:new Date().toISOString(),status:200,contentType:'application/json'}}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error}
  let last:unknown;for(let attempt=1;attempt<=3;attempt++)try{const response=await fetch(url,{signal:AbortSignal.timeout(25_000),headers:{Accept:'application/json','User-Agent':'Civica/0.1 (dados publicos legislativos)'}}),bytes=new Uint8Array(await response.arrayBuffer());if(!response.ok)throw new Error(`HTTP ${response.status}`);JSON.parse(new TextDecoder().decode(bytes));await mkdir(resolve(file,'..'),{recursive:true});await writeFile(file,bytes);return{bytes,url,fetchedAt:new Date().toISOString(),status:response.status,contentType:response.headers.get('content-type')??'application/json'}}catch(error){last=error;if(attempt<3)await new Promise(done=>setTimeout(done,attempt*400))}throw new Error(`${url}: ${last instanceof Error?last.message:String(last)}`)
}

export function parseCamaraAgenda(document:unknown,rawId:string,event:{id:string;date:string;scope:'plenario'|'comissao'}):LegislativeComplement[]{
  return list(object(document).dados).flatMap((item,index)=>{const proposal=object(item.proposicao_),id=text(proposal.id)||text(item.idProposicao);if(!/^\d+$/.test(id))return[];const label=[text(proposal.siglaTipo),text(proposal.numero),text(proposal.ano)].filter(Boolean).join(' ')||`Proposição ${id}`,order=text(item.ordem)||String(index+1);return[{source:'camara',externalKey:`event-agenda:${event.id}:${order}:${id}:${index}`,kind:'agenda_item',personExternalId:null,proposalId:id,deliberationId:null,bodyId:null,occurredAt:event.date,label,value:JSON.stringify({eventId:event.id,scope:event.scope,order:Number(order)||null,topic:text(item.topico)||null,regime:text(item.regime)||null}),officialUrl:`https://dadosabertos.camara.leg.br/api/v2/eventos/${event.id}/pauta`,rawId}]});
}

export async function collectCamaraAgenda(db:DatabaseSync,options:{year:number;rawDirectory:string;cacheDirectory:string;dryRun?:boolean;progress?:(message:string)=>void;concurrency?:number}){
  if(!Number.isInteger(options.year)||options.year<2001||options.year>2100)throw new Error('Ano de pauta inválido');const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date()),to=today<`${options.year}-12-31`?today:`${options.year}-12-31`,from=`${options.year}-01-01`;let runId:string|null=null;
  try{if(!options.dryRun)runId=startRun(db,'camara');const annual=await load(annualUrl(options.year),resolve(options.cacheDirectory,`${options.year}-events.json`));if(!options.dryRun)await saveRaw(db,runId!,options.rawDirectory,annual);const events=list(object(JSON.parse(new TextDecoder().decode(annual.bytes))).dados).flatMap(item=>{const date=text(item.dataHoraInicio).slice(0,10),kind=text(item.descricaoTipo);if(date<from||date>to||!['Sessão Deliberativa','Reunião Deliberativa','Audiência Pública e Deliberação'].includes(kind))return[];return[{id:text(item.id),date,scope:kind==='Sessão Deliberativa'?'plenario' as const:'comissao' as const}]});const records:LegislativeComplement[]=[],failures:Array<{id:string;error:string}>=[],concurrency=Math.max(1,Math.min(12,options.concurrency??8));let cursor=0,done=0;const worker=async()=>{while(cursor<events.length){const event=events[cursor++]!;try{const response=await load(agendaUrl(event.id),resolve(options.cacheDirectory,String(options.year),`${event.id}.json`)),rawId=options.dryRun?`dry:camara-agenda:${event.id}`:await saveRaw(db,runId!,options.rawDirectory,response);records.push(...parseCamaraAgenda(JSON.parse(new TextDecoder().decode(response.bytes)),rawId,event))}catch(error){failures.push({id:event.id,error:error instanceof Error?error.message:String(error)})}done++;if(done%50===0||done===events.length)options.progress?.(`Câmara pautas: ${done}/${events.length} eventos`)}};await Promise.all(Array.from({length:Math.min(concurrency,events.length)},worker));const unique=[...new Map(records.map(record=>[record.externalKey,record])).values()],matters=new Set(unique.map(record=>record.proposalId)).size,plenaryMatters=new Set(unique.filter(record=>JSON.parse(record.value!).scope==='plenario').map(record=>record.proposalId)).size,commissionMatters=new Set(unique.filter(record=>JSON.parse(record.value!).scope==='comissao').map(record=>record.proposalId)).size,result={year:options.year,from,to,events:events.length,eventsCovered:events.length-failures.length,items:unique.length,matters,plenaryMatters,commissionMatters,failures,published:false};if(!options.dryRun){publishComplement(db,runId!,'camara',`camara-agenda-${options.year}`,unique,{...result,source:'GET /eventos/{id}/pauta'});result.published=true}return result}catch(error){if(runId)failRun(db,runId,error instanceof Error?error.message:String(error));throw error}
}
