import { createHash } from 'node:crypto';
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import type { DatabaseSync } from 'node:sqlite';
import type { CabinetMonthlyBudget, FunctionalStaffAssignment, Profile } from '@senadotracker/domain';
import { decimalCents, searchText } from '@senadotracker/domain';
import { failRun, listPublished, publishCabinetBudgets, publishStaffSnapshot, startRun } from '@senadotracker/db';
import { saveRaw, saveRawFile } from './raw.ts';

const staffUrl='https://dadosabertos.camara.leg.br/arquivos/funcionarios/csv/funcionarios.csv';
export const staffHeaders=['ponto','codGrupo','grupo','nome','cargo','lotacao','atoNomeacao','dataNomeacao','dataInicioHistorico','dataPubNomeacao','funcao','uriLotacao'] as const;
const clean=(value:string)=>value.trim();
const civil=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value.trim())?value.trim():null;

function csvRecords(text:string){const records:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i]!;if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"'&&!field)quoted=true;else if(c===';'){row.push(field);field=''}else if(c==='\n'){if(field.endsWith('\r'))field=field.slice(0,-1);row.push(field);field='';if(row.some(Boolean))records.push(row);row=[]}else field+=c}if(quoted)throw new Error('CSV de funcionários com aspas não terminadas');if(field||row.length){row.push(field);records.push(row)}return records}
export interface StaffReconciliation{input:number;confirmed:number;pending:number;ambiguous:number;ignoredUnits:number;examples:{pending:string[];ambiguous:string[];ignored:string[]}}
export function parseCamaraStaff(bytes:Uint8Array,rawId:string,observedAt:string,validDeputies:Set<string>):{rows:FunctionalStaffAssignment[];report:StaffReconciliation}{
  const records=csvRecords(new TextDecoder('utf-8',{fatal:true}).decode(bytes).replace(/^\uFEFF/,'')),header=records.shift();if(!header||header.length!==staffHeaders.length||!header.every((x,i)=>x===staffHeaders[i]))throw new Error('Cabeçalho de funcionários da Câmara divergente');
  const seen=new Map<string,number>(),rows:FunctionalStaffAssignment[]=[];let confirmed=0,pending=0,ambiguous=0,ignoredUnits=0;const examples={pending:[] as string[],ambiguous:[] as string[],ignored:[] as string[]};
  for(const values of records){if(values.length!==header.length)throw new Error(`Linha funcional com ${values.length} colunas; esperado ${header.length}`);const r=Object.fromEntries(header.map((h,i)=>[h,values[i]??'']));const point=clean(r.ponto!),base=`${point}:${clean(r.codGrupo!)}:${clean(r.nome!)}`,occurrence=(seen.get(base)??0)+1;seen.set(base,occurrence);const match=/\/deputados\/(\d+)\/?$/i.exec(clean(r.uriLotacao!)),id=match?.[1]??null,isStaff=searchText(r.grupo!)!=='parlamentar',isOffice=isStaff&&(Boolean(id)||/^GAB\.\s+(?:\d+\/\d+|EDP\/\d+)\s*-/i.test(clean(r.lotacao!)));let externalId:string|null=null,status:FunctionalStaffAssignment['matchStatus']='rejected',evidence:string[]=[];
    if(isOffice&&id&&validDeputies.has(id)){externalId=id;status='confirmed';evidence=['uriLotacao/deputados/{id}','ID presente no cadastro ativo da Câmara'];confirmed++}else if(isOffice&&id){status='pending';pending++;if(examples.pending.length<10)examples.pending.push(`${r.lotacao} -> ${id}`)}else if(isOffice){status='ambiguous';ambiguous++;if(examples.ambiguous.length<10)examples.ambiguous.push(clean(r.lotacao!))}else{ignoredUnits++;if(examples.ignored.length<10)examples.ignored.push(clean(r.lotacao!))}
    rows.push({source:'camara',staffKey:`${base}:${occurrence}`,functionalId:point||null,name:clean(r.nome!),relationship:clean(r.grupo!),position:clean(r.cargo!)||null,role:clean(r.funcao!)||null,unitId:id,unitLabel:clean(r.lotacao!),appointedAt:civil(r.dataNomeacao!),startedAt:civil(r.dataInicioHistorico!),endedAt:null,observedAt,externalId,matchStatus:status,matchEvidence:evidence,rawId});
  }return{rows,report:{input:records.length,confirmed,pending,ambiguous,ignoredUnits,examples}}
}

async function profiles(db:DatabaseSync){const items:(Profile&{personId:string})[]=[];let page=1,total=0;do{const result=listPublished(db,{source:'camara',page,pageSize:100});items.push(...result.items as (Profile&{personId:string})[]);total=result.total;page++}while(items.length<total);return items}
async function download(url:string,accept:string){const response=await fetch(url,{headers:{Accept:accept,'User-Agent':'SenadoTracker/0.1 (official-data-research)'}}),bytes=new Uint8Array(await response.arrayBuffer());if(response.status!==200)throw new Error(`HTTP ${response.status} em ${new URL(url).pathname}`);return{bytes,contentType:response.headers.get('content-type')??'application/octet-stream',fetchedAt:new Date().toISOString()}}
export async function collectCamaraStaff(db:DatabaseSync,options:{rawDirectory:string;file?:string;dryRun?:boolean;reportFile?:string}){let runId:string|null=null;try{const source=options.file?{bytes:new Uint8Array(await readFile(options.file)),contentType:'text/csv; charset=utf-8',fetchedAt:new Date().toISOString()}:await download(staffUrl,'text/csv');if(!options.dryRun)runId=startRun(db,'camara');const rawId=options.dryRun?'dry:staff':options.file?await saveRawFile(db,runId!,options.rawDirectory,options.file,{url:staffUrl,fetchedAt:source.fetchedAt,status:200,contentType:source.contentType}):await saveRaw(db,runId!,options.rawDirectory,{url:staffUrl,fetchedAt:source.fetchedAt,status:200,contentType:source.contentType,bytes:source.bytes});const current=await profiles(db),parsed=parseCamaraStaff(source.bytes,rawId,source.fetchedAt,new Set(current.map(x=>x.externalId)));const availability=parsed.report.pending||parsed.report.ambiguous?'partial':'available',result={dryRun:Boolean(options.dryRun),runId,observedAt:source.fetchedAt,availability,records:parsed.rows.length,...parsed.report,published:false};if(!options.dryRun){publishStaffSnapshot(db,runId!,'camara',source.fetchedAt,availability,`Snapshot oficial da Câmara coletado em ${source.fetchedAt}; unidades não parlamentares não são atribuídas a deputados.`,parsed.rows);result.published=true}if(options.reportFile)await writeFile(options.reportFile,JSON.stringify(result,null,2)+'\n');return result}catch(error){if(runId)failRun(db,runId,error instanceof Error?error.message:String(error));throw error}}

const entities=(s:string)=>s.replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
export function parseCamaraBudgetHtml(html:string,externalId:string,year:number,rawId:string):CabinetMonthlyBudget[]{const plain=entities(html);if(!new RegExp(`Verba de gabinete em\\s+${year}`,'i').test(plain)||!(/Valor dispon.vel \(R\$\)/i.test(plain)&&/Valor gasto \(R\$\)/i.test(plain)))throw new Error(`HTML de verba alterado ou indisponível para ${externalId}/${year}`);const tbody=/<tbody[^>]*>([\s\S]*?)<\/tbody>/i.exec(html)?.[1];if(!tbody)throw new Error(`Tabela mensal ausente para ${externalId}/${year}`);const rows:CabinetMonthlyBudget[]=[];for(const match of tbody.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const cells=[...match[1]!.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>entities(x[1]!));if(cells.length!==3)continue;const month=Number(cells[0]);if(!Number.isInteger(month)||month<1||month>12)throw new Error(`Mês inválido na verba de ${externalId}`);rows.push({source:'camara',externalId,year,month,availableCents:decimalCents(cells[1]!),spentCents:decimalCents(cells[2]!),rawId})}if(!rows.length||new Set(rows.map(x=>x.month)).size!==rows.length)throw new Error(`Série mensal vazia ou duplicada para ${externalId}/${year}`);return rows}

async function cachedHtml(url:string,cacheFile:string){try{const [bytes,info]=await Promise.all([readFile(cacheFile),stat(cacheFile)]);return{bytes:new Uint8Array(bytes),contentType:'text/html; charset=utf-8',fetchedAt:info.mtime.toISOString(),cached:true}}catch{const response=await download(url,'text/html');await mkdir(dirname(cacheFile),{recursive:true});await writeFile(cacheFile,response.bytes);return{...response,cached:false}}}
export async function collectCamaraBudgets(db:DatabaseSync,options:{year:number;rawDirectory:string;cacheDirectory:string;ids?:string[];dryRun?:boolean;reportFile?:string;delayMs?:number;progress?:(message:string)=>void}){if(!Number.isInteger(options.year)||options.year<2008||options.year>2100)throw new Error('Ano de verba inválido');const current=await profiles(db),allowed=new Set(current.map(x=>x.externalId)),ids=options.ids?.length?options.ids:current.map(x=>x.externalId);if(ids.some(id=>!allowed.has(id)))throw new Error('Recorte contém deputado fora do cadastro ativo');let runId:string|null=null;try{if(!options.dryRun)runId=startRun(db,'camara');const rows:CabinetMonthlyBudget[]=[],failures:{externalId:string;error:string}[]=[],cacheHits:string[]=[];for(let index=0;index<ids.length;index++){const id=ids[index]!,url=`https://www.camara.leg.br/deputados/${id}/verba-gabinete?ano=${options.year}`,cacheFile=resolve(options.cacheDirectory,String(options.year),`${id}.html`);try{const response=await cachedHtml(url,cacheFile);if(response.cached)cacheHits.push(id);const rawId=options.dryRun?`dry:${id}`:await saveRaw(db,runId!,options.rawDirectory,{url,fetchedAt:response.fetchedAt,status:200,contentType:response.contentType,bytes:response.bytes});rows.push(...parseCamaraBudgetHtml(new TextDecoder('utf-8').decode(response.bytes),id,options.year,rawId))}catch(error){failures.push({externalId:id,error:error instanceof Error?error.message:String(error)})}options.progress?.(`${index+1}/${ids.length} deputados`);if(!responseFromCache(cacheHits,id)&&index<ids.length-1)await new Promise(resolve=>setTimeout(resolve,options.delayMs??180))}
    if(!rows.length)throw new Error('Nenhuma série mensal válida foi coletada');const duplicate=new Set<string>();for(const row of rows){const key=`${row.externalId}:${row.month}`;if(duplicate.has(key))throw new Error(`Mês duplicado no lote: ${key}`);duplicate.add(key)}const covered=new Set(rows.map(x=>x.externalId)).size,availability=failures.length?'partial':'available',result={year:options.year,dryRun:Boolean(options.dryRun),runId,deputiesRequested:ids.length,deputiesCovered:covered,months:rows.length,availableCents:rows.reduce((n,x)=>n+(x.availableCents??0),0),spentCents:rows.reduce((n,x)=>n+(x.spentCents??0),0),cacheHits:cacheHits.length,failures,published:false};if(!options.dryRun){publishCabinetBudgets(db,runId!,options.year,availability,`Verba mensal oficial; ${covered}/${ids.length} deputados no recorte. 13º, férias e auxílio-alimentação ficam fora desta verba conforme a Câmara.`,rows);result.published=true}if(options.reportFile)await writeFile(options.reportFile,JSON.stringify(result,null,2)+'\n');return result}catch(error){if(runId)failRun(db,runId,error instanceof Error?error.message:String(error));throw error}}
const responseFromCache=(hits:string[],id:string)=>hits[hits.length-1]===id;
