import { createReadStream } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import type { DatabaseSync } from 'node:sqlite';
import type { CampaignTransaction, Candidacy, CandidacyDetails, ElectoralAsset, Profile } from '@senadotracker/domain';
import { decimalCents, searchText } from '@senadotracker/domain';
import { failRun, listPublished, publishElection, startRun } from '@senadotracker/db';
import { saveRawFile } from './raw.ts';

export type TseRow = Record<string, string>;
export const candidateHeaders=['DT_GERACAO','HH_GERACAO','ANO_ELEICAO','CD_TIPO_ELEICAO','NM_TIPO_ELEICAO','NR_TURNO','CD_ELEICAO','DS_ELEICAO','DT_ELEICAO','TP_ABRANGENCIA','SG_UF','SG_UE','NM_UE','CD_CARGO','DS_CARGO','SQ_CANDIDATO','NR_CANDIDATO','NM_CANDIDATO','NM_URNA_CANDIDATO','NM_SOCIAL_CANDIDATO','NR_CPF_CANDIDATO','DS_EMAIL','CD_SITUACAO_CANDIDATURA','DS_SITUACAO_CANDIDATURA','TP_AGREMIACAO','NR_PARTIDO','SG_PARTIDO','NM_PARTIDO','NR_FEDERACAO','NM_FEDERACAO','SG_FEDERACAO','DS_COMPOSICAO_FEDERACAO','SQ_COLIGACAO','NM_COLIGACAO','DS_COMPOSICAO_COLIGACAO','SG_UF_NASCIMENTO','DT_NASCIMENTO','NR_TITULO_ELEITORAL_CANDIDATO','CD_GENERO','DS_GENERO','CD_GRAU_INSTRUCAO','DS_GRAU_INSTRUCAO','CD_ESTADO_CIVIL','DS_ESTADO_CIVIL','CD_COR_RACA','DS_COR_RACA','CD_OCUPACAO','DS_OCUPACAO','CD_SIT_TOT_TURNO','DS_SIT_TOT_TURNO'] as const;
export const assetHeaders=['DT_GERACAO','HH_GERACAO','ANO_ELEICAO','CD_TIPO_ELEICAO','NM_TIPO_ELEICAO','CD_ELEICAO','DS_ELEICAO','DT_ELEICAO','SG_UF','SG_UE','NM_UE','SQ_CANDIDATO','NR_ORDEM_BEM_CANDIDATO','CD_TIPO_BEM_CANDIDATO','DS_TIPO_BEM_CANDIDATO','DS_BEM_CANDIDATO','VR_BEM_CANDIDATO','DT_ULT_ATUAL_BEM_CANDIDATO','HH_ULT_ATUAL_BEM_CANDIDATO'] as const;
export const complementHeaders=['DT_GERACAO','HH_GERACAO','ANO_ELEICAO','CD_ELEICAO','SQ_CANDIDATO','CD_DETALHE_SITUACAO_CAND','DS_DETALHE_SITUACAO_CAND','CD_NACIONALIDADE','DS_NACIONALIDADE','CD_MUNICIPIO_NASCIMENTO','NM_MUNICIPIO_NASCIMENTO','NR_IDADE_DATA_POSSE','ST_QUILOMBOLA','CD_ETNIA_INDIGENA','DS_ETNIA_INDIGENA','VR_DESPESA_MAX_CAMPANHA','ST_REELEICAO','ST_DECLARAR_BENS','NR_PROTOCOLO_CANDIDATURA','NR_PROCESSO','CD_SITUACAO_CANDIDATO_PLEITO','DS_SITUACAO_CANDIDATO_PLEITO','CD_SITUACAO_CANDIDATO_URNA','DS_SITUACAO_CANDIDATO_URNA','ST_CANDIDATO_INSERIDO_URNA','NM_TIPO_DESTINACAO_VOTOS','CD_SITUACAO_CANDIDATO_TOT','DS_SITUACAO_CANDIDATO_TOT','ST_PREST_CONTAS','ST_SUBSTITUIDO','SQ_SUBSTITUIDO','SQ_ORDEM_SUPLENCIA','DT_ACEITE_CANDIDATURA','CD_SITUACAO_JULGAMENTO','DS_SITUACAO_JULGAMENTO','CD_SITUACAO_JULGAMENTO_PLEITO','DS_SITUACAO_JULGAMENTO_PLEITO','CD_SITUACAO_JULGAMENTO_URNA','DS_SITUACAO_JULGAMENTO_URNA','CD_SITUACAO_CASSACAO','DS_SITUACAO_CASSACAO','CD_SITUACAO_CASSACAO_MIDIA','DS_SITUACAO_CASSACAO_MIDIA','CD_SITUACAO_DIPLOMA','DS_SITUACAO_DIPLOMA','CD_GENERO_FEFC','DS_GENERO_FEFC','CD_COR_RACA_FEFC','DS_COR_RACA_FEFC'] as const;

function sameHeader(a:string[],b:readonly string[]){return a.length===b.length&&a.every((v,i)=>v===b[i])}
export async function* streamTseCsv(file:string,expected:readonly string[]):AsyncGenerator<TseRow>{
  const decoder=new TextDecoder('windows-1252');let field='',record:string[]=[],quoted=false,headers:string[]|null=null,line=1;
  const emit=()=>{record.push(field);field='';const out=record;record=[];return out};
  const consume=function*(text:string):Generator<string[]>{for(let i=0;i<text.length;i++){const c=text[i]!;if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"'&&!field)quoted=true;else if(c===';'){record.push(field);field=''}else if(c==='\n'){if(field.endsWith('\r'))field=field.slice(0,-1);line++;yield emit()}else field+=c}};
  const handle=function*(rows:Iterable<string[]>):Generator<TseRow>{for(const values of rows){if(!headers){headers=values;if(headers[0]?.charCodeAt(0)===0xfeff)headers[0]=headers[0].slice(1);if(!sameHeader(headers,expected))throw new Error(`Cabeçalho TSE divergente em ${file}: esperado ${expected.length} colunas, recebido ${headers.length}`);continue}if(values.length===1&&values[0]==='')continue;if(values.length!==headers.length)throw new Error(`CSV TSE inválido em ${file}, linha ${line}: ${values.length} colunas; esperado ${headers.length}`);yield Object.fromEntries(headers.map((h,i)=>[h,values[i]!]))}};
  for await(const chunk of createReadStream(file))yield* handle(consume(decoder.decode(chunk as Buffer,{stream:true})));
  yield* handle(consume(decoder.decode()));if(quoted)throw new Error(`CSV TSE inválido em ${file}: aspas não terminadas`);if(field||record.length)yield* handle([emit()]);if(!headers)throw new Error(`CSV TSE vazio: ${file}`);
}

const empty=(v:unknown)=>{const s=String(v??'').trim();return !s||s==='#NULO#'||s==='#NULO'?'':s};
const bool=(v:unknown):boolean|null=>empty(v)==='S'?true:empty(v)==='N'?false:null;
const civil=(v:unknown)=>{const s=empty(v),m=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(s);return m?`${m[3]}-${m[2]}-${m[1]}`:s||null};
const elected=(v:unknown):boolean|null=>{const n=searchText(empty(v));if(['eleito','eleito por qp','eleito por media'].includes(n))return true;if(['nao eleito','suplente'].includes(n))return false;return null};
const relevant=(office:string)=>['senador','deputado federal'].includes(searchText(office));
const urlFor=(year:number)=>`https://dadosabertos.tse.jus.br/dataset/candidatos-${year}`;

export function parseCandidateRow(row:TseRow,meta:{year:number;rawId:string}):Candidacy|null{
  if(Number(row.ANO_ELEICAO)!==meta.year||Number(row.NR_TURNO)!==1||!relevant(row.DS_CARGO??''))return null;
  const sequenceId=empty(row.SQ_CANDIDATO),name=empty(row.NM_CANDIDATO),uf=empty(row.SG_UF);if(!sequenceId||!name||!/^[A-Z]{2}$/.test(uf))throw new Error(`Candidatura TSE incompleta: ${sequenceId||'sem SQ_CANDIDATO'}`);
  return{electionId:`tse-${meta.year}-1-brasil`,sequenceId,year:meta.year,round:1,office:row.DS_CARGO!,uf,name,ballotName:empty(row.NM_URNA_CANDIDATO)||name,ballotNumber:empty(row.NR_CANDIDATO)||null,party:empty(row.SG_PARTIDO)||null,votes:null,result:empty(row.DS_SIT_TOT_TURNO)||null,elected:elected(row.DS_SIT_TOT_TURNO),matchStatus:'pending',personId:null,matchEvidence:[],officialUrl:urlFor(meta.year),rawId:meta.rawId,electionCode:empty(row.CD_ELEICAO)||null,electionDate:civil(row.DT_ELEICAO),socialName:empty(row.NM_SOCIAL_CANDIDATO)||null,details:{candidacyStatus:empty(row.DS_SITUACAO_CANDIDATURA)||null,legalStatus:null,ballotStatus:null,diplomaStatus:null,reelection:null,declaredAssets:null,accountsSubmitted:null,substituteSequenceId:null,substituteOrder:null,campaignLimitCents:null}};
}
export function parseTseSimplified(payload:any,meta:{year:number;round:number;uf:string;office:string;rawId:string;officialUrl:string}):Candidacy[]{return (payload?.cand??[]).map((r:any)=>({electionId:`tse-${meta.year}-${meta.round}-${meta.uf.toLowerCase()}`,sequenceId:String(r.sqcand),year:meta.year,round:meta.round,office:meta.office,uf:meta.uf,name:String(r.nm),ballotName:String(r.nmu??r.nm),ballotNumber:r.n==null?null:String(r.n),party:empty(r.cc)||null,votes:r.vap==null?null:Number(r.vap),result:empty(r.st)||null,elected:elected(r.st),matchStatus:'pending',personId:null,matchEvidence:[],officialUrl:meta.officialUrl,rawId:meta.rawId}))}
export function parseTseAssets(rows:any[],rawId:string):ElectoralAsset[]{return rows.map(r=>({sequenceId:empty(r.SQ_CANDIDATO),assetId:empty(r.NR_ORDEM_BEM_CANDIDATO??r.SQ_BEM_CANDIDATO),description:empty(r.DS_BEM_CANDIDATO),kind:empty(r.DS_TIPO_BEM_CANDIDATO)||null,valueCents:decimalCents(r.VR_BEM_CANDIDATO),version:empty(r.NR_CONTROLE_CANDIDATO)||[empty(r.DT_ULT_ATUAL_BEM_CANDIDATO),empty(r.HH_ULT_ATUAL_BEM_CANDIDATO)].filter(Boolean).join(' ')||'original',rawId,updatedAt:civil(r.DT_ULT_ATUAL_BEM_CANDIDATO)}))}
export function parseTseTransactions(rows:any[],kind:'revenue'|'expense',rawId:string):CampaignTransaction[]{return rows.map(r=>({sequenceId:empty(r.SQ_CANDIDATO),transactionId:empty(r.SQ_RECEITA??r.SQ_DESPESA),kind,counterparty:empty(r.NM_DOADOR??r.NM_FORNECEDOR)||null,counterpartyDocument:empty(r.NR_CPF_CNPJ_DOADOR??r.NR_CPF_CNPJ_FORNECEDOR)||null,category:empty(r.DS_FONTE_RECEITA??r.DS_ORIGEM_DESPESA)||null,description:empty(r.DS_RECEITA??r.DS_DESPESA)||null,valueCents:decimalCents(r.VR_RECEITA??r.VR_DESPESA),date:civil(r.DT_RECEITA??r.DT_DESPESA),version:empty(r.NR_CONTROLE_CANDIDATO)||'original',rawId}))}
export function parseComplement(row:TseRow):CandidacyDetails{return{candidacyStatus:empty(row.DS_DETALHE_SITUACAO_CAND)||null,legalStatus:empty(row.DS_SITUACAO_JULGAMENTO)||null,ballotStatus:empty(row.DS_SITUACAO_CANDIDATO_URNA)||null,diplomaStatus:empty(row.DS_SITUACAO_DIPLOMA)||null,reelection:bool(row.ST_REELEICAO),declaredAssets:bool(row.ST_DECLARAR_BENS),accountsSubmitted:bool(row.ST_PREST_CONTAS),substituteSequenceId:empty(row.SQ_SUBSTITUIDO)||null,substituteOrder:empty(row.SQ_ORDEM_SUPLENCIA)?Number(row.SQ_ORDEM_SUPLENCIA):null,campaignLimitCents:empty(row.VR_DESPESA_MAX_CAMPANHA)?decimalCents(row.VR_DESPESA_MAX_CAMPANHA):null}}

const partyAt=(p:Profile,date:string)=>p.parties.find(x=>x.start.slice(0,10)<=date&&(!x.end||x.end.slice(0,10)>=date))?.party??(p.observedAt.slice(0,4)===date.slice(0,4)?p.party:null);
export function linkCandidacies(candidacies:Candidacy[],profiles:(Profile&{personId:string})[]):Candidacy[]{return candidacies.map(c=>{const source=searchText(c.office)==='senador'?'senado':'camara',date=c.electionDate??`${c.year}-10-01`,names=new Set([searchText(c.name),searchText(c.ballotName)]);const candidateParty=searchText(c.party??'');const identityMatches=profiles.filter(p=>p.source===source&&p.uf===c.uf&&[searchText(p.name),searchText(p.fullName??'')].some(n=>n&&names.has(n)));const partyMatches=candidateParty?identityMatches.filter(p=>searchText(partyAt(p,date)??'')===candidateParty):[];const matches=partyMatches.length===1?partyMatches:identityMatches;const partyConfirmed=matches.length===1&&partyMatches.includes(matches[0]!);const evidence=['nome oficial/urna','UF',`cargo/${source}`,partyConfirmed?'partido no pleito':null].filter(Boolean) as string[];return matches.length===1?{...c,personId:matches[0]!.personId,matchStatus:'confirmed',matchEvidence:evidence}:matches.length>1?{...c,personId:null,matchStatus:'ambiguous',matchEvidence:[...evidence,'múltiplos perfis compatíveis']}:{...c,personId:null,matchStatus:'pending',matchEvidence:[]}})}

export interface TseImportReport{year:number;dryRun:boolean;input:{candidates:number;assets:number;complement:number};selected:{candidacies:number;assets:number;complements:number;excludedAssets:number;orphanAssets:number};links:{confirmed:number;pending:number;ambiguous:number;notFound:number;evidence:string[]};coverage:{candidacies:'available';assets:'available';complement:'available'|'unavailable';campaignAccounts:'unavailable'};published:boolean;runId:string|null}
export async function importTseLocal(db:DatabaseSync,options:{year:number;candidatesFile:string;assetsFile:string;complementFile?:string;rawDirectory:string;dryRun?:boolean;reportFile?:string;progress?:(message:string)=>void}):Promise<TseImportReport>{
  const {year}=options;if(![2018,2022].includes(year))throw new Error('A importação local aceita os anos auditados 2018 e 2022');if(year===2022&&!options.complementFile)throw new Error('O complemento de candidaturas é obrigatório para 2022');let runId:string|null=null;
  try{if(!options.dryRun)runId=startRun(db,'tse');const fetchedAt=new Date().toISOString();const ids=options.dryRun?{cand:'dry:candidates',assets:'dry:assets',comp:'dry:complement'}:{cand:await saveRawFile(db,runId!,options.rawDirectory,options.candidatesFile,{url:urlFor(year),fetchedAt,status:200,contentType:'text/csv; charset=windows-1252'}),assets:await saveRawFile(db,runId!,options.rawDirectory,options.assetsFile,{url:`https://dadosabertos.tse.jus.br/dataset/bens-de-candidatos-${year}`,fetchedAt,status:200,contentType:'text/csv; charset=windows-1252'}),comp:options.complementFile?await saveRawFile(db,runId!,options.rawDirectory,options.complementFile,{url:urlFor(year),fetchedAt,status:200,contentType:'text/csv; charset=windows-1252'}):'dry:complement'};
    const input={candidates:0,assets:0,complement:0},candidacies:Candidacy[]=[],allCandidateIds=new Set<string>();for await(const row of streamTseCsv(options.candidatesFile,candidateHeaders)){input.candidates++;if(Number(row.ANO_ELEICAO)!==year)throw new Error(`Ano divergente em candidaturas: ${row.ANO_ELEICAO}`);allCandidateIds.add(row.SQ_CANDIDATO!);const item=parseCandidateRow(row,{year,rawId:ids.cand});if(item)candidacies.push(item)}const bySeq=new Map(candidacies.map(c=>[c.sequenceId,c]));let complements=0;if(options.complementFile)for await(const row of streamTseCsv(options.complementFile,complementHeaders)){input.complement++;if(Number(row.ANO_ELEICAO)!==year)throw new Error(`Ano divergente no complemento: ${row.ANO_ELEICAO}`);const c=bySeq.get(row.SQ_CANDIDATO!);if(c){c.details={...c.details!,...parseComplement(row)};c.detailsRawId=ids.comp;complements++}}
    const assets:ElectoralAsset[]=[];let orphanAssets=0,excludedAssets=0;for await(const row of streamTseCsv(options.assetsFile,assetHeaders)){input.assets++;if(Number(row.ANO_ELEICAO)!==year)throw new Error(`Ano divergente em bens: ${row.ANO_ELEICAO}`);if(!bySeq.has(row.SQ_CANDIDATO!)){if(allCandidateIds.has(row.SQ_CANDIDATO!))excludedAssets++;else orphanAssets++;continue}assets.push(...parseTseAssets([row],ids.assets))}
    const profiles:(Profile&{personId:string})[]=[];for(const source of ['senado','camara'] as const){let page=1,seen=0,total=0;do{const result=listPublished(db,{source,page,pageSize:100});total=result.total;profiles.push(...result.items as (Profile&{personId:string})[]);seen+=result.items.length;page++}while(seen<total)}const linked=linkCandidacies(candidacies,profiles),confirmed=linked.filter(c=>c.matchStatus==='confirmed').length,pending=linked.filter(c=>c.matchStatus==='pending').length,links={confirmed,pending,ambiguous:linked.filter(c=>c.matchStatus==='ambiguous').length,notFound:pending,evidence:['nome oficial ou nome de urna','UF','cargo e Casa','partido no pleito quando o histórico permite']};
    const report:TseImportReport={year,dryRun:Boolean(options.dryRun),input,selected:{candidacies:linked.length,assets:assets.length,complements,excludedAssets,orphanAssets},links,coverage:{candidacies:'available',assets:'available',complement:options.complementFile?'available':'unavailable',campaignAccounts:'unavailable'},published:false,runId};if(!options.dryRun){publishElection(db,runId!,{id:`tse-${year}-1-brasil`,year,round:1,scope:'BRASIL',officialUrl:urlFor(year)},'partial',`Candidaturas e bens declarados disponíveis. ${options.complementFile?'Complemento disponível.':'Complemento não fornecido para este ano.'} Receitas, despesas e votos nominais não constam nestes arquivos e permanecem indisponíveis.`,linked,assets,[]);report.published=true}if(options.reportFile)await writeFile(options.reportFile,JSON.stringify(report,null,2)+'\n','utf8');options.progress?.(`TSE ${year}: ${linked.length} candidaturas, ${assets.length} bens, ${links.confirmed} vínculos confirmados`);return report
  }catch(error){if(runId)failRun(db,runId,error instanceof Error?error.message:String(error));throw error}
}
