import {mkdirSync,writeFileSync} from 'node:fs';
import {dirname} from 'node:path';
import type{DatabaseSync}from'node:sqlite';
export interface InstitutionalMetrics {recordsFetched:number;recordsInserted:number;recordsUpdated:number;recordsUnchanged:number;suppliersCreated:number;suppliersMatched:number;invalidIdentifiers:number;maskedIdentifiers:number;contractsWithoutSupplier:number;contractsWithoutTender:number;orphanItems:number;orphanCommitments:number;duplicateExternalKeys:number;apiEmptyResponses:number;portalFallbacks:number;valueConflicts:number;requests:number;retries:number;bytes:number;oldestRecord:string|null;newestRecord:string|null}
export const emptyInstitutionalMetrics=():InstitutionalMetrics=>({recordsFetched:0,recordsInserted:0,recordsUpdated:0,recordsUnchanged:0,suppliersCreated:0,suppliersMatched:0,invalidIdentifiers:0,maskedIdentifiers:0,contractsWithoutSupplier:0,contractsWithoutTender:0,orphanItems:0,orphanCommitments:0,duplicateExternalKeys:0,apiEmptyResponses:0,portalFallbacks:0,valueConflicts:0,requests:0,retries:0,bytes:0,oldestRecord:null,newestRecord:null});
export function startInstitutionalMetrics(db:DatabaseSync,runId:string,collector:string,scope:string,startedAt=new Date().toISOString()){db.prepare(`INSERT INTO institutional_collector_metrics(run_id,collector,scope,started_at,status) VALUES (?,?,?,?,'running')`).run(runId,collector,scope,startedAt)}
export function finishInstitutionalMetrics(db:DatabaseSync,runId:string,collector:string,scope:string,metrics:InstitutionalMetrics,status:'complete'|'failed',error:string|null=null){db.prepare(`UPDATE institutional_collector_metrics SET records_fetched=?,records_inserted=?,records_updated=?,records_unchanged=?,suppliers_created=?,suppliers_matched=?,invalid_identifiers=?,masked_identifiers=?,contracts_without_supplier=?,contracts_without_tender=?,orphan_items=?,orphan_commitments=?,duplicate_external_keys=?,api_empty_responses=?,portal_fallbacks=?,value_conflicts=?,requests=?,retries=?,bytes=?,oldest_record=?,newest_record=?,finished_at=?,status=?,error=? WHERE run_id=? AND collector=? AND scope=?`).run(metrics.recordsFetched,metrics.recordsInserted,metrics.recordsUpdated,metrics.recordsUnchanged,metrics.suppliersCreated,metrics.suppliersMatched,metrics.invalidIdentifiers,metrics.maskedIdentifiers,metrics.contractsWithoutSupplier,metrics.contractsWithoutTender,metrics.orphanItems,metrics.orphanCommitments,metrics.duplicateExternalKeys,metrics.apiEmptyResponses,metrics.portalFallbacks,metrics.valueConflicts,metrics.requests,metrics.retries,metrics.bytes,metrics.oldestRecord,metrics.newestRecord,new Date().toISOString(),status,error,runId,collector,scope)}
export function checkpoint(db:DatabaseSync,collector:string,scope:string,state:{cursor?:string|null;status:'pending'|'running'|'complete'|'failed';error?:string|null;metadata?:Record<string,unknown>}){db.prepare(`INSERT INTO institutional_collector_checkpoints(collector,scope,cursor,updated_at,status,attempts,last_error,metadata_json) VALUES (?,?,?,?,?,1,?,?) ON CONFLICT(collector,scope) DO UPDATE SET cursor=excluded.cursor,updated_at=excluded.updated_at,status=excluded.status,attempts=institutional_collector_checkpoints.attempts+1,last_error=excluded.last_error,metadata_json=excluded.metadata_json`).run(collector,scope,state.cursor??null,new Date().toISOString(),state.status,state.error??null,JSON.stringify(state.metadata??{}))}
export function institutionalRunReport(db:DatabaseSync,runId:string){const rows=db.prepare('SELECT * FROM institutional_collector_metrics WHERE run_id=? ORDER BY collector,scope').all(runId).map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key,typeof value==='bigint'?Number(value):value])));const run=db.prepare('SELECT id,source,started_at,finished_at,status,error,reconciliation_json FROM ingestion_runs WHERE id=?').get(runId);if(!run)throw new Error('Execução institucional não encontrada');return{generatedAt:new Date().toISOString(),run:Object.fromEntries(Object.entries(run).map(([key,value])=>[key,typeof value==='bigint'?Number(value):value])),collectors:rows}}
export function writeInstitutionalRunReport(db:DatabaseSync,runId:string,jsonPath:string,markdownPath?:string){const report=institutionalRunReport(db,runId);mkdirSync(dirname(jsonPath),{recursive:true});writeFileSync(jsonPath,`${JSON.stringify(report,null,2)}\n`);if(markdownPath){mkdirSync(dirname(markdownPath),{recursive:true});const lines=[`# Execução institucional ${runId}`,'',`- Status: **${String(report.run.status)}**`,`- Início: ${String(report.run.started_at)}`,`- Fim: ${String(report.run.finished_at??'em andamento')}`,'','| Collector | Escopo | Status | Fetched | Inserted | Updated | Unchanged | Requests | Retries | Bytes |','| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |',...report.collectors.map(row=>`| ${row.collector} | ${row.scope} | ${row.status} | ${row.records_fetched} | ${row.records_inserted} | ${row.records_updated} | ${row.records_unchanged} | ${row.requests} | ${row.retries} | ${row.bytes} |`),''];writeFileSync(markdownPath,lines.join('\n'))}return report}
