import {createHash,randomUUID} from 'node:crypto';
import {mkdirSync,writeFileSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import type {DatabaseSync} from 'node:sqlite';
import type {InstitutionalRawResponse} from './institutional-http.ts';
import {stableInstitutionalId} from './institutional-normalize.ts';

export function conditionalHeaders(db:DatabaseSync,url:string){const row=db.prepare(`SELECT json_extract(payload,'$.etag') etag,json_extract(payload,'$.lastModified') modified FROM institutional_source_records WHERE json_extract(payload,'$.url')=? ORDER BY fetched_at DESC LIMIT 1`).get(url);return{...(row?.etag?{'If-None-Match':String(row.etag)}:{}),...(row?.modified?{'If-Modified-Since':String(row.modified)}:{})}}
export function persistInstitutionalRaw(db:DatabaseSync,runId:string,rawDirectory:string,response:InstitutionalRawResponse){if(response.status!==200||!response.bytes.length)throw new Error('Somente resposta completa pode ser persistida como raw');const sha256=createHash('sha256').update(response.bytes).digest('hex'),rawId=randomUUID(),path=resolve(rawDirectory,'institutional',runId,`${sha256}.bin`);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,response.bytes);db.prepare('INSERT INTO raw_objects VALUES (?,?,?,?,?,?,?,?,?)').run(rawId,runId,response.url,response.fetchedAt,response.status,response.contentType,sha256,path,response.bytes.byteLength);return{rawId,sha256,path}}
export function stageInstitutionalSourceRecord(db:DatabaseSync,input:{batchId:string;sourceSystem:string;entityType:string;externalKey:string;payload:unknown;sourceUpdatedAt?:string|null;fetchedAt:string;rawId:string}){const payload=JSON.stringify(input.payload),hash=createHash('sha256').update(payload).digest('hex'),id=stableInstitutionalId('isr',input.batchId,input.entityType,input.externalKey);db.prepare(`INSERT INTO institutional_source_records(id,batch_id,source_system,entity_type,external_key,payload_hash,source_updated_at,fetched_at,raw_id,payload) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(batch_id,entity_type,external_key) DO UPDATE SET payload_hash=excluded.payload_hash,source_updated_at=excluded.source_updated_at,fetched_at=excluded.fetched_at,raw_id=excluded.raw_id,payload=excluded.payload`).run(id,input.batchId,input.sourceSystem,input.entityType,input.externalKey,hash,input.sourceUpdatedAt??null,input.fetchedAt,input.rawId,payload);return{id,hash}}
