import {createHash} from 'node:crypto';

export const compoundKey=(...parts:(string|number|null|undefined)[])=>parts.map(value=>String(value??'').trim().replaceAll('\u001f',' ')).join('\u001f');
export const stableInstitutionalId=(prefix:string,...parts:(string|number|null|undefined)[])=>`${prefix}_${createHash('sha256').update(compoundKey(...parts)).digest('hex').slice(0,32)}`;
export function isoDate(value:unknown):string|null{if(value===null||value===undefined||value==='')return null;const text=String(value).trim();const br=/^(\d{2})\/(\d{2})\/(\d{4})(?:\s+(\d{2}):(\d{2})(?::(\d{2}))?)?$/.exec(text);const candidate=br?`${br[3]}-${br[2]}-${br[1]}${br[4]?`T${br[4]}:${br[5]}:${br[6]??'00'}Z`:''}`:text;const date=new Date(candidate.length===10?`${candidate}T00:00:00Z`:candidate);return Number.isNaN(date.valueOf())?null:(candidate.length===10?candidate:date.toISOString())}
export function scaledDecimal(value:unknown,scale=2):number|null{if(value===null||value===undefined||value==='')return null;if(!Number.isInteger(scale)||scale<0||scale>6)throw new Error('Escala inválida');let text=String(value).trim().replace(/R\$\s?/gi,'').replace(/\s/g,'');if(/^[-+]?\d{1,3}(?:\.\d{3})*,\d+$/.test(text))text=text.replaceAll('.','').replace(',','.');else if(/^[-+]?\d+,\d+$/.test(text))text=text.replace(',','.');else text=text.replaceAll(',','');const number=Number(text);if(!Number.isFinite(number))return null;const scaled=Math.round(number*10**scale);if(!Number.isSafeInteger(scaled))throw new Error('Valor fora da precisão segura');return scaled}
export function signedMovement(value:unknown,kind:unknown,scale=2):number|null{const amount=scaledDecimal(value,scale);if(amount===null)return null;const normalized=String(kind??'').normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase();return /anul|estorn|cancel|devol|revers/.test(normalized)?-Math.abs(amount):amount}
export function requireRecord(value:unknown,label='registro'):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(`${label} inválido`);return value as Record<string,unknown>}
export function requireArray(value:unknown,label='conjunto'):unknown[]{if(!Array.isArray(value))throw new Error(`${label} não é uma lista`);return value}
