export interface InstitutionalRawResponse {url:string;fetchedAt:string;status:number;contentType:string;bytes:Uint8Array;etag:string|null;lastModified:string|null}
export interface InstitutionalHttpOptions {fetch?:typeof fetch;sleep?:(ms:number)=>Promise<void>;timeoutMs?:number;maxAttempts?:number;maxBytes?:number;delayMs?:number;onRequest?:(retry:boolean)=>void}
const allowedHosts=new Set(['dadosabertos.camara.leg.br','www.camara.leg.br','adm.senado.gov.br','www.senado.gov.br','www.senado.leg.br','www6g.senado.leg.br','www12.senado.leg.br','pncp.gov.br','legis.senado.leg.br']);
export function officialInstitutionalUrl(input:string){const url=new URL(input);if(url.protocol!=='https:'||!allowedHosts.has(url.hostname)||url.username||url.password||url.hash)throw new Error('URL institucional fora da allowlist oficial');return url.href}
export class InstitutionalHttp {
  constructor(private readonly options:InstitutionalHttpOptions={}){}
  async bytes(input:string,headers:Record<string,string>={}):Promise<InstitutionalRawResponse>{const url=officialInstitutionalUrl(input),sleep=this.options.sleep??(ms=>new Promise(resolve=>setTimeout(resolve,ms))),attempts=this.options.maxAttempts??4;if(!Number.isInteger(attempts)||attempts<1||attempts>6)throw new Error('Número de tentativas inválido');for(let attempt=1;attempt<=attempts;attempt++){this.options.onRequest?.(attempt>1);if(this.options.delayMs??120)await sleep(this.options.delayMs??120);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.options.timeoutMs??60_000);try{const response=await(this.options.fetch??fetch)(url,{headers:{Accept:'application/json,text/csv,application/octet-stream;q=0.9,*/*;q=0.5','User-Agent':'Cívica/0.1 (official-data-collector)',...headers},signal:controller.signal,redirect:'error'});const reader=response.body?.getReader(),chunks:Uint8Array[]=[];let size=0;if(reader)while(true){const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>(this.options.maxBytes??250_000_000)){controller.abort();throw new Error('Resposta institucional excede limite de tamanho')}chunks.push(part.value)}const bytes=Buffer.concat(chunks),raw={url,fetchedAt:new Date().toISOString(),status:response.status,contentType:response.headers.get('content-type')??'',bytes,etag:response.headers.get('etag'),lastModified:response.headers.get('last-modified')};if(response.status===429||response.status>=500){if(attempt===attempts)throw new Error(`HTTP ${response.status} após ${attempt} tentativas`);const retry=response.headers.get('retry-after'),parsed=retry?(/^\d+$/.test(retry)?Number(retry)*1000:Date.parse(retry)-Date.now()):NaN;await sleep(Math.min(60_000,Math.max(0,Number.isFinite(parsed)?parsed:500*2**(attempt-1))));continue}if(response.status!==200)throw new Error(`HTTP ${response.status}: ${new URL(url).pathname}`);if(!bytes.length)throw new Error('Resposta institucional vazia');return raw}catch(error){if(attempt===attempts||error instanceof Error&&/^HTTP 4(?!29)/.test(error.message))throw error;await sleep(Math.min(10_000,500*2**(attempt-1)))}finally{clearTimeout(timer)}}throw new Error('Tentativas institucionais esgotadas')}
  async json(input:string){const raw=await this.bytes(input,{Accept:'application/json'});if(!/json/i.test(raw.contentType))throw new Error('Resposta institucional não é JSON');let data:unknown;try{data=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(raw.bytes))}catch{throw new Error('JSON institucional inválido')}return{raw,data}}
}
