import type { DatabaseSync } from 'node:sqlite';
import { failRun, startRun, transaction } from '@senadotracker/db';
import { InstitutionalHttp } from './institutional-http.ts';
import { scaledDecimal, stableInstitutionalId } from './institutional-normalize.ts';
import { checkpoint, emptyInstitutionalMetrics, finishInstitutionalMetrics, startInstitutionalMetrics } from './institutional-run.ts';
import { persistInstitutionalRaw, stageInstitutionalSourceRecord } from './institutional-storage.ts';

const clean = (value: string) => value.replace(/<[^>]+>/g, ' ').replace(/&nbsp;/gi, ' ').replace(/&amp;/gi, '&').replace(/\s+/g, ' ').trim();
const normalizeNe = (value: string) => { const compact=value.replace(/\s/g,'');const official=/(\d{4})NE0*(\d+)/i.exec(compact.replaceAll('/',''));if(official)return`${official[1]!}NE${official[2]!.padStart(6,'0')}`;const portal=/NE0*(\d+)\/(\d{4})/i.exec(compact);return portal?`${portal[2]!}NE${portal[1]!.padStart(6,'0')}`:null; };
export interface SenateExecutionRow { commitmentNumber: string; detailUrl: string; expenseGroup: string | null; expenseElement: string | null; committedScaled: number; liquidatedScaled: number; paidScaled: number }
export interface SenateExecutionMovement { sourceId:string;phase:'commitment'|'liquidation'|'payment';kind:string;occurredAt:string|null;movementYear:number;amountSignedScaled:number;restosAPagar:boolean;detailUrl:string|null }
export function parseSenateContractualExpenses(html: string): SenateExecutionRow[] {
  const body = /id="tabDespesasContratuais"[\s\S]*?<tbody>([\s\S]*?)<\/tbody>/i.exec(html)?.[1] ?? '';
  const rows: SenateExecutionRow[] = [];
  for (const match of body.matchAll(/<tr>([\s\S]*?)<\/tr>/gi)) {
    const cells = [...match[1]!.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(cell => clean(cell[1]!));
    const href = /<a[^>]+href="([^"]+)"/i.exec(match[1]!)?.[1]?.replaceAll('&amp;', '&') ?? '';
    const commitmentNumber = normalizeNe(cells[0] ?? '');
    const committedScaled = scaledDecimal(cells[3]), liquidatedScaled = scaledDecimal(cells[4]), paidScaled = scaledDecimal(cells[5]);
    if (commitmentNumber && committedScaled !== null && liquidatedScaled !== null && paidScaled !== null) rows.push({ commitmentNumber, detailUrl: href, expenseGroup: cells[1] || null, expenseElement: cells[2] || null, committedScaled, liquidatedScaled, paidScaled });
  }
  return rows;
}
export function aggregateSenateExecutionRows(rows:SenateExecutionRow[]):SenateExecutionRow[]{const grouped=new Map<string,SenateExecutionRow>();for(const row of rows){const current=grouped.get(row.commitmentNumber);if(current){current.committedScaled+=row.committedScaled;current.liquidatedScaled+=row.liquidatedScaled;current.paidScaled+=row.paidScaled;if(!current.detailUrl&&row.detailUrl)current.detailUrl=row.detailUrl}else grouped.set(row.commitmentNumber,{...row})}return[...grouped.values()]}

const absoluteSenateUrl=(href:string)=>{const url=new URL(href.replace(/^detalhe_documento\.asp/i,'detalhaDocumento.asp'),'https://www.senado.gov.br/transparencia/gestgov/recdesp/despesas/');return url.href};
export function parseSenateExecutionDetail(html:string,commitmentYear:number):SenateExecutionMovement[]{const section=/id="collapseDocumentosRelacionados"[\s\S]*?<tbody>([\s\S]*?)<\/tbody>/i.exec(html)?.[1]??'',rows:SenateExecutionMovement[]=[];for(const match of section.matchAll(/<tr>([\s\S]*?)<\/tr>/gi)){const cells=[...match[1]!.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(cell=>clean(cell[1]!)),rawPhase=(cells[1]??'').normalize('NFD').replace(/\p{Diacritic}/gu,'').toUpperCase(),phase=/PAGAMENTO/.test(rawPhase)?'payment':/LIQUID/.test(rawPhase)?'liquidation':/EMPENHO/.test(rawPhase)?'commitment':null,document=clean(cells[2]??''),date=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(cells[0]??''),amount=scaledDecimal(cells[7]),href=/<a[^>]+href="([^"]+)"/i.exec(match[1]!)?.[1]?.replaceAll('&amp;','&')??null;if(!phase||!document||!date||amount===null)continue;const occurredAt=`${date[3]}-${date[2]}-${date[1]}`,movementYear=Number(date[3]),negative=/ANULA|ESTORNO|CANCEL|DEVOL|REVERS/.test(rawPhase),sequence=cells[3]??'0';rows.push({sourceId:`${document}:${sequence}:${phase}`,phase,kind:negative?`anulação/estorno (${cells[1]})`:`documento relacionado (${cells[1]})`,occurredAt,movementYear,amountSignedScaled:negative?-Math.abs(amount):amount,restosAPagar:movementYear>commitmentYear,detailUrl:href?absoluteSenateUrl(href):null})}return rows}
export function parseSenateDocumentCommitments(html:string):string[]{return[...new Set(parseSenateExecutionDetail(html,0).filter(row=>row.phase==='commitment').map(row=>normalizeNe(row.sourceId.split(':')[0]!)!).filter(Boolean))]}
export function reconciledDetailedPhases(movements:SenateExecutionMovement[],expected:Record<SenateExecutionMovement['phase'],number>){const accepted=new Set<SenateExecutionMovement['phase']>(),conflicts:SenateExecutionMovement['phase'][]=[];for(const phase of ['commitment','liquidation','payment'] as const){const rows=movements.filter(movement=>movement.phase===phase);if(!rows.length)continue;if(rows.reduce((sum,movement)=>sum+movement.amountSignedScaled,0)===expected[phase])accepted.add(phase);else conflicts.push(phase)}return{accepted,conflicts}}

export interface SenateFinancialOptions { year?: number; rawDirectory: string; ids?: string[]; limit?: number | null; dryRun?: boolean; force?: boolean; http?: InstitutionalHttp; progress?: (message: string) => void }
export async function collectSenateFinancialExecution(db: DatabaseSync, options: SenateFinancialOptions) {
  const filters = options.ids?.length ? `AND (c.id IN (${options.ids.map(() => '?').join(',')}) OR substr(c.source_contract_id,11) IN (${options.ids.map(() => '?').join(',')}))` : '';
  const bindings = options.ids?.length ? [...options.ids, ...options.ids] : [];
  const commitments = db.prepare(`SELECT cm.*,c.source_contract_id,si.normalized_value supplier_document FROM commitments cm JOIN institutional_contracts c ON c.id=cm.contract_id JOIN supplier_identifiers si ON si.supplier_id=cm.supplier_id AND si.identifier_type='cnpj' AND si.is_masked=0 WHERE cm.institution='SENADO' AND cm.source_system='senado_portal'${options.year?` AND cm.commitment_year=${Number(options.year)}`:''} ${filters} GROUP BY cm.id ORDER BY cm.commitment_year DESC LIMIT ?`).all(...bindings, options.limit ?? 250);
  if (!commitments.length) return { skipped: true, reason: 'no-linked-commitments' };
  const groups = new Map<string, Record<string, unknown>[]>();
  for (const commitment of commitments) { const key = `${commitment.supplier_document}:${commitment.commitment_year}`; groups.set(key, [...(groups.get(key) ?? []), commitment]); }
  const scope = 'linked-commitments', runId = startRun(db, 'senado'), metrics = emptyInstitutionalMetrics(), http = options.http ?? new InstitutionalHttp({ delayMs: 180 });
  startInstitutionalMetrics(db, runId, 'senate-financial', scope); checkpoint(db, 'senate-financial', scope, { status: 'running' });
  try {
    const collected: Array<{ key: string; commitments: Record<string, unknown>[]; rows: SenateExecutionRow[]; rawId: string; fetchedAt: string; url: string }> = [];
    for (const [key, linked] of groups) { const [document, year] = key.split(':'); const url = `https://www6g.senado.leg.br/transparencia/orcfin/despesas-contratuais/${year}/favorecido/${document}`; const response = await http.bytes(url, { Accept: 'text/html' }); const raw = persistInstitutionalRaw(db, runId, options.rawDirectory, response); const rawRows = parseSenateContractualExpenses(new TextDecoder().decode(response.bytes)),rows=aggregateSenateExecutionRows(rawRows); collected.push({ key, commitments: linked, rows, rawId: raw.rawId, fetchedAt: response.fetchedAt, url }); metrics.requests++; metrics.bytes += response.bytes.length; options.progress?.(`${key}: ${rows.length} empenhos distintos (${rawRows.length} linhas financeiras)`); }
    const matched = collected.flatMap(group => group.commitments.map(commitment => ({ group, commitment, row: group.rows.find(row => row.commitmentNumber === normalizeNe(String(commitment.commitment_number))),detail:null as null|{movements:SenateExecutionMovement[];rawId:string;fetchedAt:string} })).filter(item => item.row));
    for(const item of matched){if(!item.row!.detailUrl)continue;try{const response=await http.bytes(absoluteSenateUrl(item.row!.detailUrl),{Accept:'text/html'}),raw=persistInstitutionalRaw(db,runId,options.rawDirectory,response),movements=parseSenateExecutionDetail(new TextDecoder().decode(response.bytes),Number(item.commitment.commitment_year));item.detail={movements,rawId:raw.rawId,fetchedAt:response.fetchedAt};metrics.requests++;metrics.bytes+=response.bytes.length}catch{metrics.apiEmptyResponses++}}
    const movementUrls=[...new Set(matched.flatMap(item=>item.detail?.movements.map(movement=>movement.detailUrl).filter((url):url is string=>Boolean(url))??[]))],verified=new Map<string,string|null>();for(const url of movementUrls){try{const response=await http.bytes(url,{Accept:'text/html'});persistInstitutionalRaw(db,runId,options.rawDirectory,response);const related=parseSenateDocumentCommitments(new TextDecoder().decode(response.bytes));verified.set(url,related.length===1?related[0]!:null);metrics.requests++;metrics.bytes+=response.bytes.length}catch{verified.set(url,null);metrics.apiEmptyResponses++}}for(const item of matched)if(item.detail)item.detail.movements=item.detail.movements.filter(movement=>movement.detailUrl&&verified.get(movement.detailUrl)===item.row!.commitmentNumber);
    metrics.recordsFetched = matched.reduce((sum,item)=>sum+2+(item.detail?.movements.length||1),0); metrics.orphanCommitments = commitments.length - matched.length;
    if (options.dryRun) { finishInstitutionalMetrics(db, runId, 'senate-financial', scope, metrics, 'complete'); failRun(db, runId, 'dry-run'); checkpoint(db, 'senate-financial', scope, { status: 'pending', metadata: { dryRun: true, matched: matched.length } }); return { dryRun: true, matched: matched.length, metrics }; }
    transaction(db, () => { const now = new Date().toISOString(); db.prepare('INSERT INTO institutional_collection_batches VALUES (?,?,?,?,?,?,?,?,?,?)').run(runId, 'SENADO', 'senado_siafi', 'financial_execution', null, null, now, metrics.orphanCommitments ? 'partial' : 'available', metrics.recordsFetched, JSON.stringify(metrics));
      for (const item of matched) { const row = item.row!; const record = stageInstitutionalSourceRecord(db, { batchId: runId, sourceSystem: 'senado_siafi', entityType: 'commitment_execution', externalKey: `${item.group.key}:${row.commitmentNumber}`, payload: { url: item.group.url, row, detailMovements:item.detail?.movements??[], note: 'Totais por NE são agregados. Documentos relacionados só substituem uma fase quando a ligação reversa é inequívoca e a soma líquida reconcilia exatamente com o total oficial.' }, fetchedAt: item.group.fetchedAt, rawId: item.group.rawId }); db.prepare('UPDATE commitments SET committed_value_scaled=?,link_evidence=?,source_record_id=? WHERE id=?').run(row.committedScaled, row.detailUrl || item.group.url, record.id, String(item.commitment.id));db.prepare("DELETE FROM financial_movements WHERE commitment_id=? AND source_system IN ('senado_portal','senado_siafi')").run(String(item.commitment.id));
        const expected={commitment:row.committedScaled,liquidation:row.liquidatedScaled,payment:row.paidScaled},detailMovements=item.detail?.movements??[],reconciled=reconciledDetailedPhases(detailMovements,expected),detailedPhases=reconciled.accepted;metrics.valueConflicts+=reconciled.conflicts.length;for(const phase of reconciled.conflicts){const observed=detailMovements.filter(movement=>movement.phase===phase).reduce((sum,movement)=>sum+movement.amountSignedScaled,0),issueKind=`detail_${phase}_does_not_reconcile`;db.prepare(`INSERT INTO financial_reconciliation_issues(id,institution,contract_id,commitment_id,source_system,issue_kind,expected_scaled,observed_scaled,value_scale,status,evidence_json,observed_at) VALUES (?,'SENADO',?,?,'senado_siafi',?,?,?,2,'open',?,?) ON CONFLICT(source_system,issue_kind,commitment_id) DO UPDATE SET expected_scaled=excluded.expected_scaled,observed_scaled=excluded.observed_scaled,status='open',evidence_json=excluded.evidence_json,observed_at=excluded.observed_at`).run(stableInstitutionalId('financial_issue','senado_siafi',String(item.commitment.id),issueKind),String(item.commitment.contract_id),String(item.commitment.id),issueKind,expected[phase],observed,JSON.stringify({phase,commitmentNumber:row.commitmentNumber,documents:detailMovements.filter(movement=>movement.phase===phase).map(movement=>movement.sourceId)}),item.group.fetchedAt)}for (const [phase, amount] of Object.entries(expected) as [SenateExecutionMovement['phase'],number][]) {if(detailedPhases.has(phase))continue; const sourceId = `${row.commitmentNumber}:${phase}:aggregate`; db.prepare(`INSERT INTO financial_movements(id,commitment_id,source_system,source_movement_id,phase,movement_kind,movement_year,occurred_at,currency,amount_signed_scaled,value_scale,restos_a_pagar,source_record_id) VALUES (?,?,'senado_siafi',?,?, 'agregado oficial por NE; exercício do movimento e restos a pagar não separáveis',?,NULL,'BRL',?,2,0,?) ON CONFLICT(source_system,source_movement_id) DO UPDATE SET amount_signed_scaled=excluded.amount_signed_scaled,restos_a_pagar=excluded.restos_a_pagar,source_record_id=excluded.source_record_id`).run(stableInstitutionalId('movement', 'senado_siafi', sourceId), String(item.commitment.id), sourceId, phase, Number(item.commitment.commitment_year), amount, record.id); metrics.recordsInserted++; }
        for(const movement of detailMovements.filter(movement=>detailedPhases.has(movement.phase))){const sourceId=`${row.commitmentNumber}:${movement.sourceId}`;db.prepare(`INSERT INTO financial_movements(id,commitment_id,source_system,source_movement_id,phase,movement_kind,movement_year,occurred_at,currency,amount_signed_scaled,value_scale,restos_a_pagar,source_record_id) VALUES (?,?,'senado_siafi',?,?,?,?,?,'BRL',?,2,?,?) ON CONFLICT(source_system,source_movement_id) DO UPDATE SET phase=excluded.phase,movement_kind=excluded.movement_kind,movement_year=excluded.movement_year,occurred_at=excluded.occurred_at,amount_signed_scaled=excluded.amount_signed_scaled,restos_a_pagar=excluded.restos_a_pagar,source_record_id=excluded.source_record_id`).run(stableInstitutionalId('movement','senado_siafi',sourceId),String(item.commitment.id),sourceId,movement.phase,movement.kind,movement.movementYear,movement.occurredAt,movement.amountSignedScaled,movement.restosAPagar?1:0,record.id);metrics.recordsInserted++}
      }
      db.prepare(`INSERT INTO active_institutional_publications VALUES ('SENADO','senado_siafi','financial_execution',?) ON CONFLICT(institution,source_system,dataset) DO UPDATE SET batch_id=excluded.batch_id`).run(runId); db.prepare("UPDATE ingestion_runs SET status='published',finished_at=?,expected_count=?,roster_complete=1,reconciliation_json=? WHERE id=?").run(now, metrics.recordsFetched, JSON.stringify(metrics), runId); db.prepare('DELETE FROM job_locks WHERE run_id=?').run(runId);
    }); finishInstitutionalMetrics(db, runId, 'senate-financial', scope, metrics, 'complete'); checkpoint(db, 'senate-financial', scope, { status: 'complete', metadata: { runId, matched: matched.length } }); return { runId, matched: matched.length, metrics };
  } catch (error) { const message = error instanceof Error ? error.message : String(error); try { finishInstitutionalMetrics(db, runId, 'senate-financial', scope, metrics, 'failed', message); } catch {} failRun(db, runId, message); checkpoint(db, 'senate-financial', scope, { status: 'failed', error: message }); throw error; }
}
