import type { ReactNode } from 'react';
import Link from 'next/link';
import type { DataCoverage } from '@senadotracker/domain';
import { CoverageBadge } from '@/components/metrics';

export interface ChartDatum {label:string;value:number|null;color?:string}
/** Cor que codifica avaliação, não série. O objeto — e não um callback solto — obriga a legenda:
    sem ela a cor vira ruído. `of` devolve valor CSS; StackedBarChart fica fora porque lá `color` é classe. */
export interface ChartTone {of:(datum:ChartDatum)=>string;legend:{label:string;color:string}[]}
export interface MultiLineDatum {label:string;values:{label:string;value:number|null;color:string}[]}
export interface GroupedDatum {label:string;values:{label:string;value:number|null;color:string}[]}
const number=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2});
const compact=new Intl.NumberFormat('pt-BR',{notation:'compact',maximumFractionDigits:1});
const formatted=(value:number|null)=>value===null?'Indisponível':number.format(value);
const short=(value:number)=>Math.abs(value)>=10_000?compact.format(value):number.format(value);

function Frame({title,coverage,children,data,legend}:{title:string;coverage:DataCoverage;children:React.ReactNode;data:ChartDatum[];legend?:{label:string;color:string}[]}){
  const valid=data.filter(item=>item.value!==null);
  if(!valid.length)return <div className="grid min-h-64 min-w-0 place-items-center rounded-2xl border bg-card p-6 text-center"><div><p className="font-bold">{title}</p><p className="mt-2 text-sm text-muted-foreground">{coverage.note}</p><div className="mt-3"><CoverageBadge coverage={coverage}/></div></div></div>;
  return <figure className="min-w-0 rounded-2xl border bg-card p-5"><figcaption className="flex flex-wrap items-center justify-between gap-2 font-bold">{title}<CoverageBadge coverage={coverage}/></figcaption>{legend&&<ul className="mt-4 flex flex-wrap gap-4 text-xs text-muted-foreground">{legend.map(item=><li className="flex items-center gap-2" key={item.label}><i className="size-3 rounded-sm" style={{background:item.color}}/>{item.label}</li>)}</ul>}<div className="mt-5">{children}</div><details className="mt-4 text-sm"><summary className="focus-ring w-fit cursor-pointer font-bold text-primary">Ver dados do gráfico</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left"><caption className="sr-only">Dados de {title}</caption><thead><tr className="border-b"><th className="p-2">Categoria</th><th className="p-2 text-right">Valor</th></tr></thead><tbody>{data.map(item=><tr className="border-b" key={item.label}><th className="p-2 font-normal">{item.label}</th><td className="p-2 text-right tabular-nums">{formatted(item.value)}</td></tr>)}</tbody></table></div></details></figure>;
}

const fillOf=(item:ChartDatum,tone?:ChartTone)=>tone?tone.of(item):item.color;
export function BarChart({title,data,coverage,tone}:{title:string;data:ChartDatum[];coverage:DataCoverage;tone?:ChartTone}){
  const max=Math.max(...data.map(item=>item.value??0),1);
  return <Frame title={title} data={data} coverage={coverage} {...(tone?{legend:tone.legend}:{})}><div className="space-y-4" aria-label={`Gráfico de barras: ${title}`}>{data.map(item=>{const fill=fillOf(item,tone);return <div key={item.label} title={`${item.label}: ${formatted(item.value)}`}><div className="mb-1 flex items-end justify-between gap-3 text-sm"><span className="font-medium">{item.label}</span><strong className="tabular-nums">{formatted(item.value)}</strong></div><div className="h-5 overflow-hidden rounded-full border bg-muted"><div className="h-full rounded-full bg-chart-1" style={{width:`${100*(item.value??0)/max}%`,...(fill?{backgroundColor:fill}:{})}}/></div></div>})}</div></Frame>;
}

export function HistogramChart({title,data,coverage,tone}:{title:string;data:ChartDatum[];coverage:DataCoverage;tone?:ChartTone}){
  const max=Math.max(...data.map(item=>item.value??0),1);
  return <Frame title={title} data={data} coverage={coverage} {...(tone?{legend:tone.legend}:{})}><div className="flex h-64 items-end gap-2 border-b border-l px-3 pt-8" aria-label={`Histograma: ${title}`}>{data.map(item=>{const fill=fillOf(item,tone);return <div key={item.label} title={`${item.label}: ${formatted(item.value)}`} className="flex h-full min-w-0 flex-1 flex-col justify-end text-center"><strong className="mb-2 truncate text-xs tabular-nums">{item.value===null?'—':short(item.value)}</strong><div className="min-h-px rounded-t bg-chart-1" style={{height:`${100*(item.value??0)/max}%`,...(fill?{backgroundColor:fill}:{})}}/><span className="mt-2 truncate text-xs text-muted-foreground">{item.label}</span></div>})}</div></Frame>;
}

export interface StackedDatum {label:string;segments:{label:string;value:number;color?:string}[]}
// Atenção: aqui `color` é CLASSE Tailwind, não valor CSS como nos demais gráficos. Por isso este
// componente não aceita `tone` — unificar o contrato seria refactor sem ganho para os importadores.
const colors=['bg-chart-1','bg-chart-2','bg-chart-3','bg-chart-4'];
export function StackedBarChart({title,data,coverage}:{title:string;data:StackedDatum[];coverage:DataCoverage}){
  const flattened=data.map(item=>({label:item.label,value:item.segments.reduce((total,segment)=>total+segment.value,0)})),legend=[...new Map(data.flatMap(item=>item.segments).map(segment=>[segment.label,segment])).values()];
  return <Frame title={title} data={flattened} coverage={coverage}><div className="mb-5 flex flex-wrap gap-4 text-xs">{legend.map((segment,index)=><span key={segment.label} className="flex items-center gap-2"><i className={`size-3 rounded-sm ${segment.color??colors[index%colors.length]}`}/>{segment.label}</span>)}</div><div className="space-y-5">{data.map(row=>{const total=row.segments.reduce((value,segment)=>value+segment.value,0);return <div key={row.label}><div className="mb-2 flex justify-between gap-3 text-sm"><strong>{row.label}</strong><span className="tabular-nums">Total: {formatted(total)}</span></div><div className="flex h-7 overflow-hidden rounded-full border bg-muted">{row.segments.map((segment,index)=><div key={segment.label} title={`${row.label} · ${segment.label}: ${formatted(segment.value)}`} className={segment.color??colors[index%colors.length]} style={{width:`${total?100*segment.value/total:0}%`}}><span className="sr-only">{segment.label}: {formatted(segment.value)}</span></div>)}</div><div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground">{row.segments.map(segment=><span key={segment.label}>{segment.label}: <strong className="text-foreground">{formatted(segment.value)}</strong></span>)}</div></div>})}</div></Frame>;
}

export function LineChart({title,data,coverage,min:fixedMin,max:fixedMax,suffix=''}:{title:string;data:ChartDatum[];coverage:DataCoverage;min?:number;max?:number;suffix?:string}){
  const valid=data.map((item,index)=>({...item,index})).filter(item=>item.value!==null),rawMax=Math.max(...valid.map(item=>item.value!),0),rawMin=Math.min(...valid.map(item=>item.value!),0),padding=(rawMax-rawMin)*.12||Math.max(Math.abs(rawMax)*.12,1),max=fixedMax??rawMax+padding,min=fixedMin??Math.min(0,rawMin-padding),x=(index:number)=>data.length===1?360:70+580*index/(data.length-1),y=(value:number)=>215-165*(Math.max(min,Math.min(max,value))-min)/(max-min||1),segments:typeof valid[]=[];let segment:typeof valid=[];
  data.forEach((item,index)=>{if(item.value===null){if(segment.length)segments.push(segment);segment=[]}else segment.push({...item,index})});if(segment.length)segments.push(segment);
  const ticks=[max,(max+min)/2,min];
  return <Frame title={title} data={data} coverage={coverage}><div className="overflow-x-auto"><svg role="img" aria-label={`Gráfico de linha: ${title}`} viewBox="0 0 720 275" className="h-auto min-w-[620px] w-full"><g stroke="var(--border)" strokeWidth="1">{ticks.map((tick,index)=><line key={index} x1="68" x2="660" y1={y(tick)} y2={y(tick)}/>)}</g><g fill="var(--muted-foreground)" fontSize="11">{ticks.map((tick,index)=><text key={index} x="60" y={y(tick)+4} textAnchor="end">{short(tick)}{suffix}</text>)}</g>{segments.map((items,index)=><polyline key={index} fill="none" stroke="var(--chart-1, #115b45)" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" points={items.map(item=>`${x(item.index)},${y(item.value!)}`).join(' ')}/>)}{valid.map(item=><g key={`${item.label}:${item.index}`} className="group"><circle cx={x(item.index)} cy={y(item.value!)} r="7" fill="var(--card)" stroke="var(--chart-1, #115b45)" strokeWidth="4"><title>{item.label}: {formatted(item.value)}{suffix}</title></circle><text x={x(item.index)} y={Math.max(14,y(item.value!)-13)} textAnchor="middle" fill="var(--foreground)" fontSize="11" fontWeight="700">{short(item.value!)}{suffix}</text></g>)}<g fill="var(--muted-foreground)" fontSize="11">{data.map((item,index)=><text key={`${item.label}:${index}`} x={x(index)} y="250" textAnchor="middle">{item.label}{item.value===null?' · sem dado':''}<title>{item.label}: {formatted(item.value)}{suffix}</title></text>)}</g></svg></div><p className="mt-2 text-xs text-muted-foreground">Passe o mouse sobre um ponto para ver o valor exato. Os valores também aparecem acima de cada ponto e na tabela abaixo.</p></Frame>;
}

export function MultiLineChart({title,data,coverage}:{title:string;data:MultiLineDatum[];coverage:DataCoverage}){
  const series=[...new Set(data.flatMap(item=>item.values.map(value=>value.label)))],flat=data.map(item=>({label:item.label,value:item.values.find(value=>value.label===series[0])?.value??null})),values=data.flatMap(item=>item.values.flatMap(value=>value.value===null?[]:[value.value])),max=Math.max(...values,1),x=(index:number)=>data.length===1?360:70+580*index/(data.length-1),y=(value:number)=>215-170*value/max;
  return <Frame title={title} data={flat} coverage={coverage}><div className="mb-4 flex flex-wrap gap-4 text-xs">{series.map(label=>{const color=data.flatMap(item=>item.values).find(value=>value.label===label)?.color??'#64748b';return <span className="flex items-center gap-2" key={label}><i className="size-3 rounded-full" style={{background:color}}/>{label}</span>})}</div><div className="overflow-x-auto"><svg role="img" aria-label={`Gráfico comparativo de linhas: ${title}`} viewBox="0 0 720 270" className="h-auto min-w-[620px] w-full"><g stroke="var(--border)">{[0,.5,1].map(point=><line key={point} x1="68" x2="660" y1={215-170*point} y2={215-170*point}/>)}</g><g fill="var(--muted-foreground)" fontSize="11">{[max,max/2,0].map((tick,index)=><text key={tick} x="60" y={[49,134,219][index]} textAnchor="end">{short(tick)}</text>)}</g>{series.map(label=>{const points=data.map((item,index)=>({index,value:item.values.find(value=>value.label===label)?.value??null,color:item.values.find(value=>value.label===label)?.color})),segments:typeof points[]=[];let segment:typeof points=[];for(const point of points){if(point.value===null){if(segment.length)segments.push(segment);segment=[]}else segment.push(point)}if(segment.length)segments.push(segment);return <g key={label}>{segments.map((part,index)=><polyline key={index} fill="none" stroke={part[0]?.color??'#64748b'} strokeWidth="3" points={part.map(point=>`${x(point.index)},${y(point.value!)}`).join(' ')}/>)}{points.filter(point=>point.value!==null).map(point=><circle key={point.index} cx={x(point.index)} cy={y(point.value!)} r="5" fill="var(--card)" stroke={point.color} strokeWidth="3"><title>{data[point.index]!.label} · {label}: {formatted(point.value)}</title></circle>)}</g>})}<g fill="var(--muted-foreground)" fontSize="11">{data.map((item,index)=><text key={item.label} x={x(index)} y="245" textAnchor="middle">{item.label}</text>)}</g></svg></div><details className="mt-4 text-sm"><summary className="focus-ring w-fit cursor-pointer font-bold text-primary">Ver comparação mensal</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left"><thead><tr><th className="p-2">Mês</th>{series.map(label=><th className="p-2 text-right" key={label}>{label}</th>)}</tr></thead><tbody>{data.map(item=><tr className="border-t" key={item.label}><th className="p-2">{item.label}</th>{series.map(label=><td className="p-2 text-right" key={label}>{formatted(item.values.find(value=>value.label===label)?.value??null)}</td>)}</tr>)}</tbody></table></div></details></Frame>
}

export function GroupedBarChart({title,data,coverage}:{title:string;data:GroupedDatum[];coverage:DataCoverage}){
  const flat=data.flatMap(group=>group.values.map(value=>({label:`${group.label} · ${value.label}`,value:value.value}))),max=Math.max(...flat.map(item=>item.value??0),1);
  return <Frame title={title} data={flat} coverage={coverage}><div className="space-y-6">{data.map(group=><div key={group.label}><strong className="text-sm">{group.label}</strong><div className="mt-2 grid gap-2">{group.values.map(value=><div key={value.label} className="grid grid-cols-[8rem_1fr_auto] items-center gap-3 text-sm" title={`${group.label} · ${value.label}: ${formatted(value.value)}`}><span className="truncate text-muted-foreground">{value.label}</span><div className="h-4 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full" style={{width:`${100*(value.value??0)/max}%`,background:value.color}}/></div><strong className="min-w-12 text-right tabular-nums">{formatted(value.value)}</strong></div>)}</div></div>)}</div></Frame>;
}

export function BulletChart({title,data,benchmark,coverage}:{title:string;data:{label:string;value:number|null;color:string}[];benchmark:number|null;coverage:DataCoverage}){
  const flat=data.map(item=>({label:item.label,value:item.value===null?null:item.value*100})),reference=benchmark===null?null:benchmark*100;
  return <Frame title={title} data={flat} coverage={coverage}><div className="space-y-5">{data.map(item=><div key={item.label}><div className="mb-1 flex justify-between text-sm"><strong>{item.label}</strong><span>{item.value===null?'Indisponível':`${number.format(item.value*100)}%`}</span></div><div className="relative h-6 rounded-full bg-muted"><div className="h-full rounded-full" style={{width:`${Math.min(100,(item.value??0)*100)}%`,background:item.color}}/>{reference!==null&&<i className="absolute inset-y-[-4px] w-0.5 bg-foreground" style={{left:`${Math.min(100,reference)}%`}} title={`Mediana: ${number.format(reference)}%`}/>}</div></div>)}{reference!==null&&<p className="text-xs text-muted-foreground">A linha vertical marca a mediana do universo: {number.format(reference)}%.</p>}</div></Frame>;
}

const rampVars=['var(--map-5)','var(--map-4)','var(--map-3)','var(--map-2)','var(--map-1)'];
export interface ConcentrationBucket {label:string;value:number}
export function ConcentrationCurve({title,buckets,coverage,note}:{title:string;buckets:ConcentrationBucket[];coverage:DataCoverage;note?:string}){
  const total=buckets.reduce((sum,b)=>sum+b.value,0),flat=buckets.map(b=>({label:b.label,value:b.value}));
  return <Frame title={title} data={flat} coverage={coverage}>
    {note&&<p className="mb-4 text-sm leading-6 text-muted-foreground">{note}</p>}
    <div className="flex h-8 overflow-hidden rounded-full border bg-muted" role="img" aria-label={`Composição do total por faixa: ${buckets.map(b=>`${b.label} ${total?(100*b.value/total).toFixed(1):0}%`).join(', ')}`}>{buckets.map((b,i)=><div key={b.label} title={`${b.label}: ${formatted(b.value)}`} style={{width:`${total?100*b.value/total:0}%`,background:rampVars[i%rampVars.length]}}/>)}</div>
    <div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">{buckets.map((b,i)=><div key={b.label}><span className="flex items-center gap-1.5 text-xs font-semibold text-muted-foreground"><i className="size-2.5 shrink-0 rounded-sm" style={{background:rampVars[i%rampVars.length]}}/>{b.label}</span><strong className="mt-1 block tabular-nums">{total?`${(100*b.value/total).toFixed(1)}%`:'—'}</strong><small className="text-muted-foreground">{formatted(b.value)}</small></div>)}</div>
  </Frame>;
}

export function AreaTrend({title,data,coverage,badge}:{title:string;data:ChartDatum[];coverage:DataCoverage;badge?:string|undefined}){
  const valid=data.map((item,index)=>({...item,index})).filter(item=>item.value!==null),rawMax=Math.max(...valid.map(item=>item.value!),0),max=rawMax*1.12||1,x=(index:number)=>data.length===1?360:70+580*index/(data.length-1),y=(value:number)=>215-165*value/max,segments:typeof valid[]=[];let segment:typeof valid=[];
  data.forEach((item,index)=>{if(item.value===null){if(segment.length)segments.push(segment);segment=[]}else segment.push({...item,index})});if(segment.length)segments.push(segment);
  const ticks=[max,max/2,0],labelStep=Math.max(1,Math.ceil(data.length/10)),showLabel=(index:number)=>index%labelStep===0||index===data.length-1;
  return <Frame title={title} data={data} coverage={coverage}>
    {badge&&<span className="mb-3 inline-flex items-center gap-1.5 rounded-full bg-secondary px-3 py-1 text-xs font-bold text-secondary-foreground">{badge}</span>}
    <div className="overflow-x-auto"><svg role="img" aria-label={`Gráfico de área: ${title}`} viewBox="0 0 720 275" className="h-auto min-w-[620px] w-full">
      <defs><linearGradient id="area-trend-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--chart-1)" stopOpacity=".32"/><stop offset="100%" stopColor="var(--chart-1)" stopOpacity="0"/></linearGradient></defs>
      <g stroke="var(--border)" strokeWidth="1">{ticks.map((tick,index)=><line key={index} x1="68" x2="660" y1={y(tick)} y2={y(tick)}/>)}</g>
      <g fill="var(--muted-foreground)" fontSize="11">{ticks.map((tick,index)=><text key={index} x="60" y={y(tick)+4} textAnchor="end">{short(tick)}</text>)}</g>
      {segments.map((items,index)=>{const line=items.map(item=>`${x(item.index)},${y(item.value!)}`).join(' L '),areaPath=`M ${x(items[0]!.index)},${y(0)} L ${line} L ${x(items[items.length-1]!.index)},${y(0)} Z`;return <g key={index}><path d={areaPath} fill="url(#area-trend-fill)"/><polyline fill="none" stroke="var(--chart-1)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" points={items.map(item=>`${x(item.index)},${y(item.value!)}`).join(' ')}/></g>})}
      {valid.map(item=><circle key={`${item.label}:${item.index}`} cx={x(item.index)} cy={y(item.value!)} r="5" fill="var(--card)" stroke="var(--chart-1)" strokeWidth="3"><title>{item.label}: {formatted(item.value)}</title></circle>)}
      <g fill="var(--muted-foreground)" fontSize="11">{data.map((item,index)=>showLabel(index)&&<text key={`${item.label}:${index}`} x={x(index)} y="250" textAnchor="middle">{item.label}{item.value===null?' · sem dado':''}<title>{item.label}: {formatted(item.value)}</title></text>)}</g>
    </svg></div>
    <p className="mt-2 text-xs text-muted-foreground">Passe o mouse sobre um ponto para ver o valor exato. Meses sem observação aparecem como lacuna, nunca como zero.</p>
  </Frame>;
}

export interface ReachCell {ufs:number;parties:number;suppliers:number}
export function ReachMatrix({title,data,coverage}:{title:string;data:ReachCell[];coverage:DataCoverage}){
  const flat=data.map(item=>({label:`${item.ufs} UF · ${item.parties} partido(s)`,value:item.suppliers})),ufsAxis=[...new Set(data.map(item=>item.ufs))].sort((a,b)=>a-b),partiesAxis=[...new Set(data.map(item=>item.parties))].sort((a,b)=>a-b),max=Math.max(...data.map(item=>item.suppliers),1);
  const find=(ufs:number,parties:number)=>data.find(item=>item.ufs===ufs&&item.parties===parties)?.suppliers??0;
  const cellColor=(value:number)=>value===0?'var(--map-empty)':value/max>.75?'var(--map-5)':value/max>.5?'var(--map-4)':value/max>.25?'var(--map-3)':'var(--map-2)';
  return <Frame title={title} data={flat} coverage={coverage}>
    <div className="overflow-x-auto"><table role="img" aria-label={`Mapa de calor de ${title}: linhas por UFs pagadoras, colunas por partidos pagadores`} className="border-separate border-spacing-1"><thead><tr><th className="p-1"/>{partiesAxis.map(parties=><th key={parties} className="p-1 text-center text-[11px] font-semibold text-muted-foreground">{parties}p</th>)}</tr></thead><tbody>{ufsAxis.map(ufs=><tr key={ufs}><th className="pr-2 text-right text-[11px] font-semibold text-muted-foreground">{ufs}UF</th>{partiesAxis.map(parties=>{const value=find(ufs,parties);return <td key={parties}><div className="grid size-9 place-items-center rounded-md text-[11px] font-bold" style={{background:cellColor(value),color:value/max>.5?'#fff':'var(--foreground)'}} title={`${ufs} UFs · ${parties} partido(s): ${value} fornecedor(es)`}>{value||''}</div></td>})}</tr>)}</tbody></table></div>
    <p className="mt-3 text-xs text-muted-foreground">Linhas: UFs pagadoras distintas. Colunas: partidos pagadores distintos. Célula: fornecedores observados nessa combinação.</p>
  </Frame>;
}

export interface RankedBarItem {key:string;label:string;value:number;href?:string;meta?:string;chip?:ReactNode}
export function RankedBars({title,items,coverage,formatValue}:{title:string;items:RankedBarItem[];coverage:DataCoverage;formatValue?:(value:number)=>string}){
  const max=Math.max(...items.map(item=>item.value),1),flat=items.map(item=>({label:item.label,value:item.value})),format=formatValue??formatted;
  return <Frame title={title} data={flat} coverage={coverage}><div className="space-y-3">{items.map((item,index)=><div key={item.key} className="grid grid-cols-[1.5rem_minmax(0,1fr)_auto] items-center gap-3"><span className="text-xs font-bold text-muted-foreground">{index+1}</span><div className="min-w-0"><div className="flex min-w-0 items-center gap-2"><span className="min-w-0 truncate font-semibold" title={item.label}>{item.href?<Link className="text-primary underline-offset-2 hover:underline" href={item.href}>{item.label}</Link>:item.label}</span>{item.chip}</div>{item.meta&&<small className="block truncate text-muted-foreground">{item.meta}</small>}<div className="mt-1.5 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-chart-1" style={{width:`${100*item.value/max}%`}}/></div></div><strong className="whitespace-nowrap text-right text-sm tabular-nums">{format(item.value)}</strong></div>)}</div></Frame>;
}
