import type { DataCoverage } from '@senadotracker/domain';
import { CoverageBadge } from '@/components/metrics';

export interface ChartDatum {label:string;value:number|null}
export interface MultiLineDatum {label:string;values:{label:string;value:number|null;color:string}[]}
export interface GroupedDatum {label:string;values:{label:string;value:number|null;color:string}[]}
const number=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2});
const compact=new Intl.NumberFormat('pt-BR',{notation:'compact',maximumFractionDigits:1});
const formatted=(value:number|null)=>value===null?'Indisponível':number.format(value);
const short=(value:number)=>Math.abs(value)>=10_000?compact.format(value):number.format(value);

function Frame({title,coverage,children,data}:{title:string;coverage:DataCoverage;children:React.ReactNode;data:ChartDatum[]}){
  const valid=data.filter(item=>item.value!==null);
  if(!valid.length)return <div className="grid min-h-64 place-items-center rounded-2xl border bg-card p-6 text-center"><div><p className="font-bold">{title}</p><p className="mt-2 text-sm text-muted-foreground">{coverage.note}</p><div className="mt-3"><CoverageBadge coverage={coverage}/></div></div></div>;
  return <figure className="rounded-2xl border bg-card p-5"><figcaption className="flex flex-wrap items-center justify-between gap-2 font-bold">{title}<CoverageBadge coverage={coverage}/></figcaption><div className="mt-5">{children}</div><details className="mt-4 text-sm"><summary className="focus-ring w-fit cursor-pointer font-bold text-primary">Ver dados do gráfico</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left"><caption className="sr-only">Dados de {title}</caption><thead><tr className="border-b"><th className="p-2">Categoria</th><th className="p-2 text-right">Valor</th></tr></thead><tbody>{data.map(item=><tr className="border-b" key={item.label}><th className="p-2 font-normal">{item.label}</th><td className="p-2 text-right tabular-nums">{formatted(item.value)}</td></tr>)}</tbody></table></div></details></figure>;
}

export function BarChart({title,data,coverage}:{title:string;data:ChartDatum[];coverage:DataCoverage}){
  const max=Math.max(...data.map(item=>item.value??0),1);
  return <Frame title={title} data={data} coverage={coverage}><div className="space-y-4" aria-label={`Gráfico de barras: ${title}`}>{data.map(item=><div key={item.label} title={`${item.label}: ${formatted(item.value)}`}><div className="mb-1 flex items-end justify-between gap-3 text-sm"><span className="font-medium">{item.label}</span><strong className="tabular-nums">{formatted(item.value)}</strong></div><div className="h-5 overflow-hidden rounded-full border bg-muted"><div className="h-full rounded-full bg-chart-1" style={{width:`${100*(item.value??0)/max}%`}}/></div></div>)}</div></Frame>;
}

export function HistogramChart({title,data,coverage}:{title:string;data:ChartDatum[];coverage:DataCoverage}){
  const max=Math.max(...data.map(item=>item.value??0),1);
  return <Frame title={title} data={data} coverage={coverage}><div className="flex h-64 items-end gap-2 border-b border-l px-3 pt-8" aria-label={`Histograma: ${title}`}>{data.map(item=><div key={item.label} title={`${item.label}: ${formatted(item.value)}`} className="flex h-full min-w-0 flex-1 flex-col justify-end text-center"><strong className="mb-2 truncate text-xs tabular-nums">{item.value===null?'—':short(item.value)}</strong><div className="min-h-px rounded-t bg-chart-1" style={{height:`${100*(item.value??0)/max}%`}}/><span className="mt-2 truncate text-xs text-muted-foreground">{item.label}</span></div>)}</div></Frame>;
}

export interface StackedDatum {label:string;segments:{label:string;value:number;color?:string}[]}
const colors=['bg-chart-1','bg-chart-2','bg-chart-3','bg-chart-4'];
export function StackedBarChart({title,data,coverage}:{title:string;data:StackedDatum[];coverage:DataCoverage}){
  const flattened=data.map(item=>({label:item.label,value:item.segments.reduce((total,segment)=>total+segment.value,0)})),legend=[...new Map(data.flatMap(item=>item.segments).map(segment=>[segment.label,segment])).values()];
  return <Frame title={title} data={flattened} coverage={coverage}><div className="mb-5 flex flex-wrap gap-4 text-xs">{legend.map((segment,index)=><span key={segment.label} className="flex items-center gap-2"><i className={`size-3 rounded-sm ${segment.color??colors[index%colors.length]}`}/>{segment.label}</span>)}</div><div className="space-y-5">{data.map(row=>{const total=row.segments.reduce((value,segment)=>value+segment.value,0);return <div key={row.label}><div className="mb-2 flex justify-between gap-3 text-sm"><strong>{row.label}</strong><span className="tabular-nums">Total: {formatted(total)}</span></div><div className="flex h-7 overflow-hidden rounded-full border bg-muted">{row.segments.map((segment,index)=><div key={segment.label} title={`${row.label} · ${segment.label}: ${formatted(segment.value)}`} className={segment.color??colors[index%colors.length]} style={{width:`${total?100*segment.value/total:0}%`}}><span className="sr-only">{segment.label}: {formatted(segment.value)}</span></div>)}</div><div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground">{row.segments.map(segment=><span key={segment.label}>{segment.label}: <strong className="text-foreground">{formatted(segment.value)}</strong></span>)}</div></div>})}</div></Frame>;
}

export function LineChart({title,data,coverage,min:fixedMin,max:fixedMax,suffix=''}:{title:string;data:ChartDatum[];coverage:DataCoverage;min?:number;max?:number;suffix?:string}){
  const valid=data.map((item,index)=>({...item,index})).filter(item=>item.value!==null),rawMax=Math.max(...valid.map(item=>item.value!),0),rawMin=Math.min(...valid.map(item=>item.value!),0),padding=(rawMax-rawMin)*.12||Math.max(Math.abs(rawMax)*.12,1),max=fixedMax??rawMax+padding,min=fixedMin??Math.min(0,rawMin-padding),x=(index:number)=>data.length===1?360:70+580*index/(data.length-1),y=(value:number)=>215-165*(Math.max(min,Math.min(max,value))-min)/(max-min||1),segments:typeof valid[]=[];let segment:typeof valid=[];
  data.forEach((item,index)=>{if(item.value===null){if(segment.length)segments.push(segment);segment=[]}else segment.push({...item,index})});if(segment.length)segments.push(segment);
  const ticks=[max,(max+min)/2,min];
  return <Frame title={title} data={data} coverage={coverage}><div className="overflow-x-auto"><svg role="img" aria-label={`Gráfico de linha: ${title}`} viewBox="0 0 720 275" className="h-auto min-w-[620px] w-full"><g stroke="var(--border)" strokeWidth="1">{ticks.map((tick,index)=><line key={index} x1="68" x2="660" y1={y(tick)} y2={y(tick)}/>)}</g><g fill="var(--muted-foreground)" fontSize="11">{ticks.map((tick,index)=><text key={index} x="60" y={y(tick)+4} textAnchor="end">{short(tick)}{suffix}</text>)}</g>{segments.map((items,index)=><polyline key={index} fill="none" stroke="var(--chart-1, #115b45)" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" points={items.map(item=>`${x(item.index)},${y(item.value!)}`).join(' ')}/>)}{valid.map(item=><g key={`${item.label}:${item.index}`} className="group"><circle cx={x(item.index)} cy={y(item.value!)} r="7" fill="var(--card)" stroke="var(--chart-1, #115b45)" strokeWidth="4"><title>{item.label}: {formatted(item.value)}{suffix}</title></circle><text x={x(item.index)} y={Math.max(14,y(item.value!)-13)} textAnchor="middle" fill="var(--foreground)" fontSize="11" fontWeight="700">{short(item.value!)}{suffix}</text></g>)}<g fill="var(--muted-foreground)" fontSize="11">{data.map((item,index)=><text key={`${item.label}:${index}`} x={x(index)} y="250" textAnchor="middle">{item.label}{item.value===null?' · sem dado':''}<title>{item.label}: {formatted(item.value)}{suffix}</title></text>)}</g></svg></div><p className="mt-2 text-xs text-muted-foreground">Passe o mouse sobre um ponto para ver o valor exato. Os valores também aparecem acima de cada ponto e na tabela abaixo.</p></Frame>;
}

export function MultiLineChart({title,data,coverage}:{title:string;data:MultiLineDatum[];coverage:DataCoverage}){
  const series=[...new Set(data.flatMap(item=>item.values.map(value=>value.label)))],flat=data.map(item=>({label:item.label,value:item.values.find(value=>value.label===series[0])?.value??null})),values=data.flatMap(item=>item.values.flatMap(value=>value.value===null?[]:[value.value])),max=Math.max(...values,1),x=(index:number)=>data.length===1?360:70+580*index/(data.length-1),y=(value:number)=>215-170*value/max;
  return <Frame title={title} data={flat} coverage={coverage}><div className="mb-4 flex flex-wrap gap-4 text-xs">{series.map(label=>{const color=data.flatMap(item=>item.values).find(value=>value.label===label)?.color??'#64748b';return <span className="flex items-center gap-2" key={label}><i className="size-3 rounded-full" style={{background:color}}/>{label}</span>})}</div><div className="overflow-x-auto"><svg role="img" aria-label={`Gráfico comparativo de linhas: ${title}`} viewBox="0 0 720 270" className="h-auto min-w-[620px] w-full"><g stroke="var(--border)">{[0,.5,1].map(point=><line key={point} x1="68" x2="660" y1={215-170*point} y2={215-170*point}/>)}</g><g fill="var(--muted-foreground)" fontSize="11">{[max,max/2,0].map((tick,index)=><text key={tick} x="60" y={[49,134,219][index]} textAnchor="end">{short(tick)}</text>)}</g>{series.map(label=>{const points=data.map((item,index)=>({index,value:item.values.find(value=>value.label===label)?.value??null,color:item.values.find(value=>value.label===label)?.color})),segments:typeof points[]=[];let segment:typeof points=[];for(const point of points){if(point.value===null){if(segment.length)segments.push(segment);segment=[]}else segment.push(point)}if(segment.length)segments.push(segment);return <g key={label}>{segments.map((part,index)=><polyline key={index} fill="none" stroke={part[0]?.color??'#64748b'} strokeWidth="3" points={part.map(point=>`${x(point.index)},${y(point.value!)}`).join(' ')}/>)}{points.filter(point=>point.value!==null).map(point=><circle key={point.index} cx={x(point.index)} cy={y(point.value!)} r="5" fill="var(--card)" stroke={point.color} strokeWidth="3"><title>{data[point.index]!.label} · {label}: {formatted(point.value)}</title></circle>)}</g>})}<g fill="var(--muted-foreground)" fontSize="11">{data.map((item,index)=><text key={item.label} x={x(index)} y="245" textAnchor="middle">{item.label}</text>)}</g></svg></div><details className="mt-4 text-sm"><summary className="focus-ring w-fit cursor-pointer font-bold text-primary">Ver comparação mensal</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left"><thead><tr><th className="p-2">Mês</th>{series.map(label=><th className="p-2 text-right" key={label}>{label}</th>)}</tr></thead><tbody>{data.map(item=><tr className="border-t" key={item.label}><th className="p-2">{item.label}</th>{series.map(label=><td className="p-2 text-right" key={label}>{formatted(item.values.find(value=>value.label===label)?.value??null)}</td>)}</tr>)}</tbody></table></div></details></Frame>
}

export function GroupedBarChart({title,data,coverage}:{title:string;data:GroupedDatum[];coverage:DataCoverage}){
  const flat=data.flatMap(group=>group.values.map(value=>({label:`${group.label} · ${value.label}`,value:value.value}))),max=Math.max(...flat.map(item=>item.value??0),1);
  return <Frame title={title} data={flat} coverage={coverage}><div className="space-y-6">{data.map(group=><div key={group.label}><strong className="text-sm">{group.label}</strong><div className="mt-2 grid gap-2">{group.values.map(value=><div key={value.label} className="grid grid-cols-[8rem_1fr_auto] items-center gap-3 text-sm" title={`${group.label} · ${value.label}: ${formatted(value.value)}`}><span className="truncate text-muted-foreground">{value.label}</span><div className="h-4 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full" style={{width:`${100*(value.value??0)/max}%`,background:value.color}}/></div><strong className="min-w-12 text-right tabular-nums">{formatted(value.value)}</strong></div>)}</div></div>)}</div></Frame>;
}

export function BulletChart({title,data,benchmark,coverage}:{title:string;data:{label:string;value:number|null;color:string}[];benchmark:number|null;coverage:DataCoverage}){
  const flat=data.map(item=>({label:item.label,value:item.value===null?null:item.value*100})),reference=benchmark===null?null:benchmark*100;
  return <Frame title={title} data={flat} coverage={coverage}><div className="space-y-5">{data.map(item=><div key={item.label}><div className="mb-1 flex justify-between text-sm"><strong>{item.label}</strong><span>{item.value===null?'Indisponível':`${number.format(item.value*100)}%`}</span></div><div className="relative h-6 rounded-full bg-muted"><div className="h-full rounded-full" style={{width:`${Math.min(100,(item.value??0)*100)}%`,background:item.color}}/>{reference!==null&&<i className="absolute inset-y-[-4px] w-0.5 bg-foreground" style={{left:`${Math.min(100,reference)}%`}} title={`Mediana: ${number.format(reference)}%`}/>}</div></div>)}{reference!==null&&<p className="text-xs text-muted-foreground">A linha vertical marca a mediana do universo: {number.format(reference)}%.</p>}</div></Frame>;
}
