'use client';
import { useMemo, useState } from 'react';
import { Check, Search, X } from 'lucide-react';
import { PartyLogo } from '@/components/party-logo';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';

export function ComparisonMultiSelect({name,label,values,initialValues,kind,max=10}:{name:string;label:string;values:string[];initialValues:string[];kind:'party'|'state';max?:number}){
  const [selected,setSelected]=useState(()=>initialValues.filter(value=>values.includes(value)).slice(0,max)),[search,setSearch]=useState('');
  const filtered=useMemo(()=>{const term=search.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();return values.filter(value=>!term||value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(term))},[search,values]);
  const toggle=(value:string)=>setSelected(current=>current.includes(value)?current.filter(item=>item!==value):current.length<max?[...current,value]:current);
  return <fieldset className="lg:col-span-3"><legend className="text-sm font-bold">{label}</legend>{selected.map(value=><input key={value} type="hidden" name={name} value={value}/>)}<div className="mt-2 rounded-2xl border bg-background p-4"><div className="flex min-h-11 flex-wrap items-center gap-2">{selected.length?selected.map(value=><span key={value} className="inline-flex items-center gap-2 rounded-full border bg-secondary py-1.5 pl-2.5 pr-1.5 text-sm font-bold">{kind==='party'?<PartyLogo party={value} size={22}/>:<span className="grid size-6 place-items-center rounded-full bg-primary text-[10px] text-primary-foreground">{value}</span>}{value}<button type="button" onClick={()=>toggle(value)} className="focus-ring grid size-7 place-items-center rounded-full hover:bg-background" aria-label={`Remover ${value}`}><X size={14}/></button></span>):<span className="text-sm text-muted-foreground">Selecione pelo menos duas opções abaixo.</span>}</div><div className="relative mt-4"><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-3 text-muted-foreground" size={17}/><Input value={search} onChange={event=>setSearch(event.target.value)} className="pl-10" placeholder={`Buscar ${kind==='party'?'partido':'estado'}…`} aria-label={`Buscar em ${label.toLowerCase()}`}/></div><div className="mt-3 flex items-center justify-between text-xs text-muted-foreground"><span>{selected.length} selecionado{selected.length===1?'':'s'}</span><span>Máximo de {max}</span></div><div className="mt-3 grid max-h-64 gap-2 overflow-y-auto pr-1 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(value=>{const active=selected.includes(value),disabled=!active&&selected.length>=max;return <button key={value} type="button" aria-pressed={active} disabled={disabled} onClick={()=>toggle(value)} className={cn('focus-ring flex min-h-11 items-center gap-3 rounded-xl border px-3 py-2 text-left text-sm transition-colors',active?'border-primary bg-primary/10 font-bold':'hover:bg-muted',disabled&&'cursor-not-allowed opacity-40')}>{kind==='party'?<PartyLogo party={value} size={25}/>:<span className="grid size-7 place-items-center rounded-full bg-secondary text-[11px] font-bold">{value}</span>}<span className="flex-1">{value}</span>{active&&<Check className="text-primary" size={17}/>}</button>})}{!filtered.length&&<p className="col-span-full py-6 text-center text-sm text-muted-foreground">Nenhuma opção encontrada.</p>}</div></div></fieldset>
}
