import Link from 'next/link';

type Point=Record<string,unknown>;
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',notation:'compact',maximumFractionDigits:1});

export function SupplierMarketScatter({points}:{points:Point[]}){
  const finite=points.filter(point=>Number(point.net)>0&&Number(point.parliamentarians)>0),maxValue=Math.max(...finite.map(point=>Number(point.net)),1),maxReach=Math.max(...finite.map(point=>Number(point.parliamentarians)),1);
  return <section className="rounded-3xl border bg-card p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-black">Tamanho do mercado</h2><p className="mt-1 text-sm text-muted-foreground">Cada ponto representa um fornecedor: valor líquido no eixo vertical e parlamentares distintos no eixo horizontal.</p></div><span className="text-xs text-muted-foreground">Amostra visual: {finite.length.toLocaleString('pt-BR')} maiores valores</span></div><div className="relative mt-6 h-[360px] rounded-2xl border bg-muted/20" aria-label="Gráfico de dispersão de fornecedores"><div className="absolute inset-x-8 bottom-8 top-6 border-b border-l border-muted-foreground/30">{finite.map(point=>{const x=8+Number(point.parliamentarians)/maxReach*88,y=92-Number(point.net)/maxValue*84,size=6+Math.min(12,Math.sqrt(Number(point.records)||1));return <Link key={String(point.supplier_id)} href={`/fornecedores/${String(point.supplier_id)}`} title={`${String(point.name??'Fornecedor')}: ${money.format(Number(point.net)/100)}, ${Number(point.parliamentarians)} parlamentares`} aria-label={`${String(point.name??'Fornecedor')}, ${money.format(Number(point.net)/100)}, ${Number(point.parliamentarians)} parlamentares`} className="absolute rounded-full bg-primary/70 ring-2 ring-background transition hover:bg-primary focus-visible:z-10 focus-visible:bg-primary" style={{left:`${x}%`,top:`${y}%`,width:size,height:size,transform:'translate(-50%,-50%)'}}/>})}</div><span className="absolute bottom-1 left-1/2 -translate-x-1/2 text-xs text-muted-foreground">Parlamentares distintos</span><span className="absolute left-1 top-1/2 -rotate-90 text-xs text-muted-foreground">Valor líquido</span></div><details className="mt-5"><summary className="cursor-pointer text-sm font-bold text-primary">Abrir tabela dos pontos</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Tabela alternativa do gráfico de fornecedores</caption><thead><tr className="border-b"><th className="px-2 py-2">Fornecedor</th><th className="px-2 py-2 text-right">Valor</th><th className="px-2 py-2 text-right">Parlamentares</th><th className="px-2 py-2 text-right">Lançamentos</th></tr></thead><tbody>{finite.slice(0,100).map(point=><tr className="border-b" key={`row-${String(point.supplier_id)}`}><td className="px-2 py-2"><Link className="text-primary underline" href={`/fornecedores/${String(point.supplier_id)}`}>{String(point.name??'Fornecedor sem nome')}</Link></td><td className="px-2 py-2 text-right">{money.format(Number(point.net)/100)}</td><td className="px-2 py-2 text-right">{Number(point.parliamentarians)}</td><td className="px-2 py-2 text-right">{Number(point.records)}</td></tr>)}</tbody></table></div></details></section>;
}
