import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { openDatabase } from '../packages/db/src/index.ts';

const db=openDatabase(resolve('data/senadotracker.sqlite'));
const profiles=db.prepare(`SELECT p.external_id,p.payload FROM profiles p JOIN active_publications a ON a.batch_id=p.batch_id WHERE a.source='camara'`).all();
const clean=(html:string)=>html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&ordf;/gi,'ª').replace(/\s+/g,' ').trim();
const numberAfter=(text:string,label:string)=>{const match=text.match(new RegExp(label+'\\s+(\\d+)','i'));return match?Number(match[1]):null};
function parse(html:string){
  const text=clean(html),sessionCount=numberAfter(text,'Total de sessões deliberativas com Ordem do Dia iniciada[^0-9]*'),daysTotal=numberAfter(text,'Total de dias com sessões deliberativas realizadas no período'),daysPresent=numberAfter(text,'Total de dias com presença nas sessões deliberativas'),daysJustified=numberAfter(text,'Total de dias com ausências justificadas em sessões deliberativas'),daysUnjustified=numberAfter(text,'Total de dias com ausências não justificadas em sessões deliberativas');
  if([sessionCount,daysTotal,daysPresent,daysJustified,daysUnjustified].some(value=>value===null))return null;
  const days=[...html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].flatMap(match=>{const row=clean(match[1]!);const date=row.match(/^(\d{2}\/\d{2}\/\d{4})\s+(.+)$/);if(!date)return[];const status=date[2]!.match(/^(Presença(?: \(~\))?|Ausência|Missão Autorizada|Ausência Justificada|Licença[^\s]*)/i)?.[1]??date[2]!.split('  ')[0]!;return[{date:date[1]!,status}]});
  return{sessionCount:sessionCount!,daysTotal:daysTotal!,daysPresent:daysPresent!,daysJustified:daysJustified!,daysUnjustified:daysUnjustified!,days};
}
const jobs=profiles.flatMap(row=>{const profile=JSON.parse(String(row.payload)) as {mandates:{start:string|null;end:string|null}[]};return Array.from({length:9},(_,i)=>2018+i).filter(year=>profile.mandates.some(m=>!m.start||Number(m.start.slice(0,4))<=year&&(!m.end||Number(m.end.slice(0,4))>=year))).map(year=>({id:String(row.external_id),year}))});
let done=0;const workers=Array.from({length:12},async()=>{while(jobs.length){const job=jobs.shift()!,url=`https://www.camara.leg.br/deputados/${job.id}/presenca-plenario/${job.year}`;for(let attempt=0;attempt<3;attempt++)try{const response=await fetch(url,{headers:{'User-Agent':'SenadoTracker/0.1 (official-data-collector)'},signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`HTTP ${response.status}`);const html=await response.text(),data=parse(html);if(data)db.prepare(`INSERT INTO chamber_official_presence VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(external_id,year) DO UPDATE SET session_count=excluded.session_count,days_total=excluded.days_total,days_present=excluded.days_present,days_justified=excluded.days_justified,days_unjustified=excluded.days_unjustified,days_json=excluded.days_json,official_url=excluded.official_url,fetched_at=excluded.fetched_at,sha256=excluded.sha256`).run(job.id,job.year,data.sessionCount,data.daysTotal,data.daysPresent,data.daysJustified,data.daysUnjustified,JSON.stringify(data.days),url,new Date().toISOString(),createHash('sha256').update(html).digest('hex'));break}catch(error){if(attempt===2)console.error(`${job.id}/${job.year}: ${error instanceof Error?error.message:error}`)}if(++done%100===0)console.log(`${done} páginas processadas`)}});
await Promise.all(workers);console.log(`${done} páginas processadas; ${db.prepare('SELECT count(*) n FROM chamber_official_presence').get()!.n} resumos publicados`);db.close();
