import {performance} from 'node:perf_hooks';
import {openDatabase,publishedParticipationRows,publishedPersonElectoralProfile,publishedCabinetProfile} from '@senadotracker/db';
const db=openDatabase('data/senadotracker.sqlite',true);
try{
  const ids=['204560','204379'],rows=db.prepare(`SELECT p.person_id,p.external_id FROM profiles p JOIN active_publications a ON a.batch_id=p.batch_id WHERE a.source='camara'`).all(),allIds=rows.map(row=>String(row.external_id));
  for(const [name,fn] of [['participation',()=>publishedParticipationRows(db,'camara',2026,allIds)],['electoral',()=>ids.map(id=>publishedPersonElectoralProfile(db,String(rows.find(row=>row.external_id===id)?.person_id)))],['cabinet',()=>ids.map(id=>publishedCabinetProfile(db,'camara',id))]] as const){const start=performance.now();fn();console.log(name,Math.round(performance.now()-start))}
  for(const [name,sql,args] of [['orientations',`SELECT c.payload FROM legislative_complements c JOIN active_complement_publications a ON a.batch_id=c.batch_id WHERE a.source=? AND c.kind='orientation'`,['camara']],['expense totals',`SELECT external_id,sum(net_cents-refund_cents) value FROM expenses WHERE batch_id=(SELECT batch_id FROM active_expense_publications WHERE source='camara' AND year=2026) GROUP BY external_id`,[]],['all deliberations',`SELECT external_id,payload FROM deliberations WHERE batch_id=(SELECT batch_id FROM active_legislative_publications WHERE source='camara' AND year=2026)`,[]]] as const){const start=performance.now(),result=db.prepare(sql).all(...args);console.log(name,Math.round(performance.now()-start),result.length)}
  const marks=ids.map(()=>'?').join(',');for(const [name,sql,args] of [['production',`SELECT x.person_external_id external_id,count(DISTINCT x.proposal_id) proposals,count(DISTINCT CASE WHEN l.proposal_id IS NOT NULL THEN x.proposal_id END) laws FROM proposal_authors x JOIN proposals p ON p.batch_id=x.batch_id AND p.external_id=x.proposal_id JOIN active_activity_publications a ON a.batch_id=x.batch_id LEFT JOIN law_links l ON l.batch_id=x.batch_id AND l.proposal_id=x.proposal_id WHERE a.source=? AND x.person_external_id IN (${marks}) AND COALESCE(json_extract(p.payload,'$.year'),CAST(substr(json_extract(p.payload,'$.presentedAt'),1,4) AS INTEGER))=? GROUP BY x.person_external_id`,['camara',...ids,2026]],['rapporteurs',`SELECT person_external_id external_id,count(*) value FROM legislative_appointments x JOIN active_activity_publications a ON a.batch_id=x.batch_id WHERE a.source=? AND x.kind='rapporteurship' AND x.person_external_id IN (${marks}) AND substr(COALESCE(json_extract(x.payload,'$.start'),''),1,4)=? GROUP BY person_external_id`,['camara',...ids,'2026']]] as const){const start=performance.now(),result=db.prepare(sql).all(...args);console.log(name,Math.round(performance.now()-start),result.length)}
  const expenseBatch=db.prepare("SELECT batch_id FROM active_expense_publications WHERE source='camara' AND year=2026").get();const expenseSql=`SELECT external_id,category_code,category,month,count(*) records,sum(net_cents-refund_cents) value FROM expenses WHERE batch_id=? AND external_id IN (${marks}) GROUP BY external_id,category_code,category,month`;const expenseStart=performance.now();const expenseRows=db.prepare(expenseSql).all(String(expenseBatch?.batch_id),...ids);console.log('selected expenses',Math.round(performance.now()-expenseStart),expenseRows.length);
  console.log('expense plan',db.prepare(`EXPLAIN QUERY PLAN ${expenseSql}`).all(String(expenseBatch?.batch_id),...ids));
  const voteBatch=db.prepare("SELECT batch_id FROM active_legislative_publications WHERE source='camara' AND year=2026").get(),voteSql=`SELECT v.payload FROM legislative_votes v JOIN deliberations d ON d.batch_id=v.batch_id AND d.external_id=v.deliberation_id WHERE v.batch_id=? AND v.external_id IN (${marks}) AND substr(d.date,1,10)<='2026-09-21'`;const voteStart=performance.now(),voteRows=db.prepare(voteSql).all(String(voteBatch?.batch_id),...ids);console.log('selected votes',Math.round(performance.now()-voteStart),voteRows.length);
  const cabinetBatch=db.prepare("SELECT batch_id FROM active_cabinet_budget_publications WHERE source='camara' AND year=2026").get(),cabinetSql=`SELECT external_id,month,sum(spent_cents) value FROM cabinet_monthly_budgets WHERE batch_id=? AND external_id IN (${marks}) AND spent_cents IS NOT NULL GROUP BY external_id,month`;const cabinetStart=performance.now(),cabinetRows=db.prepare(cabinetSql).all(String(cabinetBatch?.batch_id),...ids);console.log('selected cabinet',Math.round(performance.now()-cabinetStart),cabinetRows.length);
}finally{db.close()}
