import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openDatabase } from '@senadotracker/db';
import type { Proposal } from '@senadotracker/domain';
import { resolveCamaraPrincipalProposals } from '../../apps/collector/src/principal-proposal-resolver.ts';
import { saveRaw } from '../../apps/collector/src/raw.ts';

const child=(id:string,parent:string):Proposal=>({source:'camara',externalId:id,type:'REQ',functionalGroup:'requerimentos',number:id,year:2026,label:`REQ ${id}/2026`,summary:null,presentedAt:'2026-01-01',status:null,officialUrl:`https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=${id}`,rawId:'catalog',principalProposalId:parent,relationshipEvidence:'official_uri',catalogRole:'catalog'});
const detail=(id:string,parent?:string)=>({dados:{id:Number(id),siglaTipo:'PL',numero:Number(id),ano:id==='900'?1999:1988,ementa:`Pai ${id}`,dataApresentacao:id==='900'?'1999-02-03':'1988-04-05',statusProposicao:{descricaoSituacao:'Arquivada'},...(parent?{uriPropPrincipal:`https://dadosabertos.camara.leg.br/api/v2/proposicoes/${parent}`}:{})}});

test('resolver deduplica pais, preserva ano real, percorre cadeia e é idempotente',async()=>{const directory=await mkdtemp(join(tmpdir(),'principal-resolver-')),db=openDatabase(join(directory,'db.sqlite'));let calls=0;const factory=(runId:string)=>({json:async(url:string)=>{calls++;const match=/proposicoes\/(\d+)/.exec(url),id=match?.[1]??'';const data=url.endsWith('/temas')?{dados:[{codTema:40,tema:`Tema ${id}`,relevancia:1}]}:detail(id,id==='900'?'901':undefined);const fetchedAt='2026-09-23T12:00:00.000Z',bytes=Buffer.from(JSON.stringify(data)),rawId=await saveRaw(db,runId,directory,{url,fetchedAt,status:200,contentType:'application/json',bytes});return{data,rawId,fetchedAt,url}}});try{const first=await resolveCamaraPrincipalProposals(db,{children:[child('1','900'),child('2','900')],rawDirectory:directory,clientFactory:factory,maxDepth:3,concurrency:2});assert.equal(first.missingBefore,1);assert.equal(first.resolved,2);assert.equal(first.requests,4);assert.equal(calls,4);assert.equal(db.prepare('SELECT count(*) n FROM principal_proposal_support').get()!.n,2);const stored=JSON.parse(String(db.prepare("SELECT payload FROM principal_proposal_support WHERE external_id='900'").get()!.payload));assert.equal(stored.year,1999);assert.equal(stored.catalogRole,'relationship_support');assert.equal(db.prepare('SELECT count(*) n FROM principal_proposal_dependencies').get()!.n,3);const second=await resolveCamaraPrincipalProposals(db,{children:[child('1','900'),child('2','900')],rawDirectory:directory,clientFactory:factory});assert.equal(second.missingBefore,0);assert.equal(second.requests,0);assert.equal(calls,4);assert.equal(db.prepare('SELECT count(*) n FROM principal_proposal_support').get()!.n,2)}finally{db.close()}});

test('falha do pai fica registrada sem criar suporte nem lançar a coleta',async()=>{const directory=await mkdtemp(join(tmpdir(),'principal-failure-')),db=openDatabase(join(directory,'db.sqlite'));try{const result=await resolveCamaraPrincipalProposals(db,{children:[child('3','999')],rawDirectory:directory,clientFactory:()=>({json:async()=>{throw new Error('API indisponível')}})});assert.equal(result.failed,1);assert.equal(result.remaining,1);assert.equal(db.prepare("SELECT state FROM principal_proposal_dependencies WHERE parent_id='999'").get()!.state,'failed');assert.equal(db.prepare('SELECT count(*) n FROM principal_proposal_support').get()!.n,0)}finally{db.close()}});
