import test from 'node:test';import assert from 'node:assert/strict';import { openDatabase, publishedProposition, publishedPropositions } from '@senadotracker/db';import { proposalFunctionalGroup, type Proposal, type ProposalAuthor } from '@senadotracker/domain';
function seed(){const db=openDatabase(':memory:'),run='activity',raw='raw-proposal';db.prepare("INSERT INTO ingestion_runs(id,source,started_at,status,parser_version,roster_complete) VALUES (?,'senado','2026-09-09','published','test',1)").run(run);db.prepare("INSERT INTO raw_objects VALUES (?,?,?,'2026-09-09',200,'application/json',?,?,0)").run(raw,run,'https://example.invalid/proposal','0'.repeat(64),'raw/proposal');db.prepare("INSERT INTO activity_batches VALUES (?,'senado','proposals','2026-09-09',1,1,0,0)").run(run);db.prepare("INSERT INTO active_activity_publications VALUES ('senado','proposals',?)").run(run);const proposal:Proposal={source:'senado',externalId:'p-1',type:'PL',functionalGroup:'proposicoes_legislativas_principais',number:'10',year:2026,label:'PL 10/2026',summary:'Política pública de educação',presentedAt:'2026-02-01',status:null,officialUrl:'https://example.invalid/proposal',rawId:raw};const author:ProposalAuthor={proposalId:'p-1',externalId:null,name:'Autora Oficial',party:null,uf:null,kind:'author',primary:true,order:1,rawId:raw};db.prepare("INSERT INTO proposals(batch_id,source,external_id,raw_id,payload,grupo_atribuido) VALUES (?,'senado','p-1',?,?,?)").run(run,raw,JSON.stringify(proposal),proposal.functionalGroup);db.prepare("INSERT INTO proposal_authors VALUES (?,'p-1','author',NULL,?,?)").run(run,raw,JSON.stringify(author));return db}
test('busca de proposições combina texto e autoria com ordem determinística',()=>{const db=seed();try{const result=publishedPropositions(db,{search:'educacao',author:'autora',page:1,pageSize:10});assert.equal(result.total,1);assert.equal(result.items[0]!.proposal.externalId,'p-1');assert.equal(result.items[0]!.proposal.status,null);assert.equal(result.coverage.sampleSize,1)}finally{db.close()}});
test('detalhe mantém complementos ausentes e votação ausente como lacunas',()=>{const db=seed();try{const result=publishedProposition(db,'senado','p-1');assert.ok(result);assert.deepEqual(result.themes,[]);assert.deepEqual(result.movements,[]);assert.deepEqual(result.deliberations,[]);assert.equal(result.coverage.availability,'available')}finally{db.close()}});
test('detalhe vincula votação da outra Casa por tipo, número e ano',()=>{const db=seed();try{const run='vote-camara',raw='raw-vote';db.prepare("INSERT INTO ingestion_runs(id,source,started_at,status,parser_version,roster_complete) VALUES (?,'camara','2026-09-09','published','test',1)").run(run);db.prepare("INSERT INTO raw_objects VALUES (?,?,?,'2026-09-09',200,'application/json',?,?,0)").run(raw,run,'https://example.invalid/vote','1'.repeat(64),'raw/vote');db.prepare("INSERT INTO legislative_batches VALUES (?,'camara',2026,'2026-09-09',1,0)").run(run);db.prepare("INSERT INTO active_legislative_publications VALUES ('camara',2026,?)").run(run);const deliberation={source:'camara',externalId:'d-1',date:'2026-03-01',chamberBody:'PLEN',proposalId:'camara-99',proposalLabel:'PL 10/2026',description:'Votação da matéria',result:'Aprovada',officialUrl:'https://example.invalid/vote',rawId:raw};db.prepare("INSERT INTO deliberations VALUES (?,'camara','d-1',2026,'2026-03-01',?,?)").run(run,raw,JSON.stringify(deliberation));const result=publishedProposition(db,'senado','p-1');assert.ok(result);assert.equal(result.deliberations.length,1);assert.equal(result.deliberations[0]!.coverage.source,'camara');assert.match(result.deliberations[0]!.coverage.note,/tipo, número e ano/)}finally{db.close()}});

test('classifica siglas em grupos funcionais e usa grupo especial como fallback',()=>{
  assert.equal(proposalFunctionalGroup('PL'),'proposicoes_legislativas_principais');
  assert.equal(proposalFunctionalGroup(' rqs '),'requerimentos');
  assert.equal(proposalFunctionalGroup('SBE-A'),'emendas_substitutivos');
  assert.equal(proposalFunctionalGroup('PARF'),'pareceres_relatorios');
  assert.equal(proposalFunctionalGroup('RPD'),'instrumentos_votacao_tramitacao');
  assert.equal(proposalFunctionalGroup('SUG'),'indicacoes_sugestoes');
  assert.equal(proposalFunctionalGroup('MSF'),'mensagens_comunicacoes_institucionais');
  assert.equal(proposalFunctionalGroup('OFS'),'oficios_documentos');
  assert.equal(proposalFunctionalGroup('PET'),'recursos_representacoes_peticoes');
  assert.equal(proposalFunctionalGroup('TIPO-NOVO'),'atos_documentos_especiais');
});
test('busca por identificador usa tipo, numero e ano da proposicao',()=>{const db=seed();try{assert.equal(publishedPropositions(db,{search:'PL 10/2026'}).total,1);assert.equal(publishedPropositions(db,{search:'pl 10'}).total,1);assert.equal(publishedPropositions(db,{search:'PL 10/2025'}).total,0)}finally{db.close()}});
