import test from 'node:test';
import assert from 'node:assert/strict';
import {backfillExpenseSupplierIdentities,openDatabase,publishExpenses,startRun,supplierIdentitySummary} from '@senadotracker/db';
import type {Expense} from '@senadotracker/domain';

const expense=(source:'senado'|'camara',key:string,supplier:string,document:string|null):Expense=>({source,externalId:source==='senado'?'1':'2',year:2026,month:1,recordKey:key,categoryCode:'1',category:'Teste',supplier,supplierDocument:document,documentNumber:null,documentId:null,documentUrl:null,issuedAt:'2026-01-10',grossCents:1000,deductionCents:0,netCents:1000,refundCents:0,installment:null,detail:null,rawId:`raw-${source}`});

function seed(){const db=openDatabase(':memory:');for(const source of ['senado','camara'] as const){const roster=startRun(db,source);const person=`person-${source}`,externalId=source==='senado'?'1':'2';db.prepare("INSERT INTO raw_objects VALUES (?,?,?,?,'200','application/json',?,?,0)").run(`roster-raw-${source}`,roster,'https://example.test',new Date().toISOString(),'0'.repeat(64),`raw/roster-${source}`);db.prepare("UPDATE ingestion_runs SET status='validated',roster_complete=1,expected_count=1 WHERE id=?").run(roster);db.prepare('INSERT INTO staged_profiles VALUES (?,?,?)').run(roster,externalId,JSON.stringify({source,externalId,name:'Pessoa',fullName:null,uf:'DF',party:'P',photoUrl:null,officialUrl:'https://example.test',observedAt:'2026-01-01',historyAvailability:'available',mandates:[],exercises:[],parties:[],events:[],rawId:`roster-raw-${source}`}));db.prepare('INSERT INTO publication_batches VALUES (?,?,?)').run(roster,source,new Date().toISOString());db.prepare('INSERT INTO people VALUES (?,?)').run(person,new Date().toISOString());db.prepare('INSERT INTO external_identifiers VALUES (?,?,?)').run(source,externalId,person);db.prepare('INSERT INTO active_publications VALUES (?,?)').run(source,roster);db.prepare("UPDATE ingestion_runs SET status='published',finished_at=? WHERE id=?").run(new Date().toISOString(),roster);db.prepare('DELETE FROM job_locks WHERE run_id=?').run(roster);const run=startRun(db,source);db.prepare("INSERT INTO raw_objects VALUES (?,?,?,?,'200','text/plain',?,?,0)").run(`raw-${source}`,run,'https://example.test',new Date().toISOString(),'1'.repeat(64),`raw/${source}`);const values=source==='senado'?[expense(source,'s1','Vivo','02.558.157/0001-62'),expense(source,'s2','Sentinela','00.000.000/0000-10')]:[expense(source,'c1','Telefonica Brasil SA','02558157000162'),expense(source,'c2','Sem documento',null)];publishExpenses(db,run,source,2026,values)}return db}

test('backfill global une CNPJ forte, preserva aliases e ignora sentinela/ausente',()=>{const db=seed();try{const dry=backfillExpenseSupplierIdentities(db,null,{dryRun:true});assert.equal(dry.suppliers,1);assert.equal(dry.strongRows,2);assert.equal(dry.unresolvedRows,2);assert.equal(dry.sentinel,1);const run=startRun(db,'civica');const first=backfillExpenseSupplierIdentities(db,run,{now:'2026-09-23T00:00:00.000Z'});assert.equal(first.published,true);assert.equal(supplierIdentitySummary(db).suppliers,1);assert.equal(supplierIdentitySummary(db).links,2);assert.equal(db.prepare('SELECT count(*) n FROM supplier_names').get()!.n,2);assert.equal(db.prepare('SELECT count(*) n FROM supplier_roles').get()!.n,2);assert.equal(db.prepare("SELECT count(*) n FROM supplier_identity_review_queue WHERE validation_status='sentinel' AND status='pending'").get()!.n,1);const secondRun=startRun(db,'civica');backfillExpenseSupplierIdentities(db,secondRun,{now:'2026-09-24T00:00:00.000Z'});assert.equal(supplierIdentitySummary(db).suppliers,1);assert.equal(supplierIdentitySummary(db).links,2);assert.equal(db.prepare('SELECT count(*) n FROM supplier_names').get()!.n,2)}finally{db.close()}});
