import Link from 'next/link';
import {ArrowRight,BarChart3,Coins,FileText,Search,Trophy,Users,Vote} from 'lucide-react';
import {partyLanding} from '@/lib/data';
import {LegislativeSubnav} from '@/components/legislative-subnav';
import {InstitutionHero} from '@/components/heroes';
import {PartyLogo} from '@/components/party-logo';
import {PartySeats} from '@/components/party-seats';
import {EmptyState} from '@/components/empty-state';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {searchText} from '@senadotracker/domain';

export const dynamic='force-dynamic';
export const metadata={title:'Partidos no Congresso'};
type Params=Record<string,string|string[]|undefined>;
const scalar=(value:string|string[]|undefined)=>typeof value==='string'?value:undefined;
const number=new Intl.NumberFormat('pt-BR');
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const percent=new Intl.NumberFormat('pt-BR',{style:'percent',maximumFractionDigits:1});
const names:Record<string,string>={AVANTE:'Avante',CIDADANIA:'Cidadania',DC:'Democracia Cristã',MDB:'Movimento Democrático Brasileiro',MISSÃO:'Partido Missão',NOVO:'Partido Novo',PCdoB:'Partido Comunista do Brasil',PDT:'Partido Democrático Trabalhista',PL:'Partido Liberal',PODE:'Podemos',PP:'Progressistas',PRD:'Partido Renovação Democrática',PSB:'Partido Socialista Brasileiro',PSD:'Partido Social Democrático',PSDB:'Partido da Social Democracia Brasileira',PSOL:'Partido Socialismo e Liberdade',PT:'Partido dos Trabalhadores',PV:'Partido Verde',REDE:'Rede Sustentabilidade',REPUBLICANOS:'Republicanos',SOLIDARIEDADE:'Solidariedade',UNIÃO:'União Brasil'};
const tones=['bg-emerald-50 text-emerald-800','bg-sky-50 text-sky-800','bg-amber-50 text-amber-800','bg-violet-50 text-violet-800','bg-teal-50 text-teal-800'];

function SectionTitle({number:section,title,description}:{number:number;title:string;description:string}){return <div className="mb-7 flex items-start gap-4"><span aria-hidden="true" className="grid size-10 shrink-0 place-items-center rounded-full bg-secondary text-lg font-black text-primary">{section}</span><div><h2 className="text-2xl font-black tracking-tight sm:text-3xl">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div></div>}
function Stat({icon:Icon,label,value,detail,tone}:{icon:typeof Users;label:string;value:string;detail:string;tone:string}){return <div className="min-w-0 rounded-2xl border bg-card p-4 shadow-sm"><span className={`inline-grid size-10 place-items-center rounded-xl ${tone}`}><Icon size={20}/></span><p className="mt-4 text-xs font-bold leading-5 text-muted-foreground">{label}</p><strong className="mt-1 block break-words text-2xl font-black leading-tight">{value}</strong><p className="mt-2 text-xs leading-5 text-muted-foreground">{detail}</p></div>}
function PartyCard({party,deputies,senators}:{party:string;deputies:number;senators:number}){return <Link prefetch={false} href={`/legislativo/partidos/${encodeURIComponent(party)}`} className="focus-ring group flex min-h-48 flex-col rounded-2xl border bg-card p-4 shadow-sm transition hover:border-primary hover:shadow-md"><div className="flex items-start gap-3"><PartyLogo party={party} size={48}/><div className="min-w-0"><strong className="block truncate text-lg">{party}</strong><p className="line-clamp-2 text-xs text-muted-foreground">{names[party]??'Sigla no cadastro parlamentar'}</p></div></div><div className="mt-5 space-y-1 text-sm"><p><strong>{number.format(deputies)}</strong> deputados federais</p><p><strong>{number.format(senators)}</strong> senadores</p></div><span className="mt-auto inline-flex items-center gap-1 pt-5 text-sm font-bold text-primary">Ver partido <ArrowRight size={15} className="transition group-hover:translate-x-0.5"/></span></Link>}
function date(value:string|null){if(!value)return'Data de publicação não informada';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'Data de publicação não informada':new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeZone:'UTC'}).format(parsed)}

export default async function PartiesPage({searchParams}:{searchParams:Promise<Params>}){
  const q=await searchParams,rawYear=Number(scalar(q.ano)),year=Number.isInteger(rawYear)&&rawYear>2000?rawYear:null,search=scalar(q.busca)?.trim()??'',house=scalar(q.casa)==='camara'?'camara':scalar(q.casa)==='senado'?'senado':'all',order=scalar(q.ordem)==='cadeiras'?'cadeiras':'nome',rawPage=Number(scalar(q.pagina)??1),page=Number.isSafeInteger(rawPage)&&rawPage>0?rawPage:1,showAll=scalar(q.todos)==='1';
  const result=partyLanding(year);
  if(result.status==='unavailable')return <><LegislativeSubnav/><main id="conteudo" className="page-shell py-12"><EmptyState title="Partidos indisponíveis" description={result.message}/></main></>;
  const data=result.data,rows=data.panorama.rows.filter(row=>row.senators+row.deputies>0),represented=rows.length,totalSeats=rows.reduce((sum,row)=>sum+row.senators+row.deputies,0),largest=[...rows].sort((a,b)=>(b.senators+b.deputies)-(a.senators+a.deputies)||a.party.localeCompare(b.party,'pt-BR'))[0];
  const authored=[...rows].map(row=>({party:row.party,count:data.authoredByParty[row.party]??0})).sort((a,b)=>b.count-a.count||a.party.localeCompare(b.party,'pt-BR'));
  const participation=[...rows].flatMap(row=>{const value=data.participationByParty[row.party];return value&&value.n>=3?[{party:row.party,...value}]:[]}).sort((a,b)=>b.mean-a.mean||a.party.localeCompare(b.party,'pt-BR'))[0];
  const costByHouse=data.costByHouse??{senado:[],camara:[]};
  const senateCost=costByHouse.senado[0],chamberCost=costByHouse.camara[0];
  const filtered=rows.filter(row=>(house==='all'||(house==='senado'?row.senators:row.deputies)>0)&&(!search||searchText(`${row.party} ${names[row.party]??''}`).includes(searchText(search)))).sort((a,b)=>order==='cadeiras'?(b.senators+b.deputies)-(a.senators+a.deputies)||a.party.localeCompare(b.party,'pt-BR'):a.party.localeCompare(b.party,'pt-BR'));
  const pageSize=10,totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),visible=showAll?filtered.slice((Math.min(page,totalPages)-1)*pageSize,Math.min(page,totalPages)*pageSize):filtered.slice(0,pageSize);
  const href=(values:Record<string,string|number|undefined>)=>{const p=new URLSearchParams();for(const [key,value] of Object.entries({ano:data.year,casa:house,ordem:order,...(search?{busca:search}:{}),...values}))if(value!==undefined&&value!=='')p.set(key,String(value));return `/legislativo/partidos?${p}#todos-partidos`};
  const houseCosts=([['senado','Senado Federal'],['camara','Câmara dos Deputados']] as const).map(([source,label])=>({source,label,...data.operations[source].costs}));
  return <><LegislativeSubnav/><main id="conteudo" tabIndex={-1}>
    <div className="page-shell py-8"><InstitutionHero context="Representação partidária" title="Partidos no Congresso" description="Veja a composição das bancadas, a autoria de proposições e as parcelas de custo identificadas nas fontes oficiais." imageUrl="/congresso.svg" location="Senado Federal e Câmara dos Deputados" actions={<form action="/legislativo/partidos#todos-partidos" className="flex w-full max-w-lg gap-2 rounded-2xl bg-white p-2 text-foreground"><input type="hidden" name="ano" value={data.year}/><label className="relative min-w-0 flex-1"><Search aria-hidden="true" size={18} className="absolute left-3 top-3 text-muted-foreground"/><span className="sr-only">Buscar partido</span><Input name="busca" defaultValue={search} placeholder="Buscar partido (ex.: MDB, PT, PL...)" className="border-0 pl-10"/></label><Button>Buscar</Button></form>}/></div>
    <div className="page-shell border-b pb-4 text-right text-xs text-muted-foreground">Dados publicados até {date(data.updatedAt)} · indicadores de {data.year}</div>
    <section className="page-shell py-12"><SectionTitle number={1} title="Partidos no Congresso em números" description="Panorama da representação partidária no Congresso Nacional."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat icon={Users} label="Partidos representados" value={number.format(represented)} detail="com ao menos um parlamentar em exercício" tone={tones[0]!}/><Stat icon={Trophy} label="Maior bancada" value={largest?.party??'—'} detail={largest?`${number.format(largest.senators+largest.deputies)} cadeiras · ${percent.format((largest.senators+largest.deputies)/totalSeats)} do Congresso`:'Sem cadastro'} tone={tones[1]!}/><Stat icon={FileText} label="Mais proposições de autoria" value={authored[0]?.count?authored[0].party:'—'} detail={authored[0]?.count?`${number.format(authored[0].count)} proposições distintas em ${data.year}`:'Sem autoria vinculada no período'} tone={tones[2]!}/><Stat icon={Vote} label="Maior participação média nominal" value={participation?.party??'—'} detail={participation?`${percent.format(participation.mean)} · n=${participation.n} parlamentares observáveis`:'Amostra insuficiente'} tone={tones[3]!}/><Stat icon={Coins} label="Maior custo médio mensal por Casa" value={`${senateCost?.party??'—'} · ${chamberCost?.party??'—'}`} detail={`Senado: ${senateCost?`${money.format(senateCost.meanMonthlyCents/100)} · n=${senateCost.n}`:'sem amostra'}; Câmara: ${chamberCost?`${money.format(chamberCost.meanMonthlyCents/100)} · n=${chamberCost.n}`:'sem amostra'}`} tone={tones[4]!}/></div><p className="mt-4 text-xs text-muted-foreground">Presença e participação nominal são medidas diferentes. As médias de votação respeitam o universo elegível de cada Casa. Os custos somam cota, gabinete e subsídio somente em competências comuns; cada Casa tem seu próprio universo.</p></section>
    <section className="border-y bg-card"><div className="page-shell py-12"><SectionTitle number={2} title="Como as cadeiras estão distribuídas entre os partidos?" description="Número de parlamentares por partido no cadastro em exercício."/><PartySeats rows={rows}/></div></section>
    <section className="page-shell py-12"><SectionTitle number={3} title="Atuação legislativa dos partidos" description={`Temas oficiais e proposições de autoria identificada em ${data.year}.`}/><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border bg-card p-6"><p className="text-sm font-bold text-muted-foreground">Tema mais frequente nas proposições de autoria</p><Trophy className="mt-7 text-amber-600" size={30}/><strong className="mt-4 block text-2xl leading-tight">{data.topTheme?.label??'Tema oficial indisponível'}</strong><p className="mt-3 text-sm text-muted-foreground">{data.topTheme?`${number.format(data.topTheme.count)} proposições distintas com esse tema; uma matéria pode ter mais de um tema.`:'Nenhum tema oficial ligado ao universo de autoria deste período.'}</p></div><div className="rounded-2xl border bg-card p-6"><h3 className="text-lg font-bold">Partidos com mais proposições</h3><p className="mt-1 text-xs text-muted-foreground">Autoria identificada no período · contagem distinta por partido.</p><ol className="mt-5 divide-y">{authored.slice(0,5).map((row,index)=><li key={row.party} className="flex items-center justify-between gap-3 py-3"><Link prefetch={false} href={`/legislativo/partidos/${encodeURIComponent(row.party)}`} className="focus-ring flex items-center gap-2 font-bold hover:text-primary"><span className="w-5 text-xs text-muted-foreground">{index+1}</span><PartyLogo party={row.party} size={28}/>{row.party}</Link><strong className="tabular-nums">{number.format(row.count)}</strong></li>)}</ol></div></div><p className="mt-4 text-xs text-muted-foreground">{number.format(data.authoredTotal)} de {number.format(data.authoredUniverse)} proposições com autoria têm partido identificado; {number.format(data.themedTotal)} dessas possuem tema oficial. Coautoria pode vincular uma matéria a mais de um partido.</p></section>
    <section className="border-y bg-card"><div className="page-shell py-12">
      <SectionTitle number={4} title="Quanto custam as bancadas?" description="Parcelas mensais identificadas, separadas por Casa para preservar os conceitos oficiais."/>
      <div className="grid gap-5 lg:grid-cols-2">{houseCosts.map(item=>{
        const parts=[{label:'Subsídios',value:item.salaryMonthly,color:'bg-emerald-900'},{label:'Cota parlamentar',value:item.expenseMonthly,color:'bg-emerald-600'},{label:'Gabinetes',value:item.cabinetMonthly,color:'bg-emerald-300'}],complete=item.totalMonthly!==null;
        return <div key={item.source} className="rounded-2xl border bg-background p-6">
          <div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-primary">{item.label}</p><h3 className="mt-2 text-xl font-black">Custo mensal identificado</h3></div><BarChart3 className="text-primary" size={22}/></div>
          <strong className="mt-5 block break-words text-3xl font-black text-primary">{complete?money.format(item.totalMonthly!/100):'Indisponível'}</strong>
          <p className="mt-2 text-sm text-muted-foreground">{complete&&item.roster?`${money.format(item.totalMonthly!/item.roster/100)} por parlamentar · n=${item.roster}`:'Sem competência comum para todas as parcelas.'}</p>
          <p className="mt-1 text-xs text-muted-foreground">{item.months?.length?`Competências comuns: ${item.months.join(', ')}`:'Período comum não disponível'}</p>
          {complete&&<div className="mt-6 flex h-4 overflow-hidden rounded-full bg-muted" role="img" aria-label={`Composição mensal do ${item.label}: ${parts.map(part=>`${part.label} ${money.format((part.value??0)/100)}`).join(', ')}`}>{parts.map(part=><span key={part.label} className={part.color} style={{width:`${(part.value??0)/item.totalMonthly!*100}%`}}/>)}</div>}
          <div className="mt-4 grid gap-2 text-xs sm:grid-cols-3">{parts.map(part=><div key={part.label}><span className="text-muted-foreground">{part.label}</span><strong className="block">{part.value===null?'—':money.format(part.value/100)}</strong><span className="text-muted-foreground">{complete&&part.value!==null?percent.format(part.value/item.totalMonthly!):'Sem proporção'}</span></div>)}</div>
        </div>;
      })}</div>
      <div className="mt-5 grid gap-4 lg:grid-cols-2">{(['senado','camara'] as const).map(source=><div key={source} className="rounded-2xl border bg-background p-5"><h3 className="font-bold">Bancadas com maior custo médio mensal identificado · {source==='senado'?'Senado':'Câmara'}</h3><p className="mt-1 text-xs text-muted-foreground">Média por parlamentar com cota, gabinete e subsídio no mesmo mês; mínimo de três pessoas observáveis.</p>{costByHouse[source].length?<ol className="mt-4 space-y-3">{costByHouse[source].slice(0,3).map((row,index)=><li key={row.party} className="flex items-center justify-between gap-3 text-sm"><Link prefetch={false} href={`/legislativo/partidos/${encodeURIComponent(row.party)}`} className="focus-ring inline-flex items-center gap-2 font-bold hover:text-primary"><span className="w-4 text-xs text-muted-foreground">{index+1}</span><PartyLogo party={row.party} size={26}/>{row.party}</Link><span className="text-right"><strong className="block">{money.format(row.meanMonthlyCents/100)}</strong><small className="text-muted-foreground">n={row.n} · {row.observedPersonMonths} pessoa-meses</small></span></li>)}</ol>:<p className="mt-4 text-sm text-muted-foreground">Sem amostra mensal comparável nesta Casa.</p>}</div>)}</div>
      <p className="mt-4 text-xs text-muted-foreground">Cota e gabinete usam apenas competências comuns em cada Casa; o subsídio é o valor normativo multiplicado pelos parlamentares do cadastro atual. A folha do Senado e a verba utilizada da Câmara são conceitos diferentes, por isso não há um total único do Congresso.</p>
    </div></section>
    <section id="todos-partidos" className="page-shell scroll-mt-6 py-12"><SectionTitle number={5} title="Explore os partidos" description="Conheça os partidos do Congresso e acesse seus dados detalhados."/><form action="/legislativo/partidos#todos-partidos" className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-[2fr_1fr_1fr_auto]"><input type="hidden" name="ano" value={data.year}/>{showAll&&<input type="hidden" name="todos" value="1"/>}<label className="text-xs font-bold">Buscar partido<Input name="busca" defaultValue={search} placeholder="Buscar partido..." className="mt-1"/></label><label className="text-xs font-bold">Ordenar por<select name="ordem" defaultValue={order} className="mt-1 h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value="nome">Nome (A–Z)</option><option value="cadeiras">Mais cadeiras</option></select></label><label className="text-xs font-bold">Casa<select name="casa" defaultValue={house} className="mt-1 h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value="all">Todas</option><option value="camara">Câmara</option><option value="senado">Senado</option></select></label><Button className="self-end">Aplicar</Button></form>{visible.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{visible.map(row=><PartyCard key={row.party} party={row.party} deputies={row.deputies} senators={row.senators}/>)}</div>:<EmptyState title="Nenhum partido encontrado" description="Altere a busca ou o filtro de Casa para explorar outras siglas."/>}<div className="mt-6 flex flex-wrap items-center justify-between gap-3 text-sm"><p className="text-muted-foreground">Mostrando {visible.length?showAll?(Math.min(page,totalPages)-1)*pageSize+1:1:0}–{showAll?Math.min(page,totalPages)*pageSize>filtered.length?filtered.length:Math.min(page,totalPages)*pageSize:visible.length} de {filtered.length} partidos</p>{showAll?<nav aria-label="Paginação dos partidos" className="flex items-center gap-2">{page>1&&<Link href={href({todos:1,pagina:page-1})} className="focus-ring rounded-full border px-3 py-2">Anterior</Link>}<span>Página {Math.min(page,totalPages)} de {totalPages}</span>{page<totalPages&&<Link href={href({todos:1,pagina:page+1})} className="focus-ring rounded-full border px-3 py-2">Próxima</Link>}</nav>:filtered.length>10?<Link href={href({todos:1,pagina:1})} className="focus-ring inline-flex items-center gap-1 font-bold text-primary hover:underline">Ver todos os partidos ({filtered.length}) <ArrowRight size={16}/></Link>:null}</div></section>
  </main></>;
}
