import Link from 'next/link';
import { BarChart3 } from 'lucide-react';
import type { Source } from '@senadotracker/domain';
import type { VoteAxis } from '@senadotracker/db';
import { comparisonDashboard, partyComparison, personComparisonSetup, statesComparison, voteAxis } from '@/lib/data';
import { LegislativeSubnav } from '@/components/legislative-subnav';
import { InstitutionHero } from '@/components/heroes';
import { EmptyState } from '@/components/empty-state';
import { PartyLogo } from '@/components/party-logo';
import { OfficialPortrait } from '@/components/app-image';
import { BarChart, BulletChart, GroupedBarChart, MultiLineChart } from '@/components/charts';
import { ComparisonAgreementMatrix } from '@/components/comparison-agreement-matrix';
import { ComparisonVoteAxis } from '@/components/comparison-vote-axis';
import { CoverageBadge } from '@/components/metrics';
import { Card, CardContent } from '@/components/ui/card';
import { Button, buttonVariants } from '@/components/ui/button';
import { NativeSelect } from '@/components/ui/native-select';
import { ComparisonMultiSelect } from '@/components/comparison-multi-select';
import { ComparisonCosts } from '@/components/comparison-costs';
import { ComparisonPatrimony } from '@/components/comparison-patrimony';

export const dynamic='force-dynamic';
type Params=Record<string,string|string[]|undefined>;
const scalar=(value:string|string[]|undefined)=>typeof value==='string'?value:undefined;
const list=(value:string|undefined)=>[...new Set((value??'').split(',').map(item=>item.trim()).filter(Boolean))];
const colors=['#115b45','#4059ad','#d97706','#7c3aed','#be123c','#0891b2','#4d7c0f','#c2410c','#4338ca','#0f766e'];
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const number=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1});
const ufs='AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO'.split(' ');

export default async function ComparePage({searchParams}:{searchParams:Promise<Params>}){
  const query=await searchParams,mode=scalar(query.modo)==='partidos'?'partidos':scalar(query.modo)==='estados'?'estados':'parlamentares',source:Source=scalar(query.casa)==='camara'?'camara':'senado';
  const [setup,other]=[personComparisonSetup(source),personComparisonSetup(source==='senado'?'camara':'senado')];
  if(setup.status==='unavailable')return <><LegislativeSubnav/><main className="page-shell py-12"><EmptyState title="Comparação indisponível" description={setup.message}/></main></>;
  const years=[...new Set([...setup.data.years,...(other.status==='available'?other.data.years:[])])].sort((a,b)=>b-a),requested=Number(scalar(query.ano)),year=Number.isInteger(requested)&&years.includes(requested)?requested:(years[0]??new Date().getFullYear());
  const ids=scalar(query.pessoas)?list(scalar(query.pessoas)):[1,2,3,4].map(index=>scalar(query[`pessoa${index}`])).filter((item):item is string=>Boolean(item));
  const selectedParties=query.partidos?list(scalar(query.partidos)):list(Array.isArray(query.partido)?query.partido.join(','):scalar(query.partido));
  const selectedUfs=query.ufs?list(scalar(query.ufs)):list(Array.isArray(query.uf)?query.uf.join(','):scalar(query.uf));
  const result=mode==='parlamentares'&&ids.length>=2&&ids.length<=4?comparisonDashboard(source,year,ids):mode==='partidos'&&selectedParties.length>=2&&selectedParties.length<=10?partyComparison(year,selectedParties):mode==='estados'&&selectedUfs.length>=2&&selectedUfs.length<=10?statesComparison(year,selectedUfs):null;
  const partyOptions=[...new Set([...setup.data.options,...(other.status==='available'?other.data.options:[])].map(item=>item.party))].sort();
  // O eixo é da Casa, não do recorte: só é buscado quando há comparação de pessoas para destacar nele.
  const axisResult=mode==='parlamentares'&&result?.status==='available'?voteAxis(source):null,axis=axisResult?.status==='available'?axisResult.data:null;
  return <><LegislativeSubnav/><main id="conteudo" tabIndex={-1}><div className="page-shell py-8"><InstitutionHero context="Comparação multidimensional" title="Compare representantes, partidos e estados" description="Cada painel conserva unidade, período, universo e cobertura próprios. Nenhuma nota geral é calculada." imageUrl="/congresso.svg" location="Congresso Nacional"/></div><section className="page-shell py-10"><ModeNav mode={mode}/><div className="mt-6"><SelectionForm mode={mode} source={source} year={year} years={years} options={setup.data.options} ids={ids} partyOptions={partyOptions} selectedParties={selectedParties} selectedUfs={selectedUfs}/></div>{result?.status==='unavailable'&&<div className="mt-8"><EmptyState title="Recorte incompatível" description={result.message}/></div>}{result?.status==='available'&&mode==='parlamentares'&&<PersonPanels data={result.data as PersonData} axis={axis}/>} {result?.status==='available'&&mode==='partidos'&&<PartyPanels data={result.data as PartyData}/>} {result?.status==='available'&&mode==='estados'&&<StatePanels data={result.data as StateData} house={source}/>} {!result&&<div className="mt-8"><EmptyState title={`Escolha ${mode==='parlamentares'?'de dois a quatro parlamentares':mode==='partidos'?'de dois a dez partidos':'de dois a dez estados'}`} description="A seleção fica registrada na URL e pode ser compartilhada."/></div>}</section></main></>;
}

function ModeNav({mode}:{mode:string}){return <nav aria-label="Modo de comparação" className="flex flex-wrap gap-2">{[['parlamentares','Parlamentares'],['partidos','Partidos'],['estados','Estados']].map(([id,label])=><Link key={id} href={`/comparar?modo=${id}`} className={buttonVariants({variant:mode===id?'default':'outline'})}>{label}</Link>)}</nav>}

function SelectionForm({mode,source,year,years,options,ids,partyOptions,selectedParties,selectedUfs}:{mode:string;source:Source;year:number;years:number[];options:{externalId:string;name:string;party:string;uf:string}[];ids:string[];partyOptions:string[];selectedParties:string[];selectedUfs:string[]}){return <Card><CardContent className="p-6"><form action="/comparar" method="get" className="grid gap-4 lg:grid-cols-4"><input type="hidden" name="modo" value={mode}/>{mode!=='partidos'&&<label className="text-sm font-bold">Casa<NativeSelect name="casa" defaultValue={source} className="mt-2"><option value="senado">Senado</option><option value="camara">Câmara</option></NativeSelect></label>}<label className="text-sm font-bold">Ano<NativeSelect name="ano" defaultValue={String(year)} className="mt-2">{years.map(item=><option key={item}>{item}</option>)}</NativeSelect></label>{mode==='parlamentares'&&[0,1,2,3].map(index=><label key={index} className="text-sm font-bold">Parlamentar {index+1}{index>1?' (opcional)':''}<NativeSelect name={`pessoa${index+1}`} defaultValue={ids[index]??''} className="mt-2" required={index<2}><option value="">Selecione</option>{options.map(item=><option key={item.externalId} value={item.externalId}>{item.name} · {item.party}/{item.uf}</option>)}</NativeSelect></label>)}{mode==='partidos'&&<ComparisonMultiSelect name="partido" label="Partidos" values={partyOptions} initialValues={selectedParties} kind="party"/>} {mode==='estados'&&<ComparisonMultiSelect name="uf" label="Estados" values={ufs} initialValues={selectedUfs} kind="state"/>}<Button className="lg:col-span-4">Atualizar comparação</Button></form></CardContent></Card>}


type PersonData=Extract<ReturnType<typeof comparisonDashboard>,{status:'available'}>['data'];
function PersonPanels({data,axis}:{data:PersonData;axis:VoteAxis|null}){
  const names=new Map(data.people.map(item=>[item.profile.externalId,item.profile.name])),metric=(id:string,key:'presence'|'participation')=>{const item=data.people.find(person=>person.profile.externalId===id)?.participation[key];return item?.numerator!==null&&item?.denominator?item.numerator/item.denominator:null},color=(id:string)=>colors[data.people.findIndex(item=>item.profile.externalId===id)]!,removeHref=(id:string)=>`/comparar?${new URLSearchParams({modo:'parlamentares',casa:data.source,ano:String(data.year),pessoas:data.people.filter(item=>item.profile.externalId!==id).map(item=>item.profile.externalId).join(',')})}`;
  return <div className="mt-8 space-y-8"><div className="sticky top-2 z-20 flex flex-wrap gap-3 rounded-2xl border bg-background/95 p-4 shadow-sm backdrop-blur">{data.people.map((item,index)=><div key={item.profile.externalId} className="flex items-center gap-3 rounded-full border py-2 pl-2 pr-2" style={{borderColor:colors[index]}}><Link href={`/parlamentares/${data.source}/${item.profile.externalId}`} className="flex items-center gap-3"><span className="relative size-9 overflow-hidden rounded-full"><OfficialPortrait src={item.profile.photoUrl} name={item.profile.name} sizes="36px"/></span><PartyLogo party={item.profile.party} size={24}/><span><strong className="block text-sm">{item.profile.name}</strong><small>{item.profile.party}/{item.profile.uf}</small></span></Link><Link href={removeHref(item.profile.externalId)} aria-label={`Remover ${item.profile.name} da comparação`} className="focus-ring rounded-full px-2 py-1 text-lg" title="Remover">×</Link></div>)}</div>
  <ComparisonCosts data={data} palette={colors}/><section className="grid min-w-0 gap-6 xl:grid-cols-2"><div className="min-w-0 xl:col-span-2"><MultiLineChart title="Gasto mensal da cota · R$" data={(data.expenses[0]?.months??[]).map((month,index)=>({label:month.label,values:data.expenses.map(item=>({label:names.get(item.externalId)!,value:item.months[index]?.valueCents===null?null:(item.months[index]?.valueCents??0)/100,color:color(item.externalId)}))}))} coverage={data.coverage.expenses}/></div></section>
  <section className="grid gap-6 xl:grid-cols-2"><BulletChart title="Presença em sessões elegíveis" data={data.people.map(item=>({label:item.profile.name,value:metric(item.profile.externalId,'presence'),color:color(item.profile.externalId)}))} benchmark={data.benchmarks.presence.median} coverage={{...data.coverage.votes,note:'Presença em sessões usa o lote próprio de assiduidade.'}}/><BulletChart title="Participação em votações nominais" data={data.people.map(item=>({label:item.profile.name,value:metric(item.profile.externalId,'participation'),color:color(item.profile.externalId)}))} benchmark={data.benchmarks.participation.median} coverage={data.coverage.votes}/></section>
  <GroupedBarChart title={`Produção legislativa em ${data.year}`} data={data.people.map(item=>({label:item.profile.name,values:[{label:'Propostas',value:item.production.proposals,color:color(item.profile.externalId)},{label:'Relatorias',value:item.production.rapporteurships,color:color(item.profile.externalId)},{label:'Leis ligadas',value:item.production.laws,color:color(item.profile.externalId)}]}))} coverage={data.coverage.production}/>
  <section><h2 className="text-2xl font-bold">Gabinete</h2><p className="mt-2 text-sm text-muted-foreground">{data.source==='senado'?'Folha identificada e vínculos do Senado.':'Verba utilizada e vínculos da Câmara.'} O período acompanha cada observação.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{data.cabinet.map(item=><MetricCard key={item.externalId} title={names.get(item.externalId)!} color={color(item.externalId)} value={item.financialCents===null?'Indisponível':money.format(item.financialCents/100)} detail={`${item.staff??'—'} vínculos · ${item.period??'período indisponível'}`}/>)}</div></section>
  <ComparisonPatrimony data={data} palette={colors}/>
  <ComparisonAgreementMatrix data={data} palette={colors}/>
  {axis&&<ComparisonVoteAxis axis={axis} highlights={data.people.map((item,index)=>({externalId:item.profile.externalId,name:item.profile.name,color:colors[index]??'#115b45'}))}/>}
  <section className="grid gap-6 xl:grid-cols-2">{data.fidelity.some(item=>item.total>0)
    ? <div><BulletChart title="Fidelidade à orientação partidária" data={data.fidelity.map(item=>({label:names.get(item.externalId)!,value:item.ratio,color:color(item.externalId)}))} benchmark={null} coverage={{...data.coverage.votes,note:'Votos comparáveis diante de orientação oficial; orientações livres ou ausentes ficam fora do denominador.'}}/><p className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-muted-foreground">{data.fidelity.map(item=><span key={item.externalId} className="inline-flex items-center gap-1.5"><i className="size-2.5 rounded-full" style={{background:color(item.externalId)}} aria-hidden="true"/>{names.get(item.externalId)}: {item.aligned} alinhados em n={item.total}; {item.excluded} excluídos</span>)}</p></div>
    // Sem orientação publicada nos lotes ativos a fidelidade não é zero — é inobservável. Um gráfico
    // vazio afirmaria a primeira coisa; este aviso diz a segunda.
    : <div className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-bold">Fidelidade à orientação partidária</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Os lotes ativos não trazem orientação de bancada para as votações deste recorte, então a fidelidade não é calculável. Isso não significa fidelidade zero: significa que a orientação oficial ainda não foi publicada na fonte para estas deliberações.</p><div className="mt-4"><CoverageBadge coverage={{...data.coverage.votes,availability:'unavailable',note:'Orientação de bancada ausente nos lotes complementares ativos.',sampleSize:0}}/></div></div>}
    <div className="rounded-2xl border border-dashed p-6 text-sm text-muted-foreground"><BarChart3 className="mb-3"/><strong className="text-foreground">Sem nota geral.</strong><p className="mt-2">Gastos, presença, participação, produção, gabinete e eleições conservam escalas e universos próprios.</p></div></section></div>
}

type PartyData=Extract<ReturnType<typeof partyComparison>,{status:'available'}>['data'];
function PartyPanels({data}:{data:PartyData}){return <div className="mt-8 grid gap-6 xl:grid-cols-2"><GroupedBarChart title="Representação no Congresso" data={data.rows.map((item,index)=>({label:item.party,values:[{label:'Senadores',value:item.senators,color:colors[index%colors.length]!},{label:'Deputados',value:item.deputies,color:colors[index%colors.length]!}]}))} coverage={data.coverage}/><BarChart title="Cota mediana · R$" data={data.rows.map(item=>({label:item.party,value:item.expenseMedianCents===null?null:item.expenseMedianCents/100}))} coverage={data.coverage}/><BulletChart title="Presença mediana" data={data.rows.map((item,index)=>({label:item.party,value:item.presenceMedian,color:colors[index%colors.length]!}))} benchmark={null} coverage={data.coverage}/><BulletChart title="Participação mediana em votações" data={data.rows.map((item,index)=>({label:item.party,value:item.participationMedian,color:colors[index%colors.length]!}))} benchmark={null} coverage={data.coverage}/><div className="xl:col-span-2"><GroupedBarChart title="Produção legislativa" data={data.rows.map((item,index)=>({label:item.party,values:[{label:'Propostas',value:item.proposals,color:colors[index%colors.length]!},{label:'Relatorias',value:item.rapporteurships,color:colors[index%colors.length]!},{label:'Leis ligadas',value:item.laws,color:colors[index%colors.length]!}]}))} coverage={data.coverage}/></div></div>}
type StateData=Extract<ReturnType<typeof statesComparison>,{status:'available'}>['data'];
// As medianas por UF são publicadas por Casa: cota, presença e votações não se somam entre Senado e
// Câmara. O painel escolhe uma Casa e diz qual, em vez de exibir uma média sem universo comum.
function StatePanels({data,house}:{data:StateData;house:Source}){
  const label=house==='senado'?'Senado':'Câmara',of=house==='senado'?'do Senado':'da Câmara',rows=data.rows.map(item=>({uf:item.uf,senators:item.senators,deputies:item.deputies,...item.byHouse[house]}));
  const coverage={availability:rows.some(item=>item.representatives)?'available':'unavailable',source:house,period:{from:`${data.year}-01-01`,to:`${data.year}-12-31`,grain:'year'},batchId:null,note:`Cadastros ativos e observações compatíveis ${of} no mesmo ano.`,sampleSize:rows.length} as const;
  return <div className="mt-8 grid gap-6 xl:grid-cols-2"><GroupedBarChart title="Representação por estado" data={data.rows.map((item,index)=>({label:item.uf,values:[{label:'Senadores',value:item.senators,color:colors[index%colors.length]!},{label:'Deputados',value:item.deputies,color:colors[index%colors.length]!}]}))} coverage={{...coverage,source:'multiple',note:'Cadastros ativos das duas Casas no mesmo ano.'}}/><BarChart title={`Cota mediana · ${label} · R$`} data={rows.map(item=>({label:item.uf,value:item.expenseCents.median===null?null:item.expenseCents.median/100}))} coverage={coverage}/><BulletChart title={`Presença mediana · ${label}`} data={rows.map((item,index)=>({label:item.uf,value:item.presence.median,color:colors[index%colors.length]!}))} benchmark={null} coverage={coverage}/><BulletChart title={`Participação mediana · ${label}`} data={rows.map((item,index)=>({label:item.uf,value:item.participation.median,color:colors[index%colors.length]!}))} benchmark={null} coverage={coverage}/></div>;
}
function MetricCard({title,value,detail,color}:{title:string;value:string;detail:string;color?:string}){return <article className="rounded-2xl border border-t-4 bg-card p-5" style={color?{borderTopColor:color}:{}}><h3 className="font-bold">{title}</h3><p className="mt-4 text-2xl font-black">{value}</p><p className="mt-2 text-xs text-muted-foreground">{detail}</p></article>}


